/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from/home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <syscall_table.h>
#define syss(routine, nargs)    { nargs, routine }
#define sysg(routine, nargs)    { E_GENERIC, emul_generic }
#define sysr(routine)           { E_CHANGE_REGS, routine }
#define syse(routine)           { E_GENERIC, routine }
int emul_generic();
int e_htg_syscall();
int bsd_pid_by_task();
int bsd_task_by_pid();
int bsd_init_process();
#define e_setgroups	bsd_setgroups
#define e_sethostname	bsd_sethostname
#define e_connect	bsd_connect
#define e_bind		bsd_bind
#define e_adjtime	bsd_adjtime
#define e_setrlimit	bsd_setrlimit
#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
int e_fork();
int e_read();
int e_write();
int e_open();
int e_creat();
int e_link();
int e_unlink();
int e_execv();
int e_chdir();
int e_mknod();
int e_chmod();
int e_chown();
int e_obreak();
int e_mount();
int e_unmount();
int e_saccess();
int e_chflags();
int e_fchflags();
int e_sync();
int e_stat();
int e_lstat();
int e_sigprocmask();
int e_sysacct();
#if MAP_UAREA
int e_sigpending();
#else
#endif
#ifdef notyet
#else
#endif
int e_ioctl();
int e_reboot();
int e_symlink();
int e_readlink();
int e_execve();
#if NMAP_UAREA
int e_umask();
#else
#endif
int e_chroot();
int e_fstat();
int e_vfork();
int e_smmap();
int e_setgroups();
int e_setitimer();
int e_wait();
int e_sethostname();
int e_fcntl();
int e_select();
int e_fsync();
int e_connect();
int e_accept();
int e_send();
int e_sigreturn();
int e_bind();
int e_setsockopt();
#if MAP_UAREA
int e_sigblock();
int e_sigsetmask();
#else
#endif
int e_sigstack();
int e_getrusage();
int e_getsockopt();
int e_readv();
int e_writev();
int e_settimeofday();
int e_fchown();
int e_fchmod();
int e_recvfrom();
int e_rename();
int e_truncate();
int e_ftruncate();
int e_flock();
int e_mkfifo();
int e_sendto();
int e_mkdir();
int e_rmdir();
int e_utimes();
int e_adjtime();
int e_getpeername();
#if MAP_UAREA
int e_getrlimit();
#else
#endif
int e_setrlimit();
int e_quotactl();
int e_quota();
int e_getsockname();
#if NFS
#else
#endif
int e_getdirentries();
int e_statfs();
int e_fstatfs();
#if NFS
int e_getfh();
#else
#endif
#if SYSVSHM
#else
#endif
int e_table();
int e___sysctl();
struct sysent sysent[] = {
#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
	sysg(e_indir, 0),				/* 0 */
	sysg(e_rexit, 1),				/* 1 */
	sysr(e_fork),			/* 2 */
	syse(e_read),			/* 3 */
	syss(e_write, 3),		/* 4 */
	syss(e_open, 3),		/* 5 */
	sysg(e_close, 1),				/* 6 */
	sysg(e_wait4, 4),				/* 7 */
	syss(e_creat, 2),		/* 8 */
	syss(e_link, 2),		/* 9 */
	syss(e_unlink, 1),		/* 10 */
	sysr(e_execv),			/* 11 */
	syss(e_chdir, 1),		/* 12 */
	sysg(e_fchdir, 1),				/* 13 */
	syss(e_mknod, 3),		/* 14 */
	syss(e_chmod, 2),		/* 15 */
	syss(e_chown, 3),		/* 16 */
	syse(e_obreak),			/* 17 */
	sysg(e_getfsstat, 3),				/* 18 */
	sysg(e_lseek, 3),				/* 19 */
	sysg(e_getpid, 0),				/* 20 */
	syss(e_mount, 4),		/* 21 */
	syss(e_unmount, 2),		/* 22 */
	sysg(e_setuid, 1),				/* 23 */
	sysg(e_getuid, 0),				/* 24 */
	sysg(e_geteuid, 0),				/* 25 */
	sysg(e_ptrace, 4),				/* 26 */
	sysg(e_recvmsg, 3),				/* 27 */
	sysg(e_sendmsg, 3),				/* 28 */
	sysg(e_recvfrom, 6),				/* 29 */
	sysg(e_accept, 3),				/* 30 */
	sysg(e_getpeername, 3),				/* 31 */
	sysg(e_getsockname, 3),				/* 32 */
	syss(e_saccess, 2),		/* 33 */
	syss(e_chflags, 2),		/* 34 */
	syss(e_fchflags, 2),		/* 35 */
	syss(e_sync, 0),		/* 36 */
	sysg(e_kill, 2),				/* 37 */
	syss(e_stat, 2),		/* 38 */
	sysg(e_getppid, 0),				/* 39 */
	syss(e_lstat, 2),		/* 40 */
	sysg(e_dup, 1),				/* 41 */
	sysg(e_pipe, 1),				/* 42 */
	sysg(e_getegid, 0),				/* 43 */
	sysg(e_profil, 4),				/* 44 */
	sysg(e_ktrace, 0),				/* 45 */
	sysg(e_sigaction, 3),				/* 46 */
	sysg(e_getgid, 0),				/* 47 */
	syse(e_sigprocmask),			/* 48 */
	sysg(e_getlogin, 0),				/* 49 */
	sysg(e_setlogin, 1),				/* 50 */
	syss(e_sysacct, 1),		/* 51 */
#if MAP_UAREA
	syse(e_sigpending),			/* 52 */
#else
	sysg(e_sigpending, 1),				/* 52 */
#endif
#ifdef notyet
#else
	sysg(e_sigaltstack, 3),				/* 53 */
#endif
	syss(e_ioctl, 3),		/* 54 */
	syss(e_reboot, 1),		/* 55 */
	sysg(e_revoke, 1),				/* 56 */
	syss(e_symlink, 2),		/* 57 */
	syss(e_readlink, 3),		/* 58 */
	sysr(e_execve),			/* 59 */
#if NMAP_UAREA
	syse(e_umask),			/* 60 */
#else
	sysg(e_umask, 1),				/* 60 */
#endif
	syss(e_chroot, 1),		/* 61 */
	syss(e_fstat, 2),		/* 62 */
	sysg(e_getkerninfo, 4),				/* 63 */
	sysg(e_getpagesize, 0),				/* 64 */
	sysg(e_msync, 2),				/* 65 */
	sysr(e_vfork),			/* 66 */
	sysg(e_vread, 0),				/* 67 */
	sysg(e_vwrite, 0),				/* 68 */
	sysg(e_sbrk, 1),				/* 69 */
	sysg(e_sstk, 1),				/* 70 */
	syse(e_smmap),			/* 71 */
	sysg(e_ovadvise, 0),				/* 72 */
	sysg(e_munmap, 2),				/* 73 */
	sysg(e_mprotect, 3),				/* 74 */
	sysg(e_madvise, 3),				/* 75 */
	sysg(e_vhangup, 0),				/* 76 */
	sysg(e_vlimit, 0),				/* 77 */
	sysg(e_mincore, 3),				/* 78 */
	sysg(e_getgroups, 2),				/* 79 */
	syss(e_setgroups, 2),		/* 80 */
	sysg(e_getpgrp, 0),				/* 81 */
	sysg(e_setpgid, 2),				/* 82 */
	syss(e_setitimer, 3),		/* 83 */
	sysr(e_wait),			/* 84 */
	sysg(e_swapon, 1),				/* 85 */
	sysg(e_getitimer, 2),				/* 86 */
	sysg(e_gethostname, 2),				/* 87 */
	syss(e_sethostname, 2),		/* 88 */
	sysg(e_getdtablesize, 0),				/* 89 */
	sysg(e_dup2, 2),				/* 90 */
	sysg(e_getdopt, 2),				/* 91 */
	syss(e_fcntl, 3),		/* 92 */
	syss(e_select, 5),		/* 93 */
	sysg(e_setdopt, 2),				/* 94 */
	syss(e_fsync, 1),		/* 95 */
	sysg(e_setpriority, 3),				/* 96 */
	sysg(e_socket, 3),				/* 97 */
	syss(e_connect, 3),		/* 98 */
	syss(e_accept, 3),		/* 99 */
	sysg(e_getpriority, 2),				/* 100 */
	syss(e_send, 4),		/* 101 */
	sysg(e_recv, 4),				/* 102 */
	sysr(e_sigreturn),			/* 103 */
	syss(e_bind, 3),		/* 104 */
	syss(e_setsockopt, 5),		/* 105 */
	sysg(e_listen, 2),				/* 106 */
	sysg(e_vtimes, 0),				/* 107 */
	sysg(e_sigvec, 3),				/* 108 */
#if MAP_UAREA
	syse(e_sigblock),			/* 109 */
	syse(e_sigsetmask),			/* 110 */
#else
	sysg(e_sigblock, 1),				/* 109 */
	sysg(e_sigsetmask, 1),				/* 110 */
#endif
	sysg(e_sigsuspend, 1),				/* 111 */
	syss(e_sigstack, 2),		/* 112 */
	sysg(e_recvmsg, 3),				/* 113 */
	sysg(e_sendmsg, 3),				/* 114 */
	sysg(e_vtrace, 2),				/* 115 */
	sysg(e_gettimeofday, 2),				/* 116 */
	syss(e_getrusage, 2),		/* 117 */
	syss(e_getsockopt, 5),		/* 118 */
	sysg(e_nosys, 0),				/* 119 */
	syss(e_readv, 3),		/* 120 */
	syss(e_writev, 3),		/* 121 */
	syss(e_settimeofday, 2),		/* 122 */
	syss(e_fchown, 3),		/* 123 */
	syss(e_fchmod, 2),		/* 124 */
	syss(e_recvfrom, 6),		/* 125 */
	sysg(e_setreuid, 2),				/* 126 */
	sysg(e_setregid, 2),				/* 127 */
	syss(e_rename, 2),		/* 128 */
	syss(e_truncate, 2),		/* 129 */
	syss(e_ftruncate, 2),		/* 130 */
	syss(e_flock, 2),		/* 131 */
	syss(e_mkfifo, 2),		/* 132 */
	syss(e_sendto, 6),		/* 133 */
	sysg(e_shutdown, 2),				/* 134 */
	sysg(e_socketpair, 4),				/* 135 */
	syss(e_mkdir, 2),		/* 136 */
	syss(e_rmdir, 1),		/* 137 */
	syss(e_utimes, 2),		/* 138 */
	sysg(e_4.2, 0),				/* 139 */
	syss(e_adjtime, 2),		/* 140 */
	syss(e_getpeername, 3),		/* 141 */
	sysg(e_gethostid, 0),				/* 142 */
	sysg(e_sethostid, 1),				/* 143 */
#if MAP_UAREA
	syse(e_getrlimit),			/* 144 */
#else
	sysg(e_getrlimit, 2),				/* 144 */
#endif
	syss(e_setrlimit, 2),		/* 145 */
	sysg(e_killpg, 2),				/* 146 */
	sysg(e_setsid, 0),				/* 147 */
	syss(e_quotactl, 4),		/* 148 */
	syss(e_quota, 4),		/* 149 */
	syss(e_getsockname, 3),		/* 150 */
	sysg(e_nosys, 0),				/* 151 */
	sysg(e_nosys, 0),				/* 152 */
	sysg(e_nosys, 0),				/* 153 */
	sysg(e_nosys, 0),				/* 154 */
#if NFS
	sysg(e_nfssvc, 5),				/* 155 */
#else
	sysg(e_nosys, 0),				/* 155 */
#endif
	syss(e_getdirentries, 4),		/* 156 */
	syss(e_statfs, 2),		/* 157 */
	syss(e_fstatfs, 2),		/* 158 */
	sysg(e_nosys, 0),				/* 159 */
	sysg(e_nosys, 0),				/* 160 */
#if NFS
	syss(e_getfh, 2),		/* 161 */
#else
	sysg(e_nosys, 0),				/* 161 */
#endif
	sysg(e_getdomainname, 2),				/* 162 */
	sysg(e_setdomainname, 2),				/* 163 */
	sysg(e_uname, 1),				/* 164 */
	sysg(e_nosys, 0),				/* 165 */
	sysg(e_nosys, 0),				/* 166 */
	sysg(e_nosys, 0),				/* 167 */
	sysg(e_nosys, 0),				/* 168 */
	sysg(e_nosys, 0),				/* 169 */
	sysg(e_nosys, 0),				/* 170 */
#if SYSVSHM
	sysg(e_shmsys, 4),				/* 171 */
#else
	sysg(e_nosys, 0),				/* 171 */
#endif
	sysg(e_nosys, 0),				/* 172 */
	sysg(e_nosys, 0),				/* 173 */
	sysg(e_nosys, 0),				/* 174 */
	sysg(e_nosys, 0),				/* 175 */
	sysg(e_nosys, 0),				/* 176 */
	sysg(e_nosys, 0),				/* 177 */
	sysg(e_nosys, 0),				/* 178 */
	sysg(e_nosys, 0),				/* 179 */
	sysg(e_nosys, 0),				/* 180 */
	sysg(e_setgid, 1),				/* 181 */
	sysg(e_setegid, 1),				/* 182 */
	sysg(e_seteuid, 1),				/* 183 */
	sysg(e_nosys, 0),				/* 184 */
	sysg(e_nosys, 0),				/* 185 */
	sysg(e_nosys, 0),				/* 186 */
	sysg(e_nosys, 0),				/* 187 */
	sysg(e_nosys, 0),				/* 188 */
	sysg(e_nosys, 0),				/* 189 */
	sysg(e_nosys, 0),				/* 190 */
	sysg(e_nosys, 0),				/* 191 */
	sysg(e_nosys, 0),				/* 192 */
	sysg(e_nosys, 0),				/* 193 */
	sysg(e_nosys, 0),				/* 194 */
	sysg(e_nosys, 0),				/* 195 */
	sysg(e_nosys, 0),				/* 196 */
	sysg(e_nosys, 0),				/* 197 */
	sysg(e_nosys, 0),				/* 198 */
	sysg(e_nosys, 0),				/* 199 */
	syss(e_table, 5),		/* 200 */
	sysg(e_sysctrace, 1),				/* 201 */
	syse(e___sysctl),			/* 202 */
};

int	nsysent = sizeof(sysent)/sizeof(struct sysent);

struct sysent   sysent_task_by_pid =
        syss(bsd_task_by_pid, 1);

struct sysent   sysent_pid_by_task =
        syss(bsd_pid_by_task, 4);

struct sysent   sysent_htg_ux_syscall =
        sysr(e_htg_syscall);

struct sysent   sysent_init_process =
        syss(bsd_init_process, 1);

