#!/usr/bin/env python3
"""
Generate ODE-style configuration headers from conf/ files.

This script parses:
- conf/config.common
- conf/AT386/config.devices  
- conf/AT386/config.debug (if exists)

And generates the corresponding header files in i386/AT386/
"""

import os
import re
import sys
from pathlib import Path
from collections import defaultdict

# Base paths
SCRIPT_DIR = Path(__file__).parent.resolve()
MACH_KERNEL = SCRIPT_DIR.parent / "src" / "mach_kernel"
CONF_DIR = MACH_KERNEL / "conf"
OUTPUT_DIR = MACH_KERNEL / "i386" / "AT386"

# Track all options and devices
options = {}  # name -> value (1 or 0)
devices = defaultdict(int)  # name -> count
pseudo_devices = {}  # name -> count

def parse_config_file(filepath):
    """Parse a config file and extract options, devices, pseudo-devices."""
    if not filepath.exists():
        print(f"Warning: {filepath} not found, skipping")
        return
    
    print(f"Parsing {filepath}")
    
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            # Parse "options NAME" or "options !NAME"
            match = re.match(r'^options\s+(!?)(\w+)(?:\s+(.*))?$', line)
            if match:
                negated = match.group(1) == '!'
                name = match.group(2)
                value = match.group(3)
                
                if negated:
                    options[name] = 0
                elif value:
                    # options NAME VALUE
                    try:
                        options[name] = int(value)
                    except ValueError:
                        options[name] = 1
                else:
                    options[name] = 1
                continue
            
            # Parse "device NAME" (e.g., "device hd0", "device com0")
            match = re.match(r'^device\s+(\w+?)(\d*)$', line)
            if match:
                name = match.group(1)
                devices[name] += 1
                continue
            
            # Parse "pseudo-device NAME [COUNT]"
            match = re.match(r'^pseudo-device\s+"?(\w+)"?\s*(\d*)$', line)
            if match:
                name = match.group(1)
                count = match.group(2)
                if count:
                    pseudo_devices[name] = int(count)
                else:
                    pseudo_devices[name] = 1
                continue
            
            # Parse "ident NAME"
            match = re.match(r'^ident\s+(\w+)$', line)
            if match:
                options[match.group(1)] = 1
                continue

def generate_header(name, value, prefix="N"):
    """Generate a header file for a configuration option."""
    header_name = name.lower() + ".h"
    header_path = OUTPUT_DIR / header_name
    
    # Skip if we already have a manually maintained header with complex content
    if header_path.exists():
        with open(header_path, 'r') as f:
            content = f.read()
            # If it has more than just the define, skip it
            if content.count('#define') > 2 or 'extern' in content or 'struct' in content:
                print(f"  Skipping {header_name} (manually maintained)")
                return
    
    # Determine the macro name
    macro_name = f"{prefix}{name.upper()}"
    
    # Special cases
    if name.upper() in ['MACH_KERNEL', 'MACH_PAGEMAP', 'MACH_LOAD', 'ADVISORY_PAGEOUT',
                         'TASK_SWAPPER', 'THREAD_SWAPPER', 'HIMEM', 'EISA', 'VTOC_COMPAT',
                         'CHAINED_IOS', 'MACH_RT', 'MACH', 'GPROF', 'ETAP']:
        macro_name = name.upper()
    
    content = f"""/*
 * ODE-style configuration header for {name.upper()}
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_{name.upper()}_H_
#define _I386_AT386_{name.upper()}_H_

#define {macro_name} {value}

#endif /* _I386_AT386_{name.upper()}_H_ */
"""
    
    with open(header_path, 'w') as f:
        f.write(content)
    print(f"  Generated {header_name} with {macro_name}={value}")

def main():
    print("=" * 60)
    print("ODE Configuration Header Generator")
    print("=" * 60)
    
    # Parse configuration files
    parse_config_file(CONF_DIR / "config.common")
    parse_config_file(CONF_DIR / "AT386" / "config.devices")
    parse_config_file(CONF_DIR / "AT386" / "config.debug")
    
    print()
    print("Collected configuration:")
    print(f"  Options: {len(options)}")
    print(f"  Devices: {len(devices)}")  
    print(f"  Pseudo-devices: {len(pseudo_devices)}")
    print()
    
    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    print("Generating headers...")
    
    # Generate headers for options (without N prefix)
    for name, value in options.items():
        generate_header(name, value, prefix="")
    
    # Generate headers for devices (with N prefix, value is count)
    for name, count in devices.items():
        generate_header(name, count, prefix="N")
    
    # Generate headers for pseudo-devices (with N prefix)
    for name, count in pseudo_devices.items():
        generate_header(name, count, prefix="N")
    
    # Generate additional common headers that may be needed
    additional_headers = {
        # Device drivers that might be referenced but not in config
        'qd': 0,
        'tu': 0,
        'fta': 0,
        'par': 0,
        'lpr': 0,
        'blit': 0,
        'wt': 0,
        'kkt': 0,
        'sce': 0,
        'cdli': 0,
        'flipc': 0,
        'evc': 0,
        'pc586': 1,
        'at3c501': 0,  # Disabled, NE uses its own driver
    }
    
    print()
    print("Generating additional headers for commonly referenced devices...")
    for name, value in additional_headers.items():
        if name.lower() not in [n.lower() for n in pseudo_devices.keys()]:
            if name.lower() not in [n.lower() for n in devices.keys()]:
                if name.upper() not in options:
                    generate_header(name, value, prefix="N")
    
    print()
    print("Done!")
    print("=" * 60)

if __name__ == "__main__":
    main()
