/* 
 * ../libjacket/e___sysctl.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e___sysctl(int *name, unsigned int namelen, void *old, size_t *oldlenp, void *new, size_t newlen, int *retlen)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*retlen = __sysctl(name, namelen, old, oldlenp, new, newlen);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

