/* 
 * ../libjacket/e_chown.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_chown(const char *path, uid_t owner, gid_t group)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	chown(path, owner, group);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

