/* 
 * ../libjacket/e_dup2.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_dup2(int ofd, int nfd)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	dup2(ofd, nfd);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

