/* 
 * ../libjacket/e_execve.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_execve(const char *path, const char *argv[], const char *envp[])
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	execve(path, argv, envp);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

