/* 
 * ../libjacket/e_fcntl.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_fcntl(int fd, int cmd, int arg, int *whatever)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*whatever = fcntl(fd, cmd, arg);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

