/* 
 * ../libjacket/e_fstatfs.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_fstatfs(int fd, struct statfs *buf)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	fstatfs(fd, buf);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

