/* 
 * ../libjacket/e_ftruncate.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_ftruncate(int fd, off_t length)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	ftruncate(fd, length);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

