/* 
 * ../libjacket/e_getgroups.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_getgroups(u_int gidsetsize, int *gidset, int *ngroups)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*ngroups = getgroups(gidsetsize, gidset);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

