/* 
 * ../libjacket/e_getdirentries.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_getdirentries(int fd, char *buf, int nbytes, long *basep, int *nread)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nread = getdirentries(fd, buf, nbytes, basep);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

