/* 
 * ../libjacket/e_getdtablesize.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_getdtablesize(int *size)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*size = getdtablesize();
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

