/* 
 * ../libjacket/e_getsockopt.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_getsockopt(int fd, int level, int optname, void *optval, int *optlen)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	getsockopt(fd, level, optname, optval, optlen);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

