/* 
 * ../libjacket/e_getsockname.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_getsockname(int s, struct sockaddr *name, int *namelen)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	getsockname(s, name, namelen);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

