/* 
 * ../libjacket/e_lseek.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_lseek(int fd, off_t offset, int sbase, off_t *pos)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*pos = lseek(fd, offset, sbase);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

