/* 
 * ../libjacket/e_mknod.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_mknod(const char *path, mode_t mode, dev_t dev)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	mknod(path, mode, dev);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

