/* 
 * ../libjacket/e_mount.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_mount(int type, const char *dir, int flags, void * data)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	mount(type, dir, flags, data);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

