/* 
 * ../libjacket/e_mprotect.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_mprotect(caddr_t addr, int len, int prot)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	mprotect(addr, len, prot);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

