/* 
 * ../libjacket/e_nfssvc.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_nfssvc(int sock, struct sockaddr *mask, int mask_length, struct sockaddr *match, int match_length)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	nfssvc(sock, mask, mask_length, match, match_length);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

