/* 
 * ../libjacket/e_pipe.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_pipe(int fds[2])
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	pipe(fds);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

