/* 
 * ../libjacket/e_ptrace.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_ptrace(int request, pid_t pid, int *addr, int data)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	ptrace(request, pid, addr, data);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

