/* 
 * ../libjacket/e_quotactl.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_quotactl(const char *path, int cmd, int id, char *addr)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	quotactl(path, cmd, id, addr);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

