/* 
 * ../libjacket/e_quota.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_quota(int a1, int a2, int a3, int a4, int *retval)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*retval = quota(a1, a2, a3, a4);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

