/* 
 * ../libjacket/e_readv.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_readv(int fd, struct iovec *iov, int iovcnt, int *nread)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nread = readv(fd, iov, iovcnt);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

