/* 
 * ../libjacket/e_recvfrom.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_recvfrom(int s, void *buf, int len, int flags, struct sockaddr *from, int *fromlen, int *nreceived)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nreceived = recvfrom(s, buf, len, flags, from, fromlen);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

