/* 
 * ../libjacket/e_reboot.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_reboot(int howto)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	reboot(howto);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

