/* 
 * ../libjacket/e_read.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_read(int fd, void *buf, size_t nbytes, size_t *nread)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nread = read(fd, buf, nbytes);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

