/* 
 * ../libjacket/e_readlink.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_readlink(const char *path, char *buf, int bufsize, int *nread)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nread = readlink(path, buf, bufsize);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

