/* 
 * ../libjacket/e_saccess.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_saccess(const char *path, int amode)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	access(path, amode);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

