/* 
 * ../libjacket/e_sbrk.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_sbrk(int incr, caddr_t *obrk)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*obrk = sbrk(incr);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

