/* 
 * ../libjacket/e_setitimer.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_setitimer(int which, struct itimerval *value, struct itimerval *ovalue)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	setitimer(which, value, ovalue);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

