/* 
 * ../libjacket/e_sendto.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_sendto(int s, const void *msg, int len, int flags, const struct sockaddr *to, int tolen, int *nsent)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nsent = sendto(s, msg, len, flags, to, tolen);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

