/* 
 * ../libjacket/e_send.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_send(int s, char *msg, int len, int flags, int *nsent)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nsent = send(s, msg, len, flags);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

