/* 
 * ../libjacket/e_select.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout, int *nready)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*nready = select(nfds, readfds, writefds, exceptfds, timeout);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

