/* 
 * ../libjacket/e_socket.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_socket(int domain, int type, int protocol, int *fd)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*fd = socket(domain, type, protocol);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

