/* 
 * ../libjacket/e_statfs.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_statfs(const char *path, struct statfs *buf)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	statfs(path, buf);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

