/* 
 * ../libjacket/e_table.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libjacket.h>

errno_t e_table(int id, int index, char *addr, int nel, u_int lel, int *cel)
{
	errno_t err, tmp;

	errno_jacket_lock();
	tmp = errno;
	errno = 0;
	*cel = table(id, index, addr, nel, lel);
	err = errno;
	errno = tmp;
	errno_jacket_unlock();

	return err;
}

