/*
 * libposix-uros — Mach exception ports → POSIX hw signals (#253 /
 * Phase 4b).
 *
 * The kernel posts EXC_BAD_ACCESS / EXC_BAD_INSTRUCTION /
 * EXC_ARITHMETIC / EXC_BREAKPOINT messages to whatever port we
 * install via task_set_exception_ports.  Without one, the kernel
 * falls back to the host default exception port — which on Uros
 * means the task is killed by the kernel and you get no useful
 * diagnostic.  Worse, in the wrong moment, the kernel can panic.
 *
 * This module installs a dedicated exception port owned by the task
 * itself, spins a Mach thread that drains incoming mach_msg into the
 * MIG-generated `exc_server` demux, and turns every hw trap into a
 * one-line console diagnostic followed by a clean task_terminate.
 *
 * Phase 4b is deliberately strict — "log and die".  Doing user-handler
 * dispatch on hw signals (sa_sigaction with siginfo_t, sigreturn,
 * thread-state munging to retry the faulting instruction) requires
 * machinery POSIX gets from sigreturn(3) and we don't want to land
 * here without a real testing story.  Phase 4c can take that on.
 *
 * Author: Alessandro Sangiuliano (Slex) <alex22_7@hotmail.com>
 * License: MIT
 */

#include <stdio.h>
#include <stdint.h>

#include <mach.h>
#include <mach/mach_port.h>
#include <mach/message.h>
#include <mach/mach_traps.h>
#include <mach/mach_interface.h>
#include <mach/exception.h>
#include <mach/thread_status.h>
#include <mach/mach_host.h>             /* task_set_exception_ports */

#include "uros/libposix.h"

/* sig_thread_entry.S */
extern void __uros_exc_thread_entry(void);

/* From signals.c — reused so the exception thread can stop printing in
 * the middle of a SIG_DFL terminate path.  Not currently used here but
 * kept handy. */
extern unsigned int __uros_my_pid;

#define UROS_EXC_STACK_SIZE  (16 * 1024)

mach_port_t  __uros_exc_port = MACH_PORT_NULL;

/* ------------------------------------------------------------------ */
/* MIG demux entry point and its stubs                                 */
/* ------------------------------------------------------------------ */

/* Generated by exc.defs MIG — links exc_server() into libmach_core. */
extern boolean_t exc_server(mach_msg_header_t *in, mach_msg_header_t *out);

/*
 * Map a Mach exception (with its code array) to the POSIX signal a
 * Linux kernel would have raised for the same condition.  Used only
 * for the diagnostic — Phase 4b terminates regardless of mapping.
 */
static const char *
exc_to_name(int exc, const int *code, int codeCnt, int *out_signo)
{
    (void)code; (void)codeCnt;
    switch (exc) {
    case EXC_BAD_ACCESS:      *out_signo = 11; return "SIGSEGV";
    case EXC_BAD_INSTRUCTION: *out_signo =  4; return "SIGILL";
    case EXC_ARITHMETIC:      *out_signo =  8; return "SIGFPE";
    case EXC_EMULATION:       *out_signo =  4; return "SIGILL";
    case EXC_SOFTWARE:        *out_signo =  6; return "SIGABRT";
    case EXC_BREAKPOINT:      *out_signo =  5; return "SIGTRAP";
    case EXC_SYSCALL:
    case EXC_MACH_SYSCALL:    *out_signo =  6; return "SIGSYS";
    case EXC_RPC_ALERT:       *out_signo = 14; return "SIGALRM";
    default:                  *out_signo = 11; return "SIG?";
    }
}

kern_return_t
catch_exception_raise(mach_port_t exception_port,
                      mach_port_t thread,
                      mach_port_t task,
                      exception_type_t exception,
                      exception_data_t code,
                      mach_msg_type_number_t codeCnt)
{
    (void)exception_port;

    int signo = 0;
    const char *name = exc_to_name((int)exception, (const int *)code,
                                   (int)codeCnt, &signo);

    /* The subcode (typically code[1]) is the faulting address for
     * EXC_BAD_ACCESS; for EXC_ARITHMETIC it's the operand or 0.  Keep
     * the format compact — one line is enough to diagnose. */
    unsigned long subcode = codeCnt >= 2 ? (unsigned long)code[1] : 0;
    int           sub0    = codeCnt >= 1 ? (int)code[0] : 0;

    printf("(libposix-uros): hw exception %d (%s) thread=0x%x "
           "code=%d subcode=0x%lx — task terminating\n",
           (int)exception, name, (unsigned)thread, sub0, subcode);

    (void)signo;     /* reserved for Phase 4c user handler dispatch */
    (void)task_terminate(task);
    return KERN_SUCCESS;
}

/*
 * We installed the port with EXCEPTION_DEFAULT behavior, so the kernel
 * always sends exception_raise (msgid 2401).  The other two demux
 * callbacks must still exist for the linker to resolve exc_server(),
 * but they're never reached at runtime.  Return KERN_FAILURE so a
 * misconfigured port falls back to the default kernel handling.
 */
kern_return_t
catch_exception_raise_state(mach_port_t exception_port,
                            exception_type_t exception,
                            exception_data_t code,
                            mach_msg_type_number_t codeCnt,
                            int *flavor,
                            thread_state_t old_state,
                            mach_msg_type_number_t old_stateCnt,
                            thread_state_t new_state,
                            mach_msg_type_number_t *new_stateCnt)
{
    (void)exception_port; (void)exception; (void)code; (void)codeCnt;
    (void)flavor; (void)old_state; (void)old_stateCnt;
    (void)new_state; (void)new_stateCnt;
    return KERN_FAILURE;
}

kern_return_t
catch_exception_raise_state_identity(mach_port_t exception_port,
                                     mach_port_t thread,
                                     mach_port_t task,
                                     exception_type_t exception,
                                     exception_data_t code,
                                     mach_msg_type_number_t codeCnt,
                                     int *flavor,
                                     thread_state_t old_state,
                                     mach_msg_type_number_t old_stateCnt,
                                     thread_state_t new_state,
                                     mach_msg_type_number_t *new_stateCnt)
{
    (void)exception_port; (void)thread; (void)task;
    (void)exception; (void)code; (void)codeCnt;
    (void)flavor; (void)old_state; (void)old_stateCnt;
    (void)new_state; (void)new_stateCnt;
    return KERN_FAILURE;
}

/* ------------------------------------------------------------------ */
/* Exception thread main loop                                          */
/* ------------------------------------------------------------------ */

void
__uros_exc_loop(void)
{
    /* Generous buffers — exc.defs sends small messages but we leave
     * room for trailers and future state-bearing variants. */
    char in_buf[2048];
    char out_buf[2048];

    for (;;) {
        mach_msg_header_t *in  = (mach_msg_header_t *)in_buf;
        mach_msg_header_t *out = (mach_msg_header_t *)out_buf;

        kern_return_t kr = mach_msg(in,
                                    MACH_RCV_MSG,
                                    0,
                                    sizeof(in_buf),
                                    __uros_exc_port,
                                    MACH_MSG_TIMEOUT_NONE,
                                    MACH_PORT_NULL);
        if (kr != KERN_SUCCESS)
            continue;

        boolean_t handled = exc_server(in, out);
        if (!handled)
            continue;

        /* Send the demux's reply (carries the kern_return_t from our
         * catch_exception_raise back to the kernel's exception path). */
        (void)mach_msg(out,
                       MACH_SEND_MSG,
                       out->msgh_size,
                       0,
                       MACH_PORT_NULL,
                       MACH_MSG_TIMEOUT_NONE,
                       MACH_PORT_NULL);
    }
}

/* ------------------------------------------------------------------ */
/* Init                                                                */
/* ------------------------------------------------------------------ */

void
__uros_exceptions_init(void)
{
    kern_return_t kr;

    /* 1. Allocate the receive right the kernel will mach_msg into. */
    kr = mach_port_allocate(mach_task_self(),
                            MACH_PORT_RIGHT_RECEIVE, &__uros_exc_port);
    if (kr != KERN_SUCCESS)
        return;
    (void)mach_port_insert_right(mach_task_self(),
                                 __uros_exc_port, __uros_exc_port,
                                 MACH_MSG_TYPE_MAKE_SEND);

    /* 2. Install it as the all-purpose exception handler for the
     * task.  EXCEPTION_DEFAULT → kernel sends exception_raise (msgid
     * 2401) with thread + task identity; we don't need the state-
     * bearing variants until Phase 4c. */
    kr = task_set_exception_ports(mach_task_self(),
                                  EXC_MASK_ALL,
                                  __uros_exc_port,
                                  EXCEPTION_DEFAULT,
                                  i386_THREAD_STATE);
    if (kr != KERN_SUCCESS) {
        (void)mach_port_destroy(mach_task_self(), __uros_exc_port);
        __uros_exc_port = MACH_PORT_NULL;
        return;
    }

    /* 3. Spawn the exception thread.  Same recipe as the signal
     * thread (signals.c spawn_handler_thread) but a different entry. */
    vm_address_t stack = 0;
    kr = vm_allocate(mach_task_self(), &stack, UROS_EXC_STACK_SIZE, TRUE);
    if (kr != KERN_SUCCESS)
        return;

    extern void __uros_sig_thread_die(void);
    uint32_t *sp = (uint32_t *)(stack + UROS_EXC_STACK_SIZE);
    sp -= 4;                                            /* alignment slack */
    *--sp = (uint32_t)__uros_sig_thread_die;            /* fake return */

    struct i386_thread_state state;
    for (size_t i = 0; i < sizeof state / sizeof(int); i++)
        ((int *)&state)[i] = 0;
    state.eip = (int)__uros_exc_thread_entry;
    state.uesp = (int)sp;
    state.cs   = 0x17;
    state.ds = state.es = state.ss = state.fs = state.gs = 0x1f;
    state.efl  = 0x202;

    thread_act_t thread;
    (void)thread_create_running(mach_task_self(),
                                i386_THREAD_STATE,
                                (thread_state_t)&state,
                                i386_THREAD_STATE_COUNT,
                                &thread);
}
