SRCDIR	= /home/slex/Uros/hello
OBJDIR = /home/slex/Uros/hello-build
#GLBINCDIR = /home/slex/xmach-installation/include

GSRCDIR	= /home/slex/Uros/hello-build/../kernel/generic
MSRCDIR = ../kernel

prefix = /home/slex/xmach-installation
exec_prefix = ${prefix}

include $(OBJDIR)/conf/Makeconf

include $(MSRCDIR)/Makerules
include $(GSRCDIR)/Makerules
include $(SRCDIR)/Makerules
