/*
 * ODE-style configuration header for ADSL
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_ADSL_H_
#define _I386_AT386_ADSL_H_

#define NADSL 0

#endif /* _I386_AT386_ADSL_H_ */
