/*
 * ODE-style configuration header for ADVISORY_PAGEOUT
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_ADVISORY_PAGEOUT_H_
#define _I386_AT386_ADVISORY_PAGEOUT_H_

#define ADVISORY_PAGEOUT 1

#endif /* _I386_AT386_ADVISORY_PAGEOUT_H_ */
