/*
 * ODE-style configuration header for AT3C501
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_AT3C501_H_
#define _I386_AT386_AT3C501_H_

#define NAT3C501 1

#endif /* _I386_AT386_AT3C501_H_ */
