/*
 * ODE-style configuration header for BLIT
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_BLIT_H_
#define _I386_AT386_BLIT_H_

#define NBLIT 0

#endif /* _I386_AT386_BLIT_H_ */
