/*
 * ODE-style configuration header for BOOTSTRAP_SYMBOLS
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_BOOTSTRAP_SYMBOLS_H_
#define _I386_AT386_BOOTSTRAP_SYMBOLS_H_

#define BOOTSTRAP_SYMBOLS 1

#endif /* _I386_AT386_BOOTSTRAP_SYMBOLS_H_ */
