/*
 * ODE-style configuration header for CDLI
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_CDLI_H_
#define _I386_AT386_CDLI_H_

#define NCDLI 0

#endif /* _I386_AT386_CDLI_H_ */
