/*
 * ODE-style configuration header for CDLI8390
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_CDLI8390_H_
#define _I386_AT386_CDLI8390_H_

#define NCDLI8390 1

#endif /* _I386_AT386_CDLI8390_H_ */
