/*
 * ODE-style configuration header for CHAINED_IOS
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_CHAINED_IOS_H_
#define _I386_AT386_CHAINED_IOS_H_

#define CHAINED_IOS 1

#endif /* _I386_AT386_CHAINED_IOS_H_ */
