/*
 * ODE-style configuration header for CYCTM
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_CYCTM_H_
#define _I386_AT386_CYCTM_H_

#define NCYCTM 0

#endif /* _I386_AT386_CYCTM_H_ */
