/*
 * ODE-style configuration header for EAHA
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_EAHA_H_
#define _I386_AT386_EAHA_H_

#define NEAHA 2

#endif /* _I386_AT386_EAHA_H_ */
