/*
 * ODE-style configuration header for FLIPC
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_FLIPC_H_
#define _I386_AT386_FLIPC_H_

#define NFLIPC 0

#endif /* _I386_AT386_FLIPC_H_ */
