/*
 * ODE-style configuration header for MACH_LOAD
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_LOAD_H_
#define _I386_AT386_MACH_LOAD_H_

#define MACH_LOAD 1

#endif /* _I386_AT386_MACH_LOAD_H_ */
