/*
 * ODE-style configuration header for MACH_PAGEMAP
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_PAGEMAP_H_
#define _I386_AT386_MACH_PAGEMAP_H_

#define MACH_PAGEMAP 1

#endif /* _I386_AT386_MACH_PAGEMAP_H_ */
