/*
 * ODE-style configuration header for MACH_TR
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_TR_H_
#define _I386_AT386_MACH_TR_H_

#define MACH_TR 1

#endif /* _I386_AT386_MACH_TR_H_ */
