/*
 * ODE-style configuration header for MACH_KERNEL
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_KERNEL_H_
#define _I386_AT386_MACH_KERNEL_H_

#define MACH_KERNEL 1

#endif /* _I386_AT386_MACH_KERNEL_H_ */
