/*
 * ODE-style configuration header for MACH
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_H_
#define _I386_AT386_MACH_H_

#define MACH 1

#endif /* _I386_AT386_MACH_H_ */
