/*
 * ODE-style configuration header for MACH_RT
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_MACH_RT_H_
#define _I386_AT386_MACH_RT_H_

#define MACH_RT 0

#endif /* _I386_AT386_MACH_RT_H_ */
