/*
 * ODE-style configuration header for NS8390
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_NS8390_H_
#define _I386_AT386_NS8390_H_

#define NNS8390 2

#endif /* _I386_AT386_NS8390_H_ */
