/*
 * ODE-style configuration header for PC586
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_PC586_H_
#define _I386_AT386_PC586_H_

#define NPC586 1

#endif /* _I386_AT386_PC586_H_ */
