/*
 * ODE-style configuration header for PHYSMEM
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_PHYSMEM_H_
#define _I386_AT386_PHYSMEM_H_

#define NPHYSMEM 1

#endif /* _I386_AT386_PHYSMEM_H_ */
