/*
 * platforms.h - Platform configuration for Mach kernel build
 *
 * This file is generated by the CMake build system.
 * Target: AT386 (Standard PC/AT compatible x86)
 */

#ifndef _PLATFORMS_H_
#define _PLATFORMS_H_

/*
 * Platform selection - only one should be defined
 * 
 * Supported platforms for i386:
 *   AT386     - Standard PC/AT compatible (ISA/EISA/PCI)
 *   SYMMETRY  - Sequent Symmetry multiprocessor
 *   SQT       - Sequent (alternative)
 *   iPSC386   - Intel iPSC hypercube node
 *   CBUS      - Corollary C-bus multiprocessor
 *   MBUS      - MicroChannel bus system
 */

#define AT386 1

/* Define i386 as the machine type */
#define i386 1

#endif /* _PLATFORMS_H_ */
