/*
 * ODE-style configuration header for SCSI
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_SCSI_H_
#define _I386_AT386_SCSI_H_

#define NSCSI 2

#endif /* _I386_AT386_SCSI_H_ */
