/*
 * ODE-style configuration header for TASK_SWAPPER
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_TASK_SWAPPER_H_
#define _I386_AT386_TASK_SWAPPER_H_

#define TASK_SWAPPER 1

#endif /* _I386_AT386_TASK_SWAPPER_H_ */
