/*
 * ODE-style configuration header for TEST_DEVICE
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_TEST_DEVICE_H_
#define _I386_AT386_TEST_DEVICE_H_

#define NTEST_DEVICE 1

#endif /* _I386_AT386_TEST_DEVICE_H_ */
