/*
 * ODE-style configuration header for THREAD_SWAPPER
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_THREAD_SWAPPER_H_
#define _I386_AT386_THREAD_SWAPPER_H_

#define THREAD_SWAPPER 1

#endif /* _I386_AT386_THREAD_SWAPPER_H_ */
