/*
 * ODE-style configuration header for VTOC_COMPAT
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_VTOC_COMPAT_H_
#define _I386_AT386_VTOC_COMPAT_H_

#define VTOC_COMPAT 1

#endif /* _I386_AT386_VTOC_COMPAT_H_ */
