/* 
 * ../libsys/__sysctl.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int __sysctl(int *name, unsigned int namelen, void *old, size_t *oldlenp, void *new, size_t newlen)
{
	int retlen = 0;
	errno_t err;

	err = e___sysctl(name, namelen, old, oldlenp, new, newlen, &retlen);
	if (err != 0) {
		retlen = -1;
		errno = err;
	}
	return retlen;
}

