/* 
 * ../libsys/accept.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int accept(int s, struct sockaddr *addr, int *addrlen)
{
	int fd = 0;
	errno_t err;

	err = e_accept(s, addr, addrlen, &fd);
	if (err != 0) {
		fd = -1;
		errno = err;
	}
	return fd;
}

