/* 
 * ../libsys/chroot.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int chroot(const char *dirname)
{
	errno_t err;

	err = e_chroot(dirname);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

