/* 
 * ../libsys/creat.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int creat(char *name, mode_t mode)
{
	int fd = 0;
	errno_t err;

	err = e_creat(name, mode, &fd);
	if (err != 0) {
		fd = -1;
		errno = err;
	}
	return fd;
}

