/* 
 * ../libsys/dup.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int dup(int fd)
{
	int nfd = 0;
	errno_t err;

	err = e_dup(fd, &nfd);
	if (err != 0) {
		nfd = -1;
		errno = err;
	}
	return nfd;
}

