/* 
 * ../libsys/dup2.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int dup2(int ofd, int nfd)
{
	errno_t err;

	err = e_dup2(ofd, nfd);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

