/* 
 * ../libsys/execve.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int execve(const char *path, const char *argv[], const char *envp[])
{
	errno_t err;

	err = e_execve(path, argv, envp);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

