/* 
 * ../libsys/fcntl.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int fcntl(int fd, int cmd, int arg)
{
	int whatever = 0;
	errno_t err;

	err = e_fcntl(fd, cmd, arg, &whatever);
	if (err != 0) {
		whatever = -1;
		errno = err;
	}
	return whatever;
}

