/* 
 * ../libsys/ftruncate.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int ftruncate(int fd, off_t length)
{
	errno_t err;

	err = e_ftruncate(fd, length);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

