/* 
 * ../libsys/getdirentries.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int getdirentries(int fd, char *buf, int nbytes, long *basep)
{
	int nread = 0;
	errno_t err;

	err = e_getdirentries(fd, buf, nbytes, basep, &nread);
	if (err != 0) {
		nread = -1;
		errno = err;
	}
	return nread;
}

