/* 
 * ../libsys/getdtablesize.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int getdtablesize()
{
	int size = 0;
	errno_t err;

	err = e_getdtablesize(&size);
	if (err != 0) {
		size = -1;
		errno = err;
	}
	return size;
}

