/* 
 * ../libsys/getgid.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

gid_t getgid()
{
	gid_t gid = 0;
	errno_t err;

	err = e_getgid(&gid);
	if (err != 0) {
		gid = -1;
		errno = err;
	}
	return gid;
}

