/* 
 * ../libsys/gethostid.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int gethostid()
{
	int id = 0;
	errno_t err;

	err = e_gethostid(&id);
	if (err != 0) {
		id = -1;
		errno = err;
	}
	return id;
}

