/* 
 * ../libsys/getpgrp.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

pid_t getpgrp()
{
	pid_t pgrp = 0;
	errno_t err;

	err = e_getpgrp(&pgrp);
	if (err != 0) {
		pgrp = -1;
		errno = err;
	}
	return pgrp;
}

