/* 
 * ../libsys/getpriority.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int getpriority(int which, int who)
{
	int prio = 0;
	errno_t err;

	err = e_getpriority(which, who, &prio);
	if (err != 0) {
		prio = -1;
		errno = err;
	}
	return prio;
}

