/* 
 * ../libsys/getrusage.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int getrusage(int who, struct rusage *rusage)
{
	errno_t err;

	err = e_getrusage(who, rusage);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

