/* 
 * ../libsys/getsockopt.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int getsockopt(int fd, int level, int optname, void *optval, int *optlen)
{
	errno_t err;

	err = e_getsockopt(fd, level, optname, optval, optlen);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

