/* 
 * ../libsys/gettimeofday.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int gettimeofday(struct timeval *tp, struct timezone *tzp)
{
	errno_t err;

	err = e_gettimeofday(tp, tzp);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

