/* 
 * ../libsys/getuid.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

uid_t getuid()
{
	uid_t uid = 0;
	errno_t err;

	err = e_getuid(&uid);
	if (err != 0) {
		uid = -1;
		errno = err;
	}
	return uid;
}

