/* 
 * ../libsys/kill.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int kill(pid_t pid, int sig)
{
	errno_t err;

	err = e_kill(pid, sig);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

