/* 
 * ../libsys/lseek.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

off_t lseek(int fd, off_t offset, int sbase)
{
	off_t pos = 0;
	errno_t err;

	err = e_lseek(fd, offset, sbase, &pos);
	if (err != 0) {
		pos = -1;
		errno = err;
	}
	return pos;
}

