/* 
 * ../libsys/madvise.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int madvise(caddr_t addr, int len, int behav)
{
	errno_t err;

	err = e_madvise(addr, len, behav);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

