/* 
 * ../libsys/mincore.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int mincore(caddr_t addr, int len, char *vec)
{
	errno_t err;

	err = e_mincore(addr, len, vec);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

