/* 
 * ../libsys/mmap.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

caddr_t mmap(caddr_t addr, size_t len, int prot, int flags, int fd, off_t offset)
{
	caddr_t addr_out = 0;
	errno_t err;

	err = e_smmap(addr, len, prot, flags, fd, offset, &addr_out);
	if (err != 0) {
		addr_out = -1;
		errno = err;
	}
	return addr_out;
}

