/* 
 * ../libsys/mprotect.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int mprotect(caddr_t addr, int len, int prot)
{
	errno_t err;

	err = e_mprotect(addr, len, prot);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

