/* 
 * ../libsys/nfssvc.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int nfssvc(int sock, struct sockaddr *mask, int mask_length, struct sockaddr *match, int match_length)
{
	errno_t err;

	err = e_nfssvc(sock, mask, mask_length, match, match_length);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

