/* 
 * ../libsys/open.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int open(const char *path, int flags, int mode)
{
	int fd = 0;
	errno_t err;

	err = e_open(path, flags, mode, &fd);
	if (err != 0) {
		fd = -1;
		errno = err;
	}
	return fd;
}

