/* 
 * ../libsys/ptrace.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int ptrace(int request, pid_t pid, int *addr, int data)
{
	errno_t err;

	err = e_ptrace(request, pid, addr, data);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

