/* 
 * ../libsys/quota.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int quota(int a1, int a2, int a3, int a4)
{
	int retval = 0;
	errno_t err;

	err = e_quota(a1, a2, a3, a4, &retval);
	if (err != 0) {
		retval = -1;
		errno = err;
	}
	return retval;
}

