/* 
 * ../libsys/readlink.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int readlink(const char *path, char *buf, int bufsize)
{
	int nread = 0;
	errno_t err;

	err = e_readlink(path, buf, bufsize, &nread);
	if (err != 0) {
		nread = -1;
		errno = err;
	}
	return nread;
}

