/* 
 * ../libsys/readv.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int readv(int fd, struct iovec *iov, int iovcnt)
{
	int nread = 0;
	errno_t err;

	err = e_readv(fd, iov, iovcnt, &nread);
	if (err != 0) {
		nread = -1;
		errno = err;
	}
	return nread;
}

