/* 
 * ../libsys/read.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

size_t read(int fd, void *buf, size_t nbytes)
{
	size_t nread = 0;
	errno_t err;

	err = e_read(fd, buf, nbytes, &nread);
	if (err != 0) {
		nread = -1;
		errno = err;
	}
	return nread;
}

