/* 
 * ../libsys/recvfrom.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int recvfrom(int s, void *buf, int len, int flags, struct sockaddr *from, int *fromlen)
{
	int nreceived = 0;
	errno_t err;

	err = e_recvfrom(s, buf, len, flags, from, fromlen, &nreceived);
	if (err != 0) {
		nreceived = -1;
		errno = err;
	}
	return nreceived;
}

