/* 
 * ../libsys/recv.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int recv(int s, char *buf, int len, int flags)
{
	int nreceived = 0;
	errno_t err;

	err = e_recv(s, buf, len, flags, &nreceived);
	if (err != 0) {
		nreceived = -1;
		errno = err;
	}
	return nreceived;
}

