/* 
 * ../libsys/rmdir.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int rmdir(const char *path)
{
	errno_t err;

	err = e_rmdir(path);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

