/* 
 * ../libsys/sbrk.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

caddr_t sbrk(int incr)
{
	caddr_t obrk = 0;
	errno_t err;

	err = e_sbrk(incr, &obrk);
	if (err != 0) {
		obrk = -1;
		errno = err;
	}
	return obrk;
}

