/* 
 * ../libsys/select.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
{
	int nready = 0;
	errno_t err;

	err = e_select(nfds, readfds, writefds, exceptfds, timeout, &nready);
	if (err != 0) {
		nready = -1;
		errno = err;
	}
	return nready;
}

