/* 
 * ../libsys/sendmsg.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int sendmsg(int s, const struct msghdr *msg, int flags)
{
	int nsent = 0;
	errno_t err;

	err = e_sendmsg(s, msg, flags, &nsent);
	if (err != 0) {
		nsent = -1;
		errno = err;
	}
	return nsent;
}

