/* 
 * ../libsys/sendto.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int sendto(int s, const void *msg, int len, int flags, const struct sockaddr *to, int tolen)
{
	int nsent = 0;
	errno_t err;

	err = e_sendto(s, msg, len, flags, to, tolen, &nsent);
	if (err != 0) {
		nsent = -1;
		errno = err;
	}
	return nsent;
}

