/* 
 * ../libsys/seteuid.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int seteuid(uid_t euid)
{
	errno_t err;

	err = e_seteuid(euid);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

