/* 
 * ../libsys/setgroups.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int setgroups(int gidsetsize, gid_t *gidset)
{
	errno_t err;

	err = e_setgroups(gidsetsize, gidset);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

