/* 
 * ../libsys/setpgid.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int setpgid(pid_t pid, pid_t pgrp)
{
	errno_t err;

	err = e_setpgid(pid, pgrp);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

