/* 
 * ../libsys/shutdown.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int shutdown(int fd, int how)
{
	errno_t err;

	err = e_shutdown(fd, how);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

