/* 
 * ../libsys/sigpending.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int sigpending(sigset_t *set)
{
	errno_t err;

	err = e_sigpending(set);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

