/* 
 * ../libsys/sigreturn.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int sigreturn(struct sigcontext *scp)
{
	errno_t err;

	err = e_sigreturn(scp);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

