/* 
 * ../libsys/socketpair.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int socketpair(int domain, int type, int protocol, int *sv)
{
	errno_t err;

	err = e_socketpair(domain, type, protocol, sv);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

