/* 
 * ../libsys/statfs.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int statfs(const char *path, struct statfs *buf)
{
	errno_t err;

	err = e_statfs(path, buf);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

