/* 
 * ../libsys/stat.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int stat(const char *path, struct stat *buf)
{
	errno_t err;

	err = e_stat(path, buf);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

