/* 
 * ../libsys/swapon.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int swapon(const char *special)
{
	errno_t err;

	err = e_swapon(special);
	if (err != 0) {
		errno = err;
		return -1;
	}
	return 0;
}

