/* 
 * ../libsys/table.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int table(int id, int index, char *addr, int nel, u_int lel)
{
	int cel = 0;
	errno_t err;

	err = e_table(id, index, addr, nel, lel, &cel);
	if (err != 0) {
		cel = -1;
		errno = err;
	}
	return cel;
}

