/* 
 * ../libsys/vfork.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

pid_t vfork()
{
	pid_t pid = 0;
	errno_t err;

	err = e_vfork(&pid);
	if (err != 0) {
		pid = -1;
		errno = err;
	}
	return pid;
}

