/* 
 * ../libsys/wait.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int wait()
{
	int retval = 0;
	errno_t err;

	err = e_wait(&retval);
	if (err != 0) {
		retval = -1;
		errno = err;
	}
	return retval;
}

