/* 
 * ../libsys/wait4.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

pid_t wait4(pid_t pid, int *status, int options, struct rusage *rusage)
{
	pid_t wpid = 0;
	errno_t err;

	err = e_wait4(pid, status, options, rusage, &wpid);
	if (err != 0) {
		wpid = -1;
		errno = err;
	}
	return wpid;
}

