/* 
 * ../libsys/writev.c
 * DO NOT EDIT-- this file is automatically generated.
 * created from /home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <sys/libsys.h>

int writev(int fd, struct iovec *iov, int iovcnt)
{
	int nwritten = 0;
	errno_t err;

	err = e_writev(fd, iov, iovcnt, &nwritten);
	if (err != 0) {
		nwritten = -1;
		errno = err;
	}
	return nwritten;
}

