/*
 * ODE-style configuration header for CPUS
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_CPUS_H_
#define _I386_AT386_CPUS_H_

#define NCPUS 1

#endif /* _I386_AT386_CPUS_H_ */
