/*
 * cputypes.h - CPU types configuration (legacy)
 * Generated by CMake build system.
 */
#ifndef _CPUTYPES_H_
#define _CPUTYPES_H_
/* This is a legacy header - use platforms.h instead */
#include <platforms.h>
#endif
