/*
 * ODE-style configuration header for DATA_DEVICE
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_DATA_DEVICE_H_
#define _I386_AT386_DATA_DEVICE_H_

#define NDATA_DEVICE 1

#endif /* _I386_AT386_DATA_DEVICE_H_ */
