/*
 * ODE-style configuration header for ETAP_MAP
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_ETAP_MAP_H_
#define _I386_AT386_ETAP_MAP_H_

#define NETAP_MAP 1

#endif /* _I386_AT386_ETAP_MAP_H_ */
