/*
 * etap.h - ETAP (Event Trace Analysis Package) configuration
 * Generated by CMake build system.
 */
#ifndef _ETAP_H_
#define _ETAP_H_
#define ETAP 0
#define ETAP_LOCK_TRACE 0
#define ETAP_LOCK_ACCUMULATE 0
#define ETAP_EVENT_MONITOR 0
#endif
