/*
 * mach_machine_routines.h - Machine routines configuration
 * Generated by CMake build system.
 */
#ifndef _MACH_MACHINE_ROUTINES_CONF_H_
#define _MACH_MACHINE_ROUTINES_CONF_H_
#define MACH_MACHINE_ROUTINES 1
#endif
