/*
 * mach_ldebug.h - Lock debugging configuration
 *
 * Generated by CMake build system.
 */

#ifndef _MACH_LDEBUG_H_
#define _MACH_LDEBUG_H_

/*
 * MACH_LDEBUG - Enable lock debugging
 * 
 * 1 = Enable lock debugging (slower, more checks)
 * 0 = Disable lock debugging (faster)
 */
#define MACH_LDEBUG 0

/*
 * ETAP - Event Trace Analysis Package (profiling)
 */
#define ETAP 0
#define ETAP_LOCK_TRACE 0
#define ETAP_LOCK_ACCUMULATE 0
#define ETAP_EVENT_MONITOR 0

#endif /* _MACH_LDEBUG_H_ */
