/*
 * Machine Configuration Header for OSFMK Mach Kernel
 * Target: i386/AT386 (Standard PC/AT compatible)
 *
 * This file consolidates all configuration options that would normally
 * be generated by the Mach configuration system.
 * 
 * Generated by CMake build system.
 */

#ifndef _MACHINE_H_
#define _MACHINE_H_

/* Include individual config headers */
#include <platforms.h>
#include <cpus.h>
#include <mach_kdb.h>
#include <mach_ldebug.h>
#include <stat_time.h>

#endif /* _MACHINE_H_ */
