/*
 * ODE-style configuration header for NET_DEVICE
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_NET_DEVICE_H_
#define _I386_AT386_NET_DEVICE_H_

#define NNET_DEVICE 1

#endif /* _I386_AT386_NET_DEVICE_H_ */
