/*
 * ODE-style configuration header for SCSIINFO
 * Auto-generated by generate_ode_headers.py
 */
#ifndef _I386_AT386_SCSIINFO_H_
#define _I386_AT386_SCSIINFO_H_

#define NSCSIINFO 1

#endif /* _I386_AT386_SCSIINFO_H_ */
