/*
 * stat_time.h - Statistical timing configuration
 *
 * Generated by CMake build system.
 */

#ifndef _STAT_TIME_H_
#define _STAT_TIME_H_

/*
 * STAT_TIME - Use statistical timing for CPU usage accounting
 * 
 * 1 = Use statistical timer (tick-based)
 * 0 = Use high-resolution timer
 */
#define STAT_TIME 1

#endif /* _STAT_TIME_H_ */
