/*
 * Copyright (c) 2026 Alessandro Sangiuliano (Slex) <alex22_7@hotmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * ipc_bench.c — IPC Performance Benchmark for OSFMK
 *
 * Measures Mach IPC latency both intra-task (thread-to-thread) and
 * inter-task (task-to-task).  Inspired by the old OSF mach_perf/ipc
 * test suite but written as a self-contained standalone Mach server.
 *
 * Tests performed:
 *   1. Intra-task null RPC        (cthread echo, no payload)
 *   2. Intra-task inline RPC      (128 / 1024 / 4096 bytes)
 *   3. Inter-task null RPC        (child task echo, no payload)
 *   4. Inter-task inline RPC      (128 / 1024 / 4096 bytes)
 *   5. Port operations            (alloc+destroy, mach_port_names)
 *
 * Timing uses the Mach REALTIME_CLOCK via clock_get_time().
 */

#include <mach.h>
#include <mach/mach_host.h>
#include <mach/bootstrap.h>
#include <mach/mach_port.h>
#include <mach/mach_traps.h>
#include <mach/message.h>
#include <mach/clock.h>
#include <mach/clock_types.h>
#include <mach/thread_switch.h>
#include <mach/i386/thread_status.h>
#include <sa_mach.h>
#include <pthread.h>
#include <device/device.h>
#include <device/device_types.h>
#include "gpu_console.h"
#include <stdio.h>
#include <string.h>

#include "disk_bench.h"
#include "mem_bench.h"
#include "flipc2_bench.h"

/* MIG stub — generated from mach_port.defs */
extern kern_return_t mach_port_set_protected_payload(
	mach_port_t task, mach_port_t name, unsigned payload);

/* Raw syscall traps — generated by kernel_trap() in mach/syscall_sw.h */
extern kern_return_t	mach_null(void);
extern void		mach_print(const char *s);
extern mach_port_type_t	urmach_cap_probe(mach_port_t name); /* #331 step 2 (TEMP) */

/* ===================================================================
 * Configuration
 * =================================================================== */

#define WARMUP_ITERS		100
#define BENCH_ITERS		10000
#define CHILD_STACK_SIZE	(64 * 1024)	/* 64 KB */

/*
 * Well-known port names inserted into the child task's IPC space
 * for the inter-task benchmark.
 */
#define CHILD_RECV_NAME		((mach_port_t) 0x1503)
#define CHILD_SEND_NAME		((mach_port_t) 0x1603)

/* ===================================================================
 * Global ports
 * =================================================================== */

static mach_port_t	host_port;
static mach_port_t	device_port;
static mach_port_t	security_port;
static mach_port_t	root_ledger_wired;
static mach_port_t	root_ledger_paged;
static mach_port_t	clock_port;

/* ===================================================================
 * Message structures
 * =================================================================== */

/*
 * Null message — header only.
 */
typedef struct {
    mach_msg_header_t	head;
} bench_null_msg_t;

/*
 * Inline data messages for payload tests.
 */
typedef struct {
    mach_msg_header_t	head;
    char		data[128];
} bench_128_msg_t;

typedef struct {
    mach_msg_header_t	head;
    char		data[1024];
} bench_1024_msg_t;

typedef struct {
    mach_msg_header_t	head;
    char		data[4096];
} bench_4096_msg_t;

/*
 * Generic receive buffer — large enough for any message.
 */
typedef struct {
    mach_msg_header_t	head;
    char		data[4096 + 64];
} bench_recv_buf_t;

/* ===================================================================
 * kmsg cache statistics
 * =================================================================== */

typedef struct {
    unsigned int tries;
    unsigned int misses;
} cache_snap_t;

static int
cache_snap(cache_snap_t *s)
{
    host_ipc_cache_info_data_t	info;
    mach_msg_type_number_t		count = HOST_IPC_CACHE_INFO_COUNT;
    kern_return_t			kr;

    kr = host_info(host_port, HOST_IPC_CACHE_INFO,
		   (host_info_t)&info, &count);
    if (kr != KERN_SUCCESS)
	return 0;
    s->tries  = info.tries;
    s->misses = info.misses;
    return 1;
}

static void
print_cache_stats(const char *label,
		  const cache_snap_t *before, const cache_snap_t *after)
{
    unsigned int tries  = after->tries  - before->tries;
    unsigned int misses = after->misses - before->misses;
    unsigned int hits   = tries - misses;
    unsigned int pct    = tries ? (hits * 100) / tries : 0;

    printf("  [cache] %-30s tries=%-6u hits=%-6u misses=%-6u hit%%=%u%%\n",
	   label, tries, hits, misses, pct);
}

/* ===================================================================
 * Timing helpers
 * =================================================================== */

static void
get_time(tvalspec_t *tv)
{
    clock_get_time(clock_port, tv);
}

/*
 * Return elapsed nanoseconds between two tvalspec_t values.
 */
static unsigned long
elapsed_ns(const tvalspec_t *before, const tvalspec_t *after)
{
    unsigned long ns;
    ns  = (unsigned long)(after->tv_sec  - before->tv_sec)  * 1000000000UL;
    ns += (unsigned long)(after->tv_nsec - before->tv_nsec);
    return ns;
}

static void
print_result(const char *label, unsigned long total_ns, int iters)
{
    unsigned long ns_per_op = total_ns / (unsigned long)iters;
    unsigned long us_whole  = ns_per_op / 1000;
    unsigned long us_frac   = (ns_per_op % 1000) / 10;   /* 2 decimal digits */
    unsigned long total_us  = total_ns / 1000;

    printf("  %-34s %5lu.%02lu us/op  (%d iters, %lu us total)\n",
	   label, us_whole, us_frac, iters, total_us);
}

/* ===================================================================
 * SMP-correct echo-thread readiness handshake.
 *
 * The old code "synchronised" by calling thread_switch(YIELD/DEPRESS)
 * after pthread_create and assuming the echo thread had, by the time the
 * yield returned, started and blocked in mach_msg_receive.  That is a
 * uniprocessor assumption: on SMP the echo thread runs on another CPU
 * and the yield guarantees nothing.  Instead, the echo thread sends a
 * one-shot ping on a ready port as its very first action; spawn_echo()
 * blocks receiving it, so the benchmark loop only starts once the echo
 * thread is provably running.  Benches run sequentially, so a single
 * global ready port (live only across the handshake) suffices and lets
 * the four echo funcs keep their (void*)port argument unchanged.
 * =================================================================== */

static volatile mach_port_t g_echo_ready_port = MACH_PORT_NULL;

/* echo side: announce "I'm running" (call once at thread entry). */
static void
echo_signal_ready(void)
{
    mach_port_t		rp = g_echo_ready_port;
    mach_msg_header_t	m;

    if (rp == MACH_PORT_NULL)
	return;
    m.msgh_bits	       = MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
    m.msgh_size	       = sizeof(m);
    m.msgh_remote_port = rp;
    m.msgh_local_port  = MACH_PORT_NULL;
    m.msgh_id	       = 0;
    (void) mach_msg(&m, MACH_SEND_MSG, sizeof(m), 0,
		    MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
}

/* spawner side: create the echo thread and block until it is running.
 * Replaces "pthread_create + pthread_detach + thread_switch(yield)".
 * The 5 s timeout turns a libpthreads lost-wakeup (echo never scheduled)
 * into an explicit log line instead of a silent wedge — a clean signal
 * to distinguish a benchmark sync bug from a real threading bug. */
static void
spawn_echo(const char *label, void *(*fn)(void *), mach_port_t echo_port)
{
    pthread_t		th;
    mach_port_t		ready_port;
    /* Receive buffer must hold the header AND the trailer the kernel
     * appends, plus slack — receiving into a bare header overflows the
     * stack (the stack protector trips: "stack smashing detected"). */
    struct {
	mach_msg_header_t  head;
	mach_msg_trailer_t trailer;
	char		   pad[32];
    } m;
    kern_return_t	kr;

    if (mach_port_allocate(mach_task_self(),
			   MACH_PORT_RIGHT_RECEIVE, &ready_port)) {
	/* Fall back to the old best-effort yield if we can't make a port. */
	pthread_create(&th, NULL, fn, (void *)(unsigned long)echo_port);
	pthread_detach(th);
	thread_switch(MACH_PORT_NULL, SWITCH_OPTION_DEPRESS, 10);
	return;
    }
    mach_port_insert_right(mach_task_self(), ready_port, ready_port,
			   MACH_MSG_TYPE_MAKE_SEND);
    g_echo_ready_port = ready_port;

    pthread_create(&th, NULL, fn, (void *)(unsigned long)echo_port);
    pthread_detach(th);

    kr = mach_msg(&m.head, MACH_RCV_MSG | MACH_RCV_TIMEOUT, 0, sizeof(m),
		  ready_port, 5000, MACH_PORT_NULL);
    if (kr == MACH_RCV_TIMED_OUT)
	printf("  %s: echo thread failed to start in 5s "
	       "(libpthreads lost wakeup?)\n", label);

    g_echo_ready_port = MACH_PORT_NULL;
    mach_port_destroy(mach_task_self(), ready_port);
}

/* ===================================================================
 * Intra-task echo thread (cthread)
 *
 * Receives a message on `port`, sends a reply back on the
 * remote_port embedded in the message header.
 * =================================================================== */

static void *
echo_thread_func(void *arg)
{
    mach_port_t		port = (mach_port_t)(unsigned long)arg;
    bench_recv_buf_t	msg;
    bench_null_msg_t	reply;
    kern_return_t	kr;

    echo_signal_ready();

    for (;;) {
	kr = mach_msg(&msg.head,
		      MACH_RCV_MSG,
		      0,
		      sizeof(msg),
		      port,
		      MACH_MSG_TIMEOUT_NONE,
		      MACH_PORT_NULL);
	if (kr != MACH_MSG_SUCCESS) {
	    /*
	     * Terminal errors mean the bench destroyed the receive port
	     * — exit instead of spinning on mach_msg(RCV) forever and
	     * polluting the next test's scheduling.
	     */
	    if (kr == MACH_RCV_PORT_DIED ||
		kr == MACH_RCV_PORT_CHANGED ||
		kr == MACH_RCV_INVALID_NAME ||
		kr == MACH_RCV_TIMED_OUT)
		break;
	    continue;
	}

	/* Send a minimal reply */
	reply.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
	reply.head.msgh_size	    = sizeof(reply);
	reply.head.msgh_remote_port = msg.head.msgh_remote_port;
	reply.head.msgh_local_port  = MACH_PORT_NULL;
	reply.head.msgh_id	    = msg.head.msgh_id + 100;

	mach_msg(&reply.head,
		 MACH_SEND_MSG,
		 sizeof(reply),
		 0,
		 MACH_PORT_NULL,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);
    }

    return (void *)0;  /* not reached */
}

/* ===================================================================
 * Intra-task RPC benchmark
 *
 * Sends `iters` messages of `send_size` bytes to the echo cthread
 * and waits for the reply each time.
 * =================================================================== */

static void
bench_intra_rpc(const char *label, int send_size, int iters)
{
    cache_snap_t	cs_before, cs_after;
    mach_port_t		echo_port, reply_port;
    kern_return_t	kr;
    tvalspec_t		t0, t1;
    int			i;
    bench_recv_buf_t	send_buf;
    bench_null_msg_t	recv_buf;

    /* Create echo port and reply port */
    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &echo_port);
    if (kr) { printf("  %s: port alloc failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(mach_task_self(),
				echo_port, echo_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert right failed %d\n", label, kr); return; }

    reply_port = mach_reply_port();

    /* Spawn echo thread and wait until it is provably running (SMP-safe). */
    spawn_echo(label, echo_thread_func, echo_port);

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    /* Timed run */
    cache_snap(&cs_before);
    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);
    cache_snap(&cs_after);

    print_result(label, elapsed_ns(&t0, &t1), iters);
    //print_cache_stats(label, &cs_before, &cs_after);

    /* Cleanup: destroy ports (kills echo thread's receive) */
    mach_port_destroy(mach_task_self(), echo_port);
    mach_port_destroy(mach_task_self(), reply_port);
}

/* ===================================================================
 * Combined-trap (SEND|RCV) echo thread  [#320]
 *
 * MIG-server-style loop: the first iteration only receives; thereafter
 * each iteration SENDS the previous reply AND RECEIVES the next request
 * in a single mach_msg() trap.  The server therefore parks on TH_WAIT
 * between requests, so both peers take the mach_msg combined-message
 * hotpath (the L4-style hand-off) rather than the separate-call DTS path.
 * =================================================================== */

static void *
combined_echo_thread_func(void *arg)
{
    mach_port_t		port = (mach_port_t)(unsigned long)arg;
    bench_recv_buf_t	buf;
    kern_return_t	kr;
    mach_msg_option_t	opt	= MACH_RCV_MSG;	/* first time: receive only */
    mach_msg_size_t	send_sz = 0;

    echo_signal_ready();

    for (;;) {
	kr = mach_msg(&buf.head, opt, send_sz, sizeof(buf), port,
		      MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	if (kr != MACH_MSG_SUCCESS) {
	    if (kr == MACH_RCV_PORT_DIED  || kr == MACH_RCV_PORT_CHANGED ||
		kr == MACH_RCV_INVALID_NAME || kr == MACH_RCV_TIMED_OUT  ||
		kr == MACH_SEND_INVALID_DEST)
		break;
	    opt = MACH_RCV_MSG; send_sz = 0;	/* resync to a clean receive */
	    continue;
	}

	/*
	 * buf holds a request; buf.head.msgh_remote_port is the client's
	 * send-once reply right.  Turn the buffer into a null reply to it,
	 * then SEND it and RCV the next request in one trap.
	 */
	buf.head.msgh_bits	 = MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
	buf.head.msgh_local_port = MACH_PORT_NULL;
	buf.head.msgh_size	 = sizeof(bench_null_msg_t);
	buf.head.msgh_id	+= 100;
	opt	= MACH_SEND_MSG | MACH_RCV_MSG;
	send_sz = sizeof(bench_null_msg_t);
    }
    return (void *)0;
}

/* ===================================================================
 * Combined-trap intra-task RPC benchmark  [#320]
 *
 * The client issues one mach_msg(MACH_SEND_MSG|MACH_RCV_MSG) per round
 * trip (send the request to the echo port, receive the reply on its own
 * reply port) -- exactly what a MIG simpleroutine does.  This is the path
 * that exercises the SMP-safe hotpath (#315); bench_intra_rpc, by using
 * separate send/recv calls, does not.
 * =================================================================== */

static void
bench_combined_rpc(const char *label, int send_size, int iters)
{
    mach_port_t		echo_port, reply_port;
    kern_return_t	kr;
    tvalspec_t		t0, t1;
    int			i;
    bench_recv_buf_t	buf;	/* one buffer: send from it, receive into it */

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &echo_port);
    if (kr) { printf("  %s: port alloc failed %d\n", label, kr); return; }
    kr = mach_port_insert_right(mach_task_self(), echo_port, echo_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert right failed %d\n", label, kr); return; }
    reply_port = mach_reply_port();

    /* Spawn echo thread and wait until it is provably running (SMP-safe). */
    spawn_echo(label, combined_echo_thread_func, echo_port);

    for (i = 0; i < WARMUP_ITERS; i++) {
	buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	buf.head.msgh_size	  = send_size;
	buf.head.msgh_remote_port = echo_port;
	buf.head.msgh_local_port  = reply_port;
	buf.head.msgh_id	  = 1;
	mach_msg(&buf.head, MACH_SEND_MSG | MACH_RCV_MSG, send_size,
		 sizeof(buf), reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    get_time(&t0);
    for (i = 0; i < iters; i++) {
	buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	buf.head.msgh_size	  = send_size;
	buf.head.msgh_remote_port = echo_port;
	buf.head.msgh_local_port  = reply_port;
	buf.head.msgh_id	  = 1;
	mach_msg(&buf.head, MACH_SEND_MSG | MACH_RCV_MSG, send_size,
		 sizeof(buf), reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    mach_port_destroy(mach_task_self(), echo_port);
    mach_port_destroy(mach_task_self(), reply_port);
}

/* ===================================================================
 * Inter-task: child echo entry point
 *
 * This function runs in the CHILD task.  It must not call any
 * MIG routine (bootstrap_ports, clock_get_time, etc.) — only raw
 * mach_msg() which is a direct syscall wrapper.
 *
 * Port names CHILD_RECV_NAME and CHILD_SEND_NAME are inserted
 * into the child's IPC space by the parent before thread resume.
 * =================================================================== */

static void __attribute__((noreturn, used))
child_echo_entry(void)
{
    bench_recv_buf_t	msg;
    bench_null_msg_t	reply;

    for (;;) {
	mach_msg(&msg.head,
		 MACH_RCV_MSG,
		 0,
		 sizeof(msg),
		 CHILD_RECV_NAME,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);

	reply.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	reply.head.msgh_size	    = sizeof(reply);
	reply.head.msgh_remote_port = CHILD_SEND_NAME;
	reply.head.msgh_local_port  = MACH_PORT_NULL;
	reply.head.msgh_id	    = msg.head.msgh_id + 100;

	mach_msg(&reply.head,
		 MACH_SEND_MSG,
		 sizeof(reply),
		 0,
		 MACH_PORT_NULL,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);
    }
}

/* ===================================================================
 * Inter-task RPC benchmark
 *
 * Creates a child task via task_create(inherit_memory=TRUE),
 * inserts ports into the child's IPC space, creates a thread
 * in the child pointing at child_echo_entry(), and measures
 * round-trip IPC latency.
 * =================================================================== */

static void
bench_inter_rpc(const char *label, int send_size, int iters)
{
    cache_snap_t		cs_before, cs_after;
    kern_return_t		kr;
    mach_port_t			child_task, child_thread;
    mach_port_t			child_recv_port;	/* child receives */
    mach_port_t			parent_recv_port;	/* parent receives replies */
    vm_offset_t			child_stack;
    struct i386_thread_state	state;
    mach_msg_type_number_t	state_count;
    tvalspec_t			t0, t1;
    int				i;
    bench_recv_buf_t		send_buf;
    bench_null_msg_t		recv_buf;

    /*
     * Step 1: Allocate ports.
     * child_recv_port: parent will move the receive right to child.
     * parent_recv_port: parent keeps the receive right for replies.
     */
    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE,
			    &child_recv_port);
    if (kr) { printf("  %s: alloc child_recv failed %d\n", label, kr); return; }

    /* Create a send right for parent to keep */
    kr = mach_port_insert_right(mach_task_self(),
				child_recv_port, child_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert send right failed %d\n", label, kr); return; }

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE,
			    &parent_recv_port);
    if (kr) { printf("  %s: alloc parent_recv failed %d\n", label, kr); return; }

    /* Send right for parent_recv_port (will give to child) */
    kr = mach_port_insert_right(mach_task_self(),
				parent_recv_port, parent_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert parent send right failed %d\n", label, kr); return; }

    /*
     * Step 2: Create child task.
     * inherit_memory=TRUE: child gets a COW copy of our address space,
     * so child_echo_entry() code is available at the same address.
     */
    kr = task_create(mach_task_self(),
		     (ledger_port_array_t)0, 0,
		     TRUE,  /* inherit memory */
		     &child_task);
    if (kr) { printf("  %s: task_create failed %d\n", label, kr); return; }

    /*
     * Step 3: Allocate stack in the child task's address space.
     */
    child_stack = 0;
    kr = vm_allocate(child_task, &child_stack, CHILD_STACK_SIZE, TRUE);
    if (kr) { printf("  %s: child stack alloc failed %d\n", label, kr); return; }

    /*
     * Step 4: Insert port rights into child's IPC space.
     *
     * CHILD_RECV_NAME: receive right — child receives benchmark
     *                  messages on this port.
     * CHILD_SEND_NAME: send right — child sends replies to parent
     *                  on this port.
     */
    kr = mach_port_insert_right(child_task,
				CHILD_RECV_NAME,
				child_recv_port,
				MACH_MSG_TYPE_MOVE_RECEIVE);
    if (kr) { printf("  %s: insert child recv failed %d\n", label, kr); return; }
    /* Parent lost the receive right; still has send right */

    kr = mach_port_insert_right(child_task,
				CHILD_SEND_NAME,
				parent_recv_port,
				MACH_MSG_TYPE_COPY_SEND);
    if (kr) { printf("  %s: insert child send failed %d\n", label, kr); return; }

    /*
     * Step 5: Create thread in child and set i386 registers.
     */
    kr = thread_create(child_task, &child_thread);
    if (kr) { printf("  %s: thread_create failed %d\n", label, kr); return; }

    state_count = i386_THREAD_STATE_COUNT;
    kr = thread_get_state(child_thread, i386_THREAD_STATE,
			  (thread_state_t)&state, &state_count);
    if (kr) { printf("  %s: get_state failed %d\n", label, kr); return; }

    state.eip  = (unsigned int)child_echo_entry;
    state.uesp = (unsigned int)(child_stack + CHILD_STACK_SIZE);

    kr = thread_set_state(child_thread, i386_THREAD_STATE,
			  (thread_state_t)&state, i386_THREAD_STATE_COUNT);
    if (kr) { printf("  %s: set_state failed %d\n", label, kr); return; }

    /*
     * Step 6: Start child thread.
     */
    kr = thread_resume(child_thread);
    if (kr) { printf("  %s: thread_resume failed %d\n", label, kr); return; }

    /* Let child settle */
    thread_switch(MACH_PORT_NULL, SWITCH_OPTION_DEPRESS, 10);

    /*
     * Step 7: Warmup.
     */
    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    /*
     * Step 8: Timed run.
     */
    cache_snap(&cs_before);
    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);
    cache_snap(&cs_after);

    print_result(label, elapsed_ns(&t0, &t1), iters);
    //print_cache_stats(label, &cs_before, &cs_after);

    /*
     * Step 9: Cleanup — destroy the child task.
     */
    task_terminate(child_task);
    mach_port_deallocate(mach_task_self(), child_thread);
    mach_port_deallocate(mach_task_self(), child_task);
    mach_port_destroy(mach_task_self(), child_recv_port);
    mach_port_destroy(mach_task_self(), parent_recv_port);
}

/* ===================================================================
 * Slow-path receive benchmark
 *
 * Guarantees the continuation path is exercised on every iteration.
 *
 * On NCPUS=1, a thread_switch(YIELD) before each send forces the echo
 * thread to run first, call mach_msg_receive, and block (no message
 * pending).  When the sender then sends, the kernel must wake up the
 * blocked receiver — this is the exact path where mach_msg_receive_
 * continue fires instead of restoring callee-saved registers.
 *
 * Comparing this number against bench_intra_rpc (where the receiver
 * may find the message already queued) isolates the slow-path cost.
 * The difference between builds with and without continuations shows
 * the continuation benefit directly.
 * =================================================================== */

/*
 * Echo thread used by the slow-path benchmark.
 * Identical to echo_thread_func but name distinguishes it for clarity.
 */
static void *
slow_echo_thread_func(void *arg)
{
    mach_port_t		port = (mach_port_t)(unsigned long)arg;
    bench_recv_buf_t	msg;
    bench_null_msg_t	reply;
    kern_return_t	kr;

    echo_signal_ready();

    for (;;) {
	kr = mach_msg(&msg.head,
		      MACH_RCV_MSG,
		      0,
		      sizeof(msg),
		      port,
		      MACH_MSG_TIMEOUT_NONE,
		      MACH_PORT_NULL);
	if (kr != MACH_MSG_SUCCESS) {
	    /*
	     * Terminal errors mean the bench destroyed the receive port
	     * — exit instead of spinning on mach_msg(RCV) forever and
	     * polluting the next test's scheduling.
	     */
	    if (kr == MACH_RCV_PORT_DIED ||
		kr == MACH_RCV_PORT_CHANGED ||
		kr == MACH_RCV_INVALID_NAME ||
		kr == MACH_RCV_TIMED_OUT)
		break;
	    continue;
	}

	reply.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
	reply.head.msgh_size	    = sizeof(reply);
	reply.head.msgh_remote_port = msg.head.msgh_remote_port;
	reply.head.msgh_local_port  = MACH_PORT_NULL;
	reply.head.msgh_id	    = msg.head.msgh_id + 100;

	mach_msg(&reply.head,
		 MACH_SEND_MSG,
		 sizeof(reply),
		 0,
		 MACH_PORT_NULL,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);
    }
    return (void *)0;
}

/*
 * bench_slow_receive:
 *
 * Measures wakeup-from-blocked latency.  Before each send, yields the
 * CPU so the echo thread runs and enters mach_msg_receive (blocking).
 * The measured time is: yield + send + wakeup-via-continuation +
 * echo-reply + receive-reply.
 *
 * The yield overhead is small (~0.1 us) and constant across builds.
 * The wakeup cost is what changes: with continuations, the receiver
 * resumes without restoring callee-saved registers (~50-100 cycles
 * faster than without).
 */
static void
bench_slow_receive(const char *label, int send_size, int iters)
{
    mach_port_t		echo_port, reply_port;
    kern_return_t	kr;
    tvalspec_t		t0, t1;
    int			i;
    bench_recv_buf_t	send_buf;
    bench_recv_buf_t	recv_buf;

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &echo_port);
    if (kr) { printf("  %s: port alloc failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(mach_task_self(),
				echo_port, echo_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert right failed %d\n", label, kr); return; }

    reply_port = mach_reply_port();

    /* Spawn echo thread and wait until it is provably running (SMP-safe). */
    spawn_echo(label, slow_echo_thread_func, echo_port);

    /* Warmup.  (The old per-iteration thread_switch(YIELD) here assumed UP
     * "echo is now blocked" semantics; on SMP it is unachievable and only
     * added a busy-yield spin, so it is gone — Mach queues the message and
     * the echo thread services it regardless of where it is.) */
    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    /* Timed run */
    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	/* Send wakes the blocked echo thread — continuation fires here */
	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);

	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    mach_port_destroy(mach_task_self(), echo_port);
    mach_port_destroy(mach_task_self(), reply_port);
}

/* ===================================================================
 * Port-operation benchmarks
 * =================================================================== */

static void
bench_port_alloc_destroy(int iters)
{
    tvalspec_t		t0, t1;
    mach_port_t		port;
    int			i;

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++) {
	mach_port_allocate(mach_task_self(),
			   MACH_PORT_RIGHT_RECEIVE, &port);
	mach_port_destroy(mach_task_self(), port);
    }

    get_time(&t0);
    for (i = 0; i < iters; i++) {
	mach_port_allocate(mach_task_self(),
			   MACH_PORT_RIGHT_RECEIVE, &port);
	mach_port_destroy(mach_task_self(), port);
    }
    get_time(&t1);

    print_result("port alloc + destroy", elapsed_ns(&t0, &t1), iters);
}

static void
bench_port_names(int iters)
{
    tvalspec_t			t0, t1;
    mach_port_array_t		names;
    mach_msg_type_number_t	names_count;
    mach_port_type_array_t	types;
    mach_msg_type_number_t	types_count;
    int				i;

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++) {
	mach_port_names(mach_task_self(),
			&names, &names_count,
			&types, &types_count);
	vm_deallocate(mach_task_self(), (vm_offset_t)names,
		      names_count * sizeof(*names));
	vm_deallocate(mach_task_self(), (vm_offset_t)types,
		      types_count * sizeof(*types));
    }

    get_time(&t0);
    for (i = 0; i < iters; i++) {
	mach_port_names(mach_task_self(),
			&names, &names_count,
			&types, &types_count);
	vm_deallocate(mach_task_self(), (vm_offset_t)names,
		      names_count * sizeof(*names));
	vm_deallocate(mach_task_self(), (vm_offset_t)types,
		      types_count * sizeof(*types));
    }
    get_time(&t1);

    print_result("mach_port_names()", elapsed_ns(&t0, &t1), iters);
}

/* ===================================================================
 * Protected payload test
 *
 * Verifies that mach_port_set_protected_payload() causes the kernel
 * to deliver the payload in msgh_local_port with the
 * MACH_MSGH_BITS_PROTECTED_PAYLOAD bit set.
 * =================================================================== */

#define PP_MAGIC_PAYLOAD	0xDEAD0042

static void
test_protected_payload(void)
{
    mach_port_t		recv_port, send_port;
    kern_return_t	kr;
    int			pass = 0, fail = 0;

    /* Allocate a receive right and make a send right */
    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &recv_port);
    if (kr != KERN_SUCCESS) {
	printf("  pp: port_allocate failed: %d\n", kr);
	return;
    }

    kr = mach_port_insert_right(mach_task_self(), recv_port,
				recv_port, MACH_MSG_TYPE_MAKE_SEND);
    if (kr != KERN_SUCCESS) {
	printf("  pp: insert_right failed: %d\n", kr);
	mach_port_destroy(mach_task_self(), recv_port);
	return;
    }
    send_port = recv_port;

    /* --- Test 1: without payload, msgh_local_port = port name --- */
    {
	bench_null_msg_t send_msg;
	mach_msg_empty_rcv_t recv_msg;

	send_msg.head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_msg.head.msgh_size = sizeof(send_msg);
	send_msg.head.msgh_remote_port = send_port;
	send_msg.head.msgh_local_port = MACH_PORT_NULL;
	send_msg.head.msgh_id = 999;

	kr = mach_msg(&send_msg.head, MACH_SEND_MSG,
		      sizeof(send_msg), 0, MACH_PORT_NULL,
		      MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	if (kr != KERN_SUCCESS) {
	    printf("  pp: send failed: %d\n", kr);
	    fail++;
	} else {
	    kr = mach_msg(&recv_msg.header, MACH_RCV_MSG,
			  0, sizeof(recv_msg), recv_port,
			  MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	    if (kr != KERN_SUCCESS) {
		printf("  pp: recv failed: %d\n", kr);
		fail++;
	    } else if (recv_msg.header.msgh_bits &
		       MACH_MSGH_BITS_PROTECTED_PAYLOAD) {
		printf("  pp: FAIL no-payload msg has PP bit set\n");
		fail++;
	    } else {
		pass++;
	    }
	}
    }

    /* --- Test 2: with payload, msgh_local_port = payload value --- */
    kr = mach_port_set_protected_payload(mach_task_self(),
					 recv_port, PP_MAGIC_PAYLOAD);
    if (kr != KERN_SUCCESS) {
	printf("  pp: set_protected_payload failed: %d\n", kr);
	fail++;
    } else {
	bench_null_msg_t send_msg;
	mach_msg_empty_rcv_t recv_msg;

	send_msg.head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_msg.head.msgh_size = sizeof(send_msg);
	send_msg.head.msgh_remote_port = send_port;
	send_msg.head.msgh_local_port = MACH_PORT_NULL;
	send_msg.head.msgh_id = 1000;

	kr = mach_msg(&send_msg.head, MACH_SEND_MSG,
		      sizeof(send_msg), 0, MACH_PORT_NULL,
		      MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	if (kr != KERN_SUCCESS) {
	    printf("  pp: send w/payload failed: %d\n", kr);
	    fail++;
	} else {
	    kr = mach_msg(&recv_msg.header, MACH_RCV_MSG,
			  0, sizeof(recv_msg), recv_port,
			  MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	    if (kr != KERN_SUCCESS) {
		printf("  pp: recv w/payload failed: %d\n", kr);
		fail++;
	    } else if (!(recv_msg.header.msgh_bits &
			 MACH_MSGH_BITS_PROTECTED_PAYLOAD)) {
		printf("  pp: FAIL payload msg missing PP bit\n");
		fail++;
	    } else if ((unsigned)recv_msg.header.msgh_local_port !=
		       PP_MAGIC_PAYLOAD) {
		printf("  pp: FAIL payload=0x%x expected 0x%x\n",
		       (unsigned)recv_msg.header.msgh_local_port,
		       PP_MAGIC_PAYLOAD);
		fail++;
	    } else {
		pass++;
	    }
	}
    }

    /* --- Test 3: clear payload (set to 0), reverts to port name --- */
    kr = mach_port_set_protected_payload(mach_task_self(),
					 recv_port, 0);
    if (kr != KERN_SUCCESS) {
	printf("  pp: clear payload failed: %d\n", kr);
	fail++;
    } else {
	bench_null_msg_t send_msg;
	mach_msg_empty_rcv_t recv_msg;

	send_msg.head.msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_msg.head.msgh_size = sizeof(send_msg);
	send_msg.head.msgh_remote_port = send_port;
	send_msg.head.msgh_local_port = MACH_PORT_NULL;
	send_msg.head.msgh_id = 1001;

	kr = mach_msg(&send_msg.head, MACH_SEND_MSG,
		      sizeof(send_msg), 0, MACH_PORT_NULL,
		      MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	if (kr != KERN_SUCCESS) {
	    printf("  pp: send after clear failed: %d\n", kr);
	    fail++;
	} else {
	    kr = mach_msg(&recv_msg.header, MACH_RCV_MSG,
			  0, sizeof(recv_msg), recv_port,
			  MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	    if (kr != KERN_SUCCESS) {
		printf("  pp: recv after clear failed: %d\n", kr);
		fail++;
	    } else if (recv_msg.header.msgh_bits &
		       MACH_MSGH_BITS_PROTECTED_PAYLOAD) {
		printf("  pp: FAIL cleared msg still has PP bit\n");
		fail++;
	    } else {
		pass++;
	    }
	}
    }

    mach_port_destroy(mach_task_self(), recv_port);

    printf("  protected payload: %d PASS, %d FAIL\n", pass, fail);
}

/* ===================================================================
 * Protected payload performance benchmark (intra-task)
 *
 * Measures RPC latency with the echo thread's receive port
 * having a protected payload set vs. not set.  Accepts send_size
 * to test with different inline data sizes.
 * =================================================================== */

static void
bench_pp_intra(const char *label, int send_size, int use_pp, int iters)
{
    mach_port_t		echo_port, reply_port;
    kern_return_t	kr;
    tvalspec_t		t0, t1;
    int			i;
    static bench_recv_buf_t	send_buf;
    static bench_recv_buf_t	recv_buf;

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &echo_port);
    if (kr) { printf("  pp bench: port alloc failed %d\n", kr); return; }

    kr = mach_port_insert_right(mach_task_self(),
				echo_port, echo_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  pp bench: insert right failed %d\n", kr); return; }

    if (use_pp) {
	kr = mach_port_set_protected_payload(mach_task_self(),
					     echo_port, PP_MAGIC_PAYLOAD);
	if (kr) { printf("  pp bench: set_payload failed %d\n", kr); return; }
    }

    reply_port = mach_reply_port();

    /* Spawn echo thread and wait until it is provably running (SMP-safe). */
    spawn_echo(label, echo_thread_func, echo_port);

    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    mach_port_destroy(mach_task_self(), echo_port);
    mach_port_destroy(mach_task_self(), reply_port);
}

/* ===================================================================
 * Protected payload performance benchmark (inter-task)
 *
 * Like bench_inter_rpc but runs twice per size: once without payload,
 * once with payload set on the child's receive port before moving it.
 * =================================================================== */

static void
bench_pp_inter(const char *label, int send_size, int use_pp, int iters)
{
    kern_return_t		kr;
    mach_port_t			child_task, child_thread;
    mach_port_t			child_recv_port;
    mach_port_t			parent_recv_port;
    vm_offset_t			child_stack;
    struct i386_thread_state	state;
    mach_msg_type_number_t	state_count;
    tvalspec_t			t0, t1;
    int				i;
    static bench_recv_buf_t	send_buf;
    static bench_recv_buf_t	recv_buf;

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE,
			    &child_recv_port);
    if (kr) { printf("  %s: alloc child_recv failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(mach_task_self(),
				child_recv_port, child_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert send right failed %d\n", label, kr); return; }

    if (use_pp) {
	kr = mach_port_set_protected_payload(mach_task_self(),
					     child_recv_port,
					     PP_MAGIC_PAYLOAD);
	if (kr) { printf("  %s: set_payload failed %d\n", label, kr); return; }
    }

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE,
			    &parent_recv_port);
    if (kr) { printf("  %s: alloc parent_recv failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(mach_task_self(),
				parent_recv_port, parent_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert parent send failed %d\n", label, kr); return; }

    kr = task_create(mach_task_self(),
		     (ledger_port_array_t)0, 0,
		     TRUE, &child_task);
    if (kr) { printf("  %s: task_create failed %d\n", label, kr); return; }

    child_stack = 0;
    kr = vm_allocate(child_task, &child_stack, CHILD_STACK_SIZE, TRUE);
    if (kr) { printf("  %s: child stack alloc failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(child_task,
				CHILD_RECV_NAME,
				child_recv_port,
				MACH_MSG_TYPE_MOVE_RECEIVE);
    if (kr) { printf("  %s: insert child recv failed %d\n", label, kr); return; }

    kr = mach_port_insert_right(child_task,
				CHILD_SEND_NAME,
				parent_recv_port,
				MACH_MSG_TYPE_COPY_SEND);
    if (kr) { printf("  %s: insert child send failed %d\n", label, kr); return; }

    kr = thread_create(child_task, &child_thread);
    if (kr) { printf("  %s: thread_create failed %d\n", label, kr); return; }

    state_count = i386_THREAD_STATE_COUNT;
    kr = thread_get_state(child_thread, i386_THREAD_STATE,
			  (thread_state_t)&state, &state_count);
    if (kr) { printf("  %s: get_state failed %d\n", label, kr); return; }

    state.eip  = (unsigned int)child_echo_entry;
    state.uesp = (unsigned int)(child_stack + CHILD_STACK_SIZE);

    kr = thread_set_state(child_thread, i386_THREAD_STATE,
			  (thread_state_t)&state, i386_THREAD_STATE_COUNT);
    if (kr) { printf("  %s: set_state failed %d\n", label, kr); return; }

    kr = thread_resume(child_thread);
    if (kr) { printf("  %s: thread_resume failed %d\n", label, kr); return; }

    thread_switch(MACH_PORT_NULL, SWITCH_OPTION_DEPRESS, 10);

    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	send_buf.head.msgh_size	      = send_size;
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    task_terminate(child_task);
    mach_port_deallocate(mach_task_self(), child_thread);
    mach_port_deallocate(mach_task_self(), child_task);
    mach_port_destroy(mach_task_self(), child_recv_port);
    mach_port_destroy(mach_task_self(), parent_recv_port);
}

/* ===================================================================
 * OOL (out-of-line) data benchmarks
 *
 * Sends a message with one OOL descriptor of the given size using
 * MACH_MSG_PHYSICAL_COPY.  The echo thread receives the OOL data
 * (kernel maps it into the receiver's address space), deallocates
 * it, and sends a null reply.
 *
 * This exercises the copyin path in ipc_kmsg_copyin_body() and the
 * copyout path in ipc_kmsg_copyout_body().  With the zero-copy
 * optimisation, large OOL regions use vm_map_copyin() with COW
 * instead of a physical copyin + vm_map_copyin(kernel_copy_map).
 * =================================================================== */

/*
 * OOL message — one out-of-line region.
 */
typedef struct {
    mach_msg_header_t		head;
    mach_msg_body_t		body;
    mach_msg_ool_descriptor_t	ool;
} bench_ool_send_msg_t;

typedef struct {
    mach_msg_header_t		head;
    mach_msg_body_t		body;
    mach_msg_ool_descriptor_t	ool;
    mach_msg_trailer_t		trailer;
} bench_ool_recv_msg_t;

/*
 * Echo thread for OOL messages: receives OOL data, deallocates it,
 * sends a null reply.
 */
static void *
ool_echo_thread_func(void *arg)
{
    mach_port_t		port = (mach_port_t)(unsigned long)arg;
    bench_ool_recv_msg_t msg;
    bench_null_msg_t	reply;
    kern_return_t	kr;

    echo_signal_ready();

    for (;;) {
	kr = mach_msg(&msg.head,
		      MACH_RCV_MSG,
		      0,
		      sizeof(msg),
		      port,
		      MACH_MSG_TIMEOUT_NONE,
		      MACH_PORT_NULL);
	if (kr != MACH_MSG_SUCCESS) {
	    /*
	     * Terminal errors mean the bench destroyed the receive port
	     * — exit instead of spinning on mach_msg(RCV) forever and
	     * polluting the next test's scheduling.
	     */
	    if (kr == MACH_RCV_PORT_DIED ||
		kr == MACH_RCV_PORT_CHANGED ||
		kr == MACH_RCV_INVALID_NAME ||
		kr == MACH_RCV_TIMED_OUT)
		break;
	    continue;
	}

	/* Deallocate received OOL data to avoid leaking memory */
	if ((msg.head.msgh_bits & MACH_MSGH_BITS_COMPLEX) &&
	    msg.body.msgh_descriptor_count == 1 &&
	    msg.ool.address != 0 && msg.ool.size > 0) {
	    vm_deallocate(mach_task_self(),
			  (vm_offset_t)msg.ool.address,
			  msg.ool.size);
	}

	reply.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
	reply.head.msgh_size	    = sizeof(reply);
	reply.head.msgh_remote_port = msg.head.msgh_remote_port;
	reply.head.msgh_local_port  = MACH_PORT_NULL;
	reply.head.msgh_id	    = msg.head.msgh_id + 100;

	mach_msg(&reply.head,
		 MACH_SEND_MSG,
		 sizeof(reply),
		 0,
		 MACH_PORT_NULL,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);
    }
    return (void *)0;
}

#define OOL_BENCH_ITERS		5000

static void
bench_ool_intra_rpc(const char *label, vm_size_t ool_size, int iters)
{
    mach_port_t		echo_port, reply_port;
    kern_return_t	kr;
    tvalspec_t		t0, t1;
    int			i;
    bench_ool_send_msg_t send_buf;
    bench_null_msg_t	recv_buf;
    vm_offset_t		data_buf;

    /* Allocate OOL data buffer */
    kr = vm_allocate(mach_task_self(), &data_buf, ool_size, TRUE);
    if (kr) { printf("  %s: vm_allocate failed %d\n", label, kr); return; }

    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &echo_port);
    if (kr) { printf("  %s: port alloc failed %d\n", label, kr); return; }
    kr = mach_port_insert_right(mach_task_self(),
				echo_port, echo_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert right failed %d\n", label, kr); return; }
    reply_port = mach_reply_port();

    /* Spawn echo thread and wait until it is provably running (SMP-safe). */
    spawn_echo(label, ool_echo_thread_func, echo_port);

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE) |
	    MACH_MSGH_BITS_COMPLEX;
	send_buf.head.msgh_size	      = sizeof(send_buf);
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;
	send_buf.body.msgh_descriptor_count = 1;
	send_buf.ool.address     = (void *)data_buf;
	send_buf.ool.size        = ool_size;
	send_buf.ool.deallocate  = FALSE;
	send_buf.ool.copy        = MACH_MSG_PHYSICAL_COPY;
	send_buf.ool.type        = MACH_MSG_OOL_DESCRIPTOR;

	mach_msg(&send_buf.head, MACH_SEND_MSG, sizeof(send_buf), 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    /* Timed run */
    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE) |
	    MACH_MSGH_BITS_COMPLEX;
	send_buf.head.msgh_size	      = sizeof(send_buf);
	send_buf.head.msgh_remote_port = echo_port;
	send_buf.head.msgh_local_port  = reply_port;
	send_buf.head.msgh_id	      = 1;
	send_buf.body.msgh_descriptor_count = 1;
	send_buf.ool.address     = (void *)data_buf;
	send_buf.ool.size        = ool_size;
	send_buf.ool.deallocate  = FALSE;
	send_buf.ool.copy        = MACH_MSG_PHYSICAL_COPY;
	send_buf.ool.type        = MACH_MSG_OOL_DESCRIPTOR;

	mach_msg(&send_buf.head, MACH_SEND_MSG, sizeof(send_buf), 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    vm_deallocate(mach_task_self(), data_buf, ool_size);
    mach_port_destroy(mach_task_self(), echo_port);
    mach_port_destroy(mach_task_self(), reply_port);
}

/* ===================================================================
 * OOL inter-task benchmark
 *
 * Creates a child task (like bench_inter_rpc), but the parent sends
 * OOL data and the child deallocates it before replying.  This
 * measures the real cross-address-space COW cost that every server
 * pays when receiving data from a client.
 * =================================================================== */

/*
 * Child echo entry for OOL messages.
 * Receives OOL data, deallocates it, sends null reply.
 * Runs in the child task — only raw mach_msg(), no MIG.
 */
/*
 * Child echo entry for OOL messages.
 * Receives OOL data and sends a null reply.
 *
 * We intentionally skip vm_deallocate() on the received OOL data:
 * the child task has no cthread context (mig_get_reply_port crashes),
 * and the child is terminated when the benchmark ends, so all its
 * memory is reclaimed.  Only raw mach_msg() (direct SYSENTER) is safe.
 */
static void __attribute__((noreturn, used))
child_ool_echo_entry(void)
{
    bench_ool_recv_msg_t	msg;
    bench_null_msg_t		reply;

    for (;;) {
	mach_msg(&msg.head,
		 MACH_RCV_MSG,
		 0,
		 sizeof(msg),
		 CHILD_RECV_NAME,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);

	reply.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0);
	reply.head.msgh_size	    = sizeof(reply);
	reply.head.msgh_remote_port = CHILD_SEND_NAME;
	reply.head.msgh_local_port  = MACH_PORT_NULL;
	reply.head.msgh_id	    = msg.head.msgh_id + 100;

	mach_msg(&reply.head,
		 MACH_SEND_MSG,
		 sizeof(reply),
		 0,
		 MACH_PORT_NULL,
		 MACH_MSG_TIMEOUT_NONE,
		 MACH_PORT_NULL);
    }
}

static void
bench_ool_inter_rpc(const char *label, vm_size_t ool_size, int iters)
{
    kern_return_t		kr;
    mach_port_t			child_task, child_thread;
    mach_port_t			child_recv_port;
    mach_port_t			parent_recv_port;
    vm_offset_t			child_stack;
    struct i386_thread_state	state;
    mach_msg_type_number_t	state_count;
    tvalspec_t			t0, t1;
    int				i;
    bench_ool_send_msg_t	send_buf;
    bench_null_msg_t		recv_buf;
    vm_offset_t			data_buf;

    /* Allocate OOL data buffer */
    kr = vm_allocate(mach_task_self(), &data_buf, ool_size, TRUE);
    if (kr) { printf("  %s: vm_allocate failed %d\n", label, kr); return; }

    /* Allocate ports */
    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &child_recv_port);
    if (kr) { printf("  %s: alloc child_recv failed %d\n", label, kr); return; }
    kr = mach_port_insert_right(mach_task_self(),
				child_recv_port, child_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert send right failed %d\n", label, kr); return; }
    kr = mach_port_allocate(mach_task_self(),
			    MACH_PORT_RIGHT_RECEIVE, &parent_recv_port);
    if (kr) { printf("  %s: alloc parent_recv failed %d\n", label, kr); return; }
    kr = mach_port_insert_right(mach_task_self(),
				parent_recv_port, parent_recv_port,
				MACH_MSG_TYPE_MAKE_SEND);
    if (kr) { printf("  %s: insert parent send right failed %d\n", label, kr); return; }

    /* Create child task */
    kr = task_create(mach_task_self(),
		     (ledger_port_array_t)0, 0, TRUE, &child_task);
    if (kr) { printf("  %s: task_create failed %d\n", label, kr); return; }

    child_stack = 0;
    kr = vm_allocate(child_task, &child_stack, CHILD_STACK_SIZE, TRUE);
    if (kr) { printf("  %s: child stack alloc failed %d\n", label, kr); return; }

    /* Insert port rights into child */
    kr = mach_port_insert_right(child_task, CHILD_RECV_NAME,
				child_recv_port, MACH_MSG_TYPE_MOVE_RECEIVE);
    if (kr) { printf("  %s: insert child recv failed %d\n", label, kr); return; }
    kr = mach_port_insert_right(child_task, CHILD_SEND_NAME,
				parent_recv_port, MACH_MSG_TYPE_COPY_SEND);
    if (kr) { printf("  %s: insert child send failed %d\n", label, kr); return; }

    /* Create and start child thread */
    kr = thread_create(child_task, &child_thread);
    if (kr) { printf("  %s: thread_create failed %d\n", label, kr); return; }

    state_count = i386_THREAD_STATE_COUNT;
    thread_get_state(child_thread, i386_THREAD_STATE,
		     (thread_state_t)&state, &state_count);
    state.eip  = (unsigned int)child_ool_echo_entry;
    state.uesp = (unsigned int)(child_stack + CHILD_STACK_SIZE);
    thread_set_state(child_thread, i386_THREAD_STATE,
		     (thread_state_t)&state, i386_THREAD_STATE_COUNT);
    thread_resume(child_thread);
    thread_switch(MACH_PORT_NULL, SWITCH_OPTION_DEPRESS, 10);

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0) |
	    MACH_MSGH_BITS_COMPLEX;
	send_buf.head.msgh_size	      = sizeof(send_buf);
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;
	send_buf.body.msgh_descriptor_count = 1;
	send_buf.ool.address     = (void *)data_buf;
	send_buf.ool.size        = ool_size;
	send_buf.ool.deallocate  = FALSE;
	send_buf.ool.copy        = MACH_MSG_PHYSICAL_COPY;
	send_buf.ool.type        = MACH_MSG_OOL_DESCRIPTOR;

	mach_msg(&send_buf.head, MACH_SEND_MSG, sizeof(send_buf), 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }

    /* Timed run */
    get_time(&t0);
    for (i = 0; i < iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, 0) |
	    MACH_MSGH_BITS_COMPLEX;
	send_buf.head.msgh_size	      = sizeof(send_buf);
	send_buf.head.msgh_remote_port = child_recv_port;
	send_buf.head.msgh_local_port  = MACH_PORT_NULL;
	send_buf.head.msgh_id	      = 1;
	send_buf.body.msgh_descriptor_count = 1;
	send_buf.ool.address     = (void *)data_buf;
	send_buf.ool.size        = ool_size;
	send_buf.ool.deallocate  = FALSE;
	send_buf.ool.copy        = MACH_MSG_PHYSICAL_COPY;
	send_buf.ool.type        = MACH_MSG_OOL_DESCRIPTOR;

	mach_msg(&send_buf.head, MACH_SEND_MSG, sizeof(send_buf), 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 parent_recv_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    get_time(&t1);

    print_result(label, elapsed_ns(&t0, &t1), iters);

    /* Cleanup */
    task_terminate(child_task);
    mach_port_deallocate(mach_task_self(), child_thread);
    mach_port_deallocate(mach_task_self(), child_task);
    mach_port_destroy(mach_task_self(), child_recv_port);
    mach_port_destroy(mach_task_self(), parent_recv_port);
    vm_deallocate(mach_task_self(), data_buf, ool_size);
}

/* ===================================================================
 * Raw syscall benchmarks (mach_null / mach_print)
 *
 * These measure the pure SYSENTER/SYSEXIT round-trip cost without
 * any IPC overhead.  Comparable to GNU Mach's mach_print benchmark.
 * =================================================================== */

#define SYSCALL_BENCH_ITERS	(1 << 18)	/* ~256K iterations */
#define SYSCALL_PRINT_ITERS	(1 << 14)	/* ~16K — printf is slow */

static void
bench_mach_null(int iters)
{
    tvalspec_t	t0, t1;
    int		i;

    /* Warmup */
    for (i = 0; i < WARMUP_ITERS; i++)
	mach_null();

    get_time(&t0);
    for (i = 0; i < iters; i++)
	mach_null();
    get_time(&t1);

    print_result("mach_null (noop trap)", elapsed_ns(&t0, &t1), iters);
}

static void
bench_mach_print(int iters)
{
    tvalspec_t	t0, t1;
    int		i;

    /* Warmup */
    for (i = 0; i < 10; i++)
	mach_print("");

    get_time(&t0);
    for (i = 0; i < iters; i++)
	mach_print("");
    get_time(&t1);

    print_result("mach_print(\"\") trap", elapsed_ns(&t0, &t1), iters);
}

/* ===================================================================
 * Test suite selection
 *
 * Without arguments: run all suites.
 * With arguments: run only the named suites.
 *
 * Valid suite names (argv):
 *   syscall  — mach_null / mach_print trap
 *   intra    — intra-task Mach IPC RPC
 *   slow     — slow-path receive (continuation)
 *   inter    — inter-task Mach IPC RPC
 *   port     — port alloc/destroy, mach_port_names
 *   pp       — protected payload (test + intra + inter)
 *   ool      — out-of-line data (intra + inter)
 *   disk     — disk I/O (ahci + ext2)
 *   mem      — memory bandwidth
 *   flipc2   — all FLIPC v2 benchmarks
 *   all      — everything (same as no arguments)
 * =================================================================== */

#define SUITE_SYSCALL	(1u <<  0)
#define SUITE_INTRA	(1u <<  1)
#define SUITE_SLOW	(1u <<  2)
#define SUITE_INTER	(1u <<  3)
#define SUITE_PORT	(1u <<  4)
#define SUITE_PP	(1u <<  5)
#define SUITE_OOL	(1u <<  6)
#define SUITE_DISK	(1u <<  7)
#define SUITE_MEM	(1u <<  8)
#define SUITE_FLIPC2	(1u <<  9)
#define SUITE_COMB	(1u << 10)
#define SUITE_CC	(1u << 11)	/* concurrent same-space (#327) */
#define SUITE_ALL	0xFFFFFFFFu

static int
streq(const char *a, const char *b)
{
    while (*a && *a == *b) { a++; b++; }
    return *a == *b;
}

static unsigned int
parse_suites(int argc, char **argv)
{
    unsigned int mask = 0;
    int i;

    for (i = 1; i < argc; i++) {
	if (streq(argv[i], "all"))	    mask |= SUITE_ALL;
	else if (streq(argv[i], "syscall")) mask |= SUITE_SYSCALL;
	else if (streq(argv[i], "intra"))   mask |= SUITE_INTRA;
	else if (streq(argv[i], "slow"))    mask |= SUITE_SLOW;
	else if (streq(argv[i], "inter"))   mask |= SUITE_INTER;
	else if (streq(argv[i], "port"))    mask |= SUITE_PORT;
	else if (streq(argv[i], "pp"))	    mask |= SUITE_PP;
	else if (streq(argv[i], "ool"))	    mask |= SUITE_OOL;
	else if (streq(argv[i], "disk"))    mask |= SUITE_DISK;
	else if (streq(argv[i], "mem"))	    mask |= SUITE_MEM;
	else if (streq(argv[i], "flipc2"))  mask |= SUITE_FLIPC2;
	else if (streq(argv[i], "comb"))    mask |= SUITE_COMB;
	else if (streq(argv[i], "cc"))	    mask |= SUITE_CC;
    }
    return mask ? mask : SUITE_ALL;
}

/* ===================================================================
 * Concurrent same-space RPC benchmark (#327)
 *
 * Spawns `nthreads` worker threads in THIS task, each driving its own
 * echo thread over a private port pair.  All of them share one ipc_space,
 * so every mach_msg they issue contends on the space lock.  With the old
 * mutex (is_read_lock == is_write_lock) the workers serialize on it; with
 * the #327 reader/writer lock the receive-side lookups run concurrently
 * while the send-side copyin still takes the write side.  We report the
 * aggregate ns/RPC so the scaling from x1 -> xN exposes the contention:
 * a flat number means full serialization, a dropping one means the read
 * side now overlaps.  Compare the same numbers against a mutex kernel
 * (A/B) to isolate the lock from raw CPU parallelism.
 * =================================================================== */

#define MAX_CC_THREADS	8

typedef struct {
    mach_port_t	echo_port;
    mach_port_t	reply_port;
    int		iters;
    int		send_size;
    pthread_t	th;
} cc_worker_t;

static volatile int g_cc_go;	/* start barrier for the timed region */

static void *
cc_worker_func(void *arg)
{
    cc_worker_t		*w = (cc_worker_t *)arg;
    bench_recv_buf_t	send_buf;
    bench_null_msg_t	recv_buf;
    int			i;

    while (!g_cc_go)		/* all workers begin together */
	;

    for (i = 0; i < w->iters; i++) {
	send_buf.head.msgh_bits =
	    MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND,
			   MACH_MSG_TYPE_MAKE_SEND_ONCE);
	send_buf.head.msgh_size	       = w->send_size;
	send_buf.head.msgh_remote_port = w->echo_port;
	send_buf.head.msgh_local_port  = w->reply_port;
	send_buf.head.msgh_id	       = 1;

	mach_msg(&send_buf.head, MACH_SEND_MSG, w->send_size, 0,
		 MACH_PORT_NULL, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	mach_msg(&recv_buf.head, MACH_RCV_MSG, 0, sizeof(recv_buf),
		 w->reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
    }
    return (void *)0;
}

static void
bench_concurrent_samespace(int nthreads, int send_size, int iters_per_thread)
{
    cc_worker_t		w[MAX_CC_THREADS];
    tvalspec_t		t0, t1;
    kern_return_t	kr;
    int			i;

    if (nthreads > MAX_CC_THREADS)
	nthreads = MAX_CC_THREADS;

    g_cc_go = 0;

    /*
     * Per worker: a private echo receive port (+ a MAKE_SEND right) and a
     * reply port, plus a dedicated echo thread.  spawn_echo() uses a single
     * global ready port, so the echo threads must be created one at a time,
     * before the workers are released.
     */
    for (i = 0; i < nthreads; i++) {
	kr = mach_port_allocate(mach_task_self(),
				MACH_PORT_RIGHT_RECEIVE, &w[i].echo_port);
	if (kr) { printf("  cc[%d]: echo alloc failed %d\n", i, kr); return; }
	mach_port_insert_right(mach_task_self(), w[i].echo_port,
			       w[i].echo_port, MACH_MSG_TYPE_MAKE_SEND);
	w[i].reply_port = mach_reply_port();
	w[i].iters	= iters_per_thread;
	w[i].send_size	= send_size;

	spawn_echo("cc-echo", echo_thread_func, w[i].echo_port);
    }

    for (i = 0; i < nthreads; i++)
	pthread_create(&w[i].th, NULL, cc_worker_func, &w[i]);

    get_time(&t0);
    g_cc_go = 1;
    for (i = 0; i < nthreads; i++)
	pthread_join(w[i].th, NULL);
    get_time(&t1);

    {
	unsigned long	total_ns  = elapsed_ns(&t0, &t1);
	long		total_rpc = (long)nthreads * iters_per_thread;
	unsigned long	per_rpc	  = total_ns / (total_rpc ? total_rpc : 1);

	printf("  concurrent same-space x%d   %ld RPCs in %lu ns  "
	       "(%lu ns/RPC aggregate)\n",
	       nthreads, total_rpc, total_ns, per_rpc);
    }

    for (i = 0; i < nthreads; i++) {
	mach_port_destroy(mach_task_self(), w[i].echo_port);
	mach_port_destroy(mach_task_self(), w[i].reply_port);
    }
}

/* ===================================================================
 * Radix overflow capability-table test (#331)
 *
 * Exercises the sparse-name code paths that the normal benchmark does
 * not: allocate_name at a high (sparse) index goes through the radix
 * overflow, a colliding index must be rejected with KERN_NAME_EXISTS,
 * and destroy must free the radix entry so the name can be re-used.
 * =================================================================== */

static void
test_radix_overflow(void)
{
    kern_return_t	kr;
    mach_port_t		self = mach_task_self();
    unsigned int	sparse = 0x100000;	/* 1M: well above the table */
    mach_port_t		name_a = (mach_port_t)((sparse << 8) | 0x11);
    mach_port_t		name_b = (mach_port_t)((sparse << 8) | 0x22); /* same idx, diff gen */
    mach_port_type_t	type;
    int			ok = 1;
    int			i;
    mach_port_t		names[8];

    /* 1) sparse allocate -> radix insert */
    kr = mach_port_allocate_name(self, MACH_PORT_RIGHT_RECEIVE, name_a);
    if (kr != KERN_SUCCESS) { printf("  radix: alloc sparse failed %d\n", kr); ok = 0; }

    /* 2) it must be found -> radix lookup */
    kr = mach_port_type(self, name_a, &type);
    if (kr != KERN_SUCCESS) { printf("  radix: type(sparse) failed %d\n", kr); ok = 0; }

    /* 3) colliding name (same index, different gen) -> KERN_NAME_EXISTS */
    kr = mach_port_allocate_name(self, MACH_PORT_RIGHT_RECEIVE, name_b);
    if (kr != KERN_NAME_EXISTS) {
	printf("  radix: collision expected KERN_NAME_EXISTS, got %d\n", kr);
	ok = 0;
    }

    /* 4) destroy -> radix delete */
    kr = mach_port_destroy(self, name_a);
    if (kr != KERN_SUCCESS) { printf("  radix: destroy(sparse) failed %d\n", kr); ok = 0; }

    /* 5) re-allocate the same name -> radix re-insert after delete */
    kr = mach_port_allocate_name(self, MACH_PORT_RIGHT_RECEIVE, name_a);
    if (kr != KERN_SUCCESS) { printf("  radix: re-alloc failed %d\n", kr); ok = 0; }
    (void) mach_port_destroy(self, name_a);

    /* 6) several sparse indices in different radix subtrees, then verify */
    for (i = 0; i < 8; i++) {
	names[i] = (mach_port_t)(((sparse + (i * 0x40000)) << 8) | 0x33);
	kr = mach_port_allocate_name(self, MACH_PORT_RIGHT_RECEIVE, names[i]);
	if (kr != KERN_SUCCESS) { printf("  radix: multi alloc[%d] failed %d\n", i, kr); ok = 0; }
    }
    for (i = 0; i < 8; i++) {
	kr = mach_port_type(self, names[i], &type);
	if (kr != KERN_SUCCESS) { printf("  radix: multi type[%d] failed %d\n", i, kr); ok = 0; }
    }
    for (i = 0; i < 8; i++)
	(void) mach_port_destroy(self, names[i]);

    printf("  radix overflow test: %s\n", ok ? "PASS" : "FAIL");
}

/* ===================================================================
 * #331 step 2 (TEMPORARY): lock-free capability-type probe.
 * urmach_cap_probe() reads a name's type via the lock-free path (no
 * space lock): seqlock snapshot of (is_table,size) + type-stable
 * table/radix/ite walk.  Validates correctness on a live name (dense
 * table path), a just-destroyed name, and a sparse name (radix path).
 * Remove with the trap once the lock-free reader is validated.
 * =================================================================== */
static void
test_cap_probe_lockfree(void)
{
    kern_return_t	kr;
    mach_port_t		self = mach_task_self();
    mach_port_t		p;
    mach_port_type_t	t;
    int			ok = 1;
    int			i;

    /* live receive right -> dense table path -> type RECEIVE */
    kr = mach_port_allocate(self, MACH_PORT_RIGHT_RECEIVE, &p);
    if (kr != KERN_SUCCESS) { printf("  cap_probe: allocate failed %d\n", kr); return; }

    t = urmach_cap_probe(p);
    if (t != MACH_PORT_TYPE_RECEIVE) {
	printf("  cap_probe: live name type 0x%x != RECEIVE\n", t); ok = 0;
    }

    /* destroyed name -> NONE (gen mismatch in the dense slot) */
    (void) mach_port_destroy(self, p);
    t = urmach_cap_probe(p);
    if (t != MACH_PORT_TYPE_NONE) {
	printf("  cap_probe: destroyed name type 0x%x != NONE\n", t); ok = 0;
    }

    /* unallocated sparse name -> NONE (radix overflow path) */
    t = urmach_cap_probe((mach_port_t)((0x200000u << 8) | 0x33));
    if (t != MACH_PORT_TYPE_NONE) {
	printf("  cap_probe: sparse name type 0x%x != NONE\n", t); ok = 0;
    }

    /* hammer the probe while the table churns under it (grow path) */
    for (i = 0; i < 4096; i++) {
	mach_port_t q;
	if (mach_port_allocate(self, MACH_PORT_RIGHT_RECEIVE, &q) == KERN_SUCCESS) {
	    if (urmach_cap_probe(q) != MACH_PORT_TYPE_RECEIVE) {
		printf("  cap_probe: churn name[%d] not RECEIVE\n", i); ok = 0;
		(void) mach_port_destroy(self, q);
		break;
	    }
	    (void) mach_port_destroy(self, q);
	}
    }

    printf("  lock-free cap probe: %s\n", ok ? "PASS" : "FAIL");
}

/* ===================================================================
 * #331 step 2 (TEMPORARY): lock-free probe under CONCURRENCY.
 * A prober thread hammers urmach_cap_probe() on a set of STABLE names
 * (allocated once, never freed) while the main thread churns the table
 * (allocate + destroy batches, forcing grows).  Invariant: a grow copies
 * each live entry to the same index in the new table, so a stable name
 * must ALWAYS probe as RECEIVE -- if the lock-free reader ever returns
 * something else it lost a live entry across a concurrent grow (a bug).
 * KVM/TSO will not surface memory-ordering bugs, but this catches faults,
 * use-after-free in the type-stable storage, and grow/seqlock logic bugs.
 * =================================================================== */
#define	CC_PROBE_STABLE	16
#define	CC_PROBE_CHURN	48
#define	CC_PROBE_ROUNDS	300

static volatile int	g_probe_stop;
static mach_port_t	g_probe_stable[CC_PROBE_STABLE];
static volatile long	g_probe_count;
static volatile long	g_probe_bad;

static void *
cap_probe_worker(void *arg)
{
    (void) arg;
    while (!g_probe_stop) {
	int i;
	for (i = 0; i < CC_PROBE_STABLE; i++) {
	    if (urmach_cap_probe(g_probe_stable[i]) != MACH_PORT_TYPE_RECEIVE)
		g_probe_bad++;
	    g_probe_count++;
	}
    }
    return NULL;
}

static void
test_cap_probe_concurrent(void)
{
    pthread_t		th;
    mach_port_t		self = mach_task_self();
    kern_return_t	kr;
    int			i, round;

    for (i = 0; i < CC_PROBE_STABLE; i++) {
	kr = mach_port_allocate(self, MACH_PORT_RIGHT_RECEIVE, &g_probe_stable[i]);
	if (kr != KERN_SUCCESS) {
	    printf("  cc-probe: stable alloc failed %d\n", kr);
	    return;
	}
    }

    g_probe_stop = 0;
    g_probe_count = 0;
    g_probe_bad = 0;
    pthread_create(&th, NULL, cap_probe_worker, NULL);

    for (round = 0; round < CC_PROBE_ROUNDS; round++) {
	mach_port_t churn[CC_PROBE_CHURN];

	for (i = 0; i < CC_PROBE_CHURN; i++)
	    if (mach_port_allocate(self, MACH_PORT_RIGHT_RECEIVE,
				   &churn[i]) != KERN_SUCCESS)
		churn[i] = MACH_PORT_NULL;
	for (i = 0; i < CC_PROBE_CHURN; i++)
	    if (churn[i] != MACH_PORT_NULL)
		(void) mach_port_destroy(self, churn[i]);
    }

    g_probe_stop = 1;
    pthread_join(th, NULL);

    for (i = 0; i < CC_PROBE_STABLE; i++)
	(void) mach_port_destroy(self, g_probe_stable[i]);

    printf("  lock-free concurrent stress: %s (%ld probes, %ld lost)\n",
	   g_probe_bad == 0 ? "PASS" : "FAIL", g_probe_count, g_probe_bad);
}

/* ===================================================================
 * Main
 * =================================================================== */

int
main(int argc, char **argv)
{
    kern_return_t	kr;
    unsigned int	suites;

    /*
     * Step 1: Get privileged ports.
     */
    kr = bootstrap_ports(bootstrap_port,
			 &host_port,
			 &device_port,
			 &root_ledger_wired,
			 &root_ledger_paged,
			 &security_port);
    if (kr != KERN_SUCCESS)
	_exit(1);

    /*
     * Step 2: Initialize console + panic.
     */
    printf_init(device_port);
    panic_init(host_port);

    /* Mirror printf onto gpu_server's text plane (#222 follow-up).
     * Async because servers launch in parallel and gpu_server may not
     * be netname-registered yet when this main() runs. */
    (void)gpu_console_init_async("bench", 100u, 50u);

    suites = parse_suites(argc, argv);

    printf("\n");
    printf("=== OSFMK IPC Performance Benchmark ===\n");
    printf("    %d iterations per test, %d warmup\n", BENCH_ITERS, WARMUP_ITERS);

    {
	host_ipc_cache_info_data_t	cinfo;
	mach_msg_type_number_t		cc = HOST_IPC_CACHE_INFO_COUNT;
	if (host_info(host_port, HOST_IPC_CACHE_INFO,
		      (host_info_t)&cinfo, &cc) == KERN_SUCCESS)
	    printf("    kmsg cache: %u slots/CPU, max msg size %u bytes\n\n",
		   cinfo.stash, cinfo.saved_size);
	else
	    printf("    kmsg cache: stats unavailable\n\n");
    }

    /*
     * Step 3: Get clock for timing.
     */
    kr = host_get_clock_service(host_port, REALTIME_CLOCK, &clock_port);
    if (kr != KERN_SUCCESS) {
	printf("(ipc_bench): clock_get failed: %d\n", kr);
	_exit(1);
    }

    /* ---------------------------------------------------------
     * Raw syscall benchmarks — measure SYSENTER/SYSEXIT cost
     * --------------------------------------------------------- */
    if (suites & SUITE_SYSCALL) {
	printf("--- Raw syscall (no IPC) ---\n");

	bench_mach_null(SYSCALL_BENCH_ITERS);
	bench_mach_print(SYSCALL_PRINT_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Intra-task benchmarks (thread-to-thread, same address space)
     * --------------------------------------------------------- */
    if (suites & SUITE_INTRA) {
	printf("--- Intra-task (thread-to-thread) ---\n");

	bench_intra_rpc("null RPC",
			(int)sizeof(bench_null_msg_t), BENCH_ITERS);
	bench_intra_rpc("128B inline RPC",
			(int)sizeof(bench_128_msg_t), BENCH_ITERS);
	bench_intra_rpc("1024B inline RPC",
			(int)sizeof(bench_1024_msg_t), BENCH_ITERS);
	bench_intra_rpc("4096B inline RPC",
			(int)sizeof(bench_4096_msg_t), BENCH_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Slow-path receive: receiver always blocked before send.
     * --------------------------------------------------------- */
    if (suites & SUITE_SLOW) {
	printf("--- Slow-path receive (continuation path) ---\n");

	bench_slow_receive("null RPC (receiver blocked)",
			   (int)sizeof(bench_null_msg_t), BENCH_ITERS);
	bench_slow_receive("128B inline RPC (receiver blocked)",
			   (int)sizeof(bench_128_msg_t), BENCH_ITERS);
	bench_slow_receive("1024B inline RPC (receiver blocked)",
			   (int)sizeof(bench_1024_msg_t), BENCH_ITERS);
	bench_slow_receive("4096B inline RPC (receiver blocked)",
			   (int)sizeof(bench_4096_msg_t), BENCH_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Inter-task benchmarks (task-to-task, separate address spaces)
     * --------------------------------------------------------- */
    if (suites & SUITE_INTER) {
	printf("--- Inter-task (task-to-task) ---\n");

	bench_inter_rpc("null RPC",
			(int)sizeof(bench_null_msg_t), BENCH_ITERS);
	bench_inter_rpc("128B inline RPC",
			(int)sizeof(bench_128_msg_t), BENCH_ITERS);
	bench_inter_rpc("1024B inline RPC",
			(int)sizeof(bench_1024_msg_t), BENCH_ITERS);
	bench_inter_rpc("4096B inline RPC",
			(int)sizeof(bench_4096_msg_t), BENCH_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Combined-trap (SEND|RCV) RPC -- exercises the mach_msg hotpath [#320]
     * --------------------------------------------------------- */
    if (suites & SUITE_COMB) {
	printf("--- Combined SEND|RCV intra-task (hotpath) ---\n");

	bench_combined_rpc("null RPC",
			   (int)sizeof(bench_null_msg_t), BENCH_ITERS);
	bench_combined_rpc("128B inline RPC",
			   (int)sizeof(bench_128_msg_t), BENCH_ITERS);
	bench_combined_rpc("1024B inline RPC",
			   (int)sizeof(bench_1024_msg_t), BENCH_ITERS);
	bench_combined_rpc("4096B inline RPC",
			   (int)sizeof(bench_4096_msg_t), BENCH_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Concurrent same-space RPC -- N threads, one ipc_space [#327]
     * Exposes the ipc_space read/write lock contention; watch the
     * aggregate ns/RPC as the thread count scales x1 -> x4.
     * --------------------------------------------------------- */
    if (suites & SUITE_CC) {
	printf("--- Concurrent same-space RPC (ipc_space lock, #327) ---\n");

	bench_concurrent_samespace(1, (int)sizeof(bench_null_msg_t),
				   BENCH_ITERS);
	bench_concurrent_samespace(2, (int)sizeof(bench_null_msg_t),
				   BENCH_ITERS);
	bench_concurrent_samespace(4, (int)sizeof(bench_null_msg_t),
				   BENCH_ITERS);

	printf("\n");
    }

    /* ---------------------------------------------------------
     * Port operation benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_PORT) {
	printf("--- Port operations ---\n");

	bench_port_alloc_destroy(BENCH_ITERS);
	bench_port_names(BENCH_ITERS);
	test_radix_overflow();		/* #331 sparse/collision paths */
	test_cap_probe_lockfree();	/* #331 step 2 lock-free reader (TEMP) */
	test_cap_probe_concurrent();	/* #331 step 2 lock-free under load (TEMP) */
    }

    /* ---------------------------------------------------------
     * Protected payload test + benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_PP) {
	printf("--- Protected payload ---\n");
	test_protected_payload();

	printf("--- PP intra-task ---\n");
	bench_pp_intra("null (no PP)",
		       (int)sizeof(bench_null_msg_t), 0, BENCH_ITERS);
	bench_pp_intra("null (w/ PP)",
		       (int)sizeof(bench_null_msg_t), 1, BENCH_ITERS);
	bench_pp_intra("128B (no PP)",
		       (int)sizeof(bench_128_msg_t), 0, BENCH_ITERS);
	bench_pp_intra("128B (w/ PP)",
		       (int)sizeof(bench_128_msg_t), 1, BENCH_ITERS);
	bench_pp_intra("1024B (no PP)",
		       (int)sizeof(bench_1024_msg_t), 0, BENCH_ITERS);
	bench_pp_intra("1024B (w/ PP)",
		       (int)sizeof(bench_1024_msg_t), 1, BENCH_ITERS);
	bench_pp_intra("4096B (no PP)",
		       (int)sizeof(bench_4096_msg_t), 0, BENCH_ITERS);
	bench_pp_intra("4096B (w/ PP)",
		       (int)sizeof(bench_4096_msg_t), 1, BENCH_ITERS);

	printf("--- PP inter-task ---\n");
	bench_pp_inter("null (no PP)",
		       (int)sizeof(bench_null_msg_t), 0, BENCH_ITERS);
	bench_pp_inter("null (w/ PP)",
		       (int)sizeof(bench_null_msg_t), 1, BENCH_ITERS);
	bench_pp_inter("128B (no PP)",
		       (int)sizeof(bench_128_msg_t), 0, BENCH_ITERS);
	bench_pp_inter("128B (w/ PP)",
		       (int)sizeof(bench_128_msg_t), 1, BENCH_ITERS);
	bench_pp_inter("1024B (no PP)",
		       (int)sizeof(bench_1024_msg_t), 0, BENCH_ITERS);
	bench_pp_inter("1024B (w/ PP)",
		       (int)sizeof(bench_1024_msg_t), 1, BENCH_ITERS);
	bench_pp_inter("4096B (no PP)",
		       (int)sizeof(bench_4096_msg_t), 0, BENCH_ITERS);
	bench_pp_inter("4096B (w/ PP)",
		       (int)sizeof(bench_4096_msg_t), 1, BENCH_ITERS);
    }

    /* ---------------------------------------------------------
     * OOL (out-of-line) data benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_OOL) {
	printf("--- OOL data (intra-task, PHYSICAL_COPY) ---\n");

	bench_ool_intra_rpc("4 KB OOL",   4096, OOL_BENCH_ITERS);
	bench_ool_intra_rpc("16 KB OOL", 16384, OOL_BENCH_ITERS);
	bench_ool_intra_rpc("64 KB OOL", 65536, OOL_BENCH_ITERS);

	printf("--- OOL data (inter-task, PHYSICAL_COPY) ---\n");

	bench_ool_inter_rpc("4 KB OOL inter",   4096, OOL_BENCH_ITERS);
	bench_ool_inter_rpc("16 KB OOL inter", 16384, OOL_BENCH_ITERS);
	bench_ool_inter_rpc("64 KB OOL inter", 65536, OOL_BENCH_ITERS);
    }

    /* ---------------------------------------------------------
     * Disk I/O benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_DISK) {
	bench_disk_run(host_port, clock_port);
	/* #232 FLIPC v2 read/write A/B moved to the standalone flipc_bench
	 * binary (#272), launched from the shell on a quiescent system. */
    }

    /* ---------------------------------------------------------
     * Memory bandwidth benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_MEM)
	bench_mem_run(clock_port);

    /* ---------------------------------------------------------
     * FLIPC v2 shared-memory channel benchmarks
     * --------------------------------------------------------- */
    if (suites & SUITE_FLIPC2)
	bench_flipc2_run(clock_port);

    /* libvfs smoke test (#220 v0.1) — hangs off the FLIPC suite gate
     * for now; pure correctness, not a perf bench. */
    if (suites & SUITE_FLIPC2) {
	extern void bench_libvfs_smoke(void);
	bench_libvfs_smoke();
    }

    /* exec_server smoke test (#228 v0.1.0) — same FLIPC gate. */
    if (suites & SUITE_FLIPC2) {
	extern void bench_exec_smoke(void);
	bench_exec_smoke();
    }

    /* proc_server smoke test (#237 v0.1.0) — same FLIPC gate. */
    if (suites & SUITE_FLIPC2) {
	extern void bench_proc_smoke(void);
	bench_proc_smoke();
    }

    printf("=== Benchmark complete ===\n");

    /*
     * Tell bootstrap we're done.
     */
    bootstrap_completed(bootstrap_port, mach_task_self());

    /*
     * Idle — don't exit, just sleep.
     */
    for (;;)
	thread_switch(MACH_PORT_NULL, SWITCH_OPTION_DEPRESS, 1000);

    return 0;
}
