
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[553] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  108,  106,  104,  105,  101,   84,   85,   82,
       80,   79,   81,   83,   95,   77,   78,   89,   86,   90,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   91,   92,   87,   94,
       93,   88,   96,  106,  106,  106,  103,  103,  102,  101,
        0,    0,  100,   95,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,    8,   94,   94,   94,   94,
       24,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,

       96,    0,   97,    0,    0,   98,    0,    0,    0,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,    9,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,    0,
       99,   94,   53,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   36,   94,   94,   94,   33,   94,   94,
       94,   94,   23,   54,   94,   94,   41,   94,   94,   94,

       94,   25,   94,   14,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   29,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   30,
       38,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   37,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   49,   94,   94,   94,   94,   94,   94,
       94,   94,   39,   94,   94,   94,   94,   94,   94,   46,
        1,   94,   94,   94,   94,   94,   94,   32,   94,   94,

       94,   31,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   44,   94,   94,   94,   94,   94,    5,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   10,   94,
       94,    6,   94,   94,   42,   94,   94,   94,   94,    4,
       94,   94,   48,   94,   94,   17,   94,   94,   94,   45,
       94,   94,   94,   94,   94,   94,   94,    3,   94,   94,
       94,   94,   51,   94,   40,   94,   35,   94,   50,    7,
       94,   94,   18,   94,   94,   94,   11,   94,   94,   94,
       21,   94,   19,   94,   27,   94,   43,   94,   94,   94,

       52,   15,   94,   28,   94,   94,   94,   22,   20,   94,
       34,   94,   47,   16,   26,   94,   94,   13,   94,   94,
        2,   94,   12,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   56,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   65,   64,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   57,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   62,   63,   94,   94,

       94,   94,   94,   94,   94,   94,   94,   94,   94,   67,
       94,   94,   94,   58,   68,   94,   69,   94,   72,   94,
       74,   94,   59,   60,   61,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   76,   94,   94,   94,   94,
       66,   94,   73,   94,   55,   94,   94,   94,   70,   71,
       75,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    1,    8,
        9,   10,   11,   12,   13,    7,   14,   15,   16,   17,
       18,   19,   15,   20,   15,   21,   15,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,    1,   53,   54,   55,    1,   56,   57,   58,   59,

       60,   32,   61,   62,   63,   36,   64,   65,   66,   67,
       68,   69,   43,   70,   71,   72,   73,   74,   49,   50,
       75,   36,    1,   76,    1,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[562] =
    {   0,
        0,    3,    9, 1055,   86,  163,   97,  101,  111,  124,
      115,  129, 1060, 1062, 1062, 1062,  132, 1062, 1062, 1062,
     1062, 1062, 1062, 1062,  139, 1062, 1062, 1062, 1062, 1062,
      132,    0,  136,   62,   76,  153,  110,  151,  143,  178,
      156,  200,  242,   86,  192,  167, 1062, 1062, 1062,  135,
     1062, 1062,    0, 1054, 1032, 1052, 1062, 1062, 1062,  228,
      276,  305,  314,  321,    0,  151,  166,  214,  168,  182,
      205,  211,  272,  215,  232,  303,  220, 1027,  181,  301,
        0,  238,  240,  252,  307,  303,  309,  306,  317,  310,
      318,  248,  244,  315,  330,  319,  323,  332,  333,  331,

        0, 1050, 1062, 1028, 1048, 1062,  393,  140, 1047,  340,
      335,  315,  337,  321,  348,  339,  354,  363,  359,  361,
      365,  368,  372,  367, 1017,  377,  390,  394,  379,  383,
      385,  368,  389,  394,  388,  407,  391,  407,  392,  402,
      404,  405,  407,  410,  408,  415,  416,  416,  416, 1045,
     1062,  418,    0,  418,  424,  424,  444,  432,  433,  440,
      438,  439,  443,  443,  464,  461,  994,  437,  463,  464,
      462,  456,  999,  464,  462,  477,  459,  480,  471,  479,
      487,  486,  491,    0,  484,  489,  468,    0,  489,  493,
      506,  489,    0,    0,  502,  502,    0,  492,  509,  511,

      503,    0,  508,    0,  515,  522, 1008,  517, 1003,  539,
      521,  541,  526,  542,  533,    0,  536,  528,  551,  544,
      544,  539,  555,  544,  541,  548,  553,  558,  552,  551,
      560,  575,  573,  567,  569,  567,  579,  592,  593,    0,
        0,  584, 1000,  590,  592,  595,  577,  597,  591,  611,
      596,  600,  601,  599,  613,  616,  601,  642,  608,  610,
      620,    0,  619,  623,  637,  616,  630,  651,  642,  642,
      640,  646,  660,    0,  648,  665,  652, 1011,  658,  659,
      664,  668,    0,  652,  669,  672,  660,  675,  677,    0,
        0,  677,  687,  683,  684,  702,  695,    0,  696,  696,

      708,    0,  699,  700,  707, 1011,  689,  717,  703,  700,
      721,    0,  712,  712,  724,  987,  718,    0,  718,  721,
      735,  741,  739,  711,  727,  737,  737,  728,  749,  747,
      759,  762,  745,  752,  753,  759,  758,  762,    0,  769,
      766,    0,  763,  768,    0,  768,  765,  770,  995,    0,
      788,  792,    0,  783,  773,    0,  781,  785,  790,    0,
      786,  803, 1008,  797,  798,  799,  803,    0,  802,  805,
      989,  813,    0,  823,    0,  825,    0,  987,    0,    0,
      815,  831,    0,  815,  818,  987,    0,  828,  824,  831,
        0,  818,    0,  821,    0,  841,    0,  832,  994,  828,

        0,    0,  832,    0,  985,  843,  841,    0,    0,  842,
        0, 1003,    0,    0,    0,  855,  864,    0,  978,  856,
        0,  883,    0,  865,  231,  992,  226,  990,  999,  989,
      982,  986,  980,  998,  982,  977,  985,  973,  861,  993,
      974,    0,  980,  986,  972,  964,  983,  982,  981,  960,
      964,  971,  962,  976,    0,    0,  951,  972,  949,  948,
      963,  946,  945,  955,  971,  952,  965,  950,   79,  953,
      888,  180,  946,  952,  960,  946,  958,  957,  956,  942,
      958,  953,  952,  965,  962,  951,    0,  939,  923,  937,
      947,  935,  932,  934,  943,  931,    0,    0,  924,  933,

      918,  929,  924,  907,  901,  900,  898,  896,  874,    0,
      900,  902,  898,    0,  859,  878,  855,  863,    0,  862,
      787,  782,    0,    0,    0,  770,  745,  622,  524,  375,
      341,  338,  328,  315,  273,    0,  277,  230,  236,  206,
        0,  205,    0,  184,    0,  172,  170,  112,    0,    0,
        0, 1062,  939,  943,  947,    4,  949,  953,  957,  961,
      965
    } ;

static const flex_int16_t yy_def[562] =
    {   0,
      553,  553,  552,    3,  554,  554,  553,  553,  553,  553,
      555,  555,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  552,  552,  552,  556,
      552,  552,  557,  558,  559,  560,  552,  552,  552,  552,
      552,  552,  552,  552,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      557,  558,  552,  559,  560,  552,  552,  552,  561,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  561,
      552,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,

      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  556,  556,  556,
      556,    0,  552,  552,  552,  552,  552,  552,  552,  552,
      552
    } ;

static const flex_int16_t yy_nxt[1140] =
    {   0,
      552,   15,   16,   15,   15,   16,   15,   65,   17,   14,
       15,   16,   15,   14,   14,   14,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       32,   32,   32,   36,   32,   37,   32,   38,   39,   40,
       41,   32,   42,   43,   44,   45,   32,   46,   32,   32,
       47,   48,   49,   32,   31,   32,   33,   34,   35,   32,
       32,   36,   37,   32,   50,   39,   40,   41,   42,   43,
       44,   45,   32,   32,   51,   52,   14,   15,   16,   15,
       14,   14,   73,   14,   14,   14,   14,   14,   15,   16,

       15,   54,   15,   16,   15,   54,   17,   14,   14,   14,
       14,   14,   15,   16,   15,   56,   58,   59,   58,   74,
       55,   73,  478,  479,   55,   15,   16,   15,   56,   17,
       58,   59,   58,   61,   60,   62,   96,   14,   14,   14,
       77,  108,  551,  108,  109,   74,   63,   63,   63,   63,
       63,   63,   63,   64,   64,   64,   64,   64,   64,   64,
       96,   14,   14,   14,   15,   16,   15,   14,   17,   77,
       14,   14,   14,   14,   14,   66,   68,   78,   67,   79,
       69,   70,   71,   80,   14,   14,   14,   14,   14,   84,
       72,   75,   76,  100,  110,   79,   85,  484,  114,  485,

      550,   66,  549,   68,   67,   79,   69,   70,   71,   81,
       80,  111,  548,  126,   14,   14,   14,   84,   75,   76,
      110,   79,  100,   85,   82,   83,   97,  114,   86,   61,
       87,   62,  115,  547,  546,   98,   99,  111,   14,   14,
       88,  126,   63,   63,   63,   63,   63,   63,   63,  116,
       82,   83,  437,  112,   97,  117,  115,   86,  120,   87,
      113,   98,   99,  124,  434,  545,  438,   88,   89,  544,
      130,  435,   90,  121,  142,  116,   91,   61,   92,   61,
      112,  117,  141,  129,  120,   93,  113,   94,   95,  124,
      107,  107,  107,  107,  107,  107,  107,   89,  118,  130,

      121,   90,  131,  142,   91,   92,   61,  543,   62,  129,
      141,   93,  542,   94,   95,  108,  119,  108,  109,   63,
       63,   63,   63,   63,   63,   63,  131,  118,   63,   63,
       63,   63,   63,   63,   63,   64,   64,   64,   64,   64,
       64,   64,  119,  122,  132,  541,  127,  133,  123,  128,
      134,  135,  137,  139,  136,  138,  140,  144,  143,  154,
      145,  146,  147,  148,  156,  149,  152,  540,  539,  158,
      122,  132,  127,  133,  123,  153,  155,  134,  137,  139,
      136,  538,  138,  140,  143,  154,  144,  145,  146,  157,
      156,  147,  148,  149,  108,  152,  108,  109,  158,  159,

      160,  162,  153,  155,  161,  163,  166,  107,  107,  107,
      107,  107,  107,  107,  164,  165,  157,  168,  175,  170,
      171,  169,  537,  176,  172,  159,  173,  160,  162,  174,
      161,  177,  163,  166,  178,  179,  180,  181,  188,  182,
      164,  165,  175,  183,  168,  184,  185,  169,  170,  171,
      172,  176,  173,  186,  187,  174,  189,  190,  177,  191,
      178,  192,  180,  194,  179,  182,  181,  188,  193,  195,
      183,  196,  184,  185,  197,  198,  199,  200,  208,  186,
      187,  201,  202,  189,  190,  191,  203,  192,  204,  194,
      205,  206,  193,  209,  210,  195,  211,  196,  214,  212,

      215,  198,  199,  197,  200,  208,  216,  201,  202,  217,
      218,  219,  203,  220,  204,  221,  222,  226,  227,  205,
      206,  225,  209,  210,  211,  212,  214,  215,  223,  228,
      229,  224,  235,  217,  233,  216,  234,  236,  219,  218,
      230,  220,  227,  237,  221,  222,  226,  231,  225,  239,
      232,  238,  536,  240,  241,  223,  228,  229,  224,  242,
      233,  235,  244,  236,  234,  246,  247,  248,  230,  249,
      250,  237,  254,  251,  231,  239,  232,  252,  238,  240,
      255,  241,  258,  256,  257,  259,  242,  260,  244,  266,
      253,  261,  247,  262,  246,  249,  248,  263,  254,  250,

      251,  264,  265,  267,  252,  268,  270,  269,  258,  255,
      256,  257,  271,  260,  259,  261,  266,  272,  273,  262,
      274,  275,  282,  263,  279,  284,  265,  264,  276,  267,
      277,  280,  281,  270,  268,  269,  283,  285,  271,  286,
      287,  272,  288,  290,  289,  273,  291,  292,  282,  274,
      275,  297,  279,  284,  276,  298,  277,  305,  280,  281,
      306,  299,  535,  283,  301,  286,  285,  287,  302,  288,
      289,  293,  290,  292,  300,  291,  294,  297,  303,  307,
      308,  298,  309,  295,  305,  310,  296,  311,  299,  306,
      301,  304,  312,  313,  302,  314,  315,  321,  317,  318,

      293,  319,  320,  324,  294,  303,  322,  308,  307,  309,
      295,  310,  296,  323,  311,  325,  328,  329,  326,  313,
      312,  330,  315,  321,  314,  317,  318,  331,  319,  324,
      320,  327,  332,  322,  341,  333,  334,  335,  336,  337,
      323,  338,  325,  328,  339,  326,  329,  342,  330,  343,
      344,  345,  346,  331,  348,  347,  356,  350,  351,  352,
      341,  332,  333,  334,  335,  353,  337,  336,  338,  354,
      357,  339,  355,  360,  344,  343,  342,  358,  359,  346,
      345,  347,  356,  348,  350,  351,  352,  361,  362,  363,
      364,  365,  534,  367,  353,  366,  357,  368,  354,  360,

      355,  369,  370,  371,  358,  359,  372,  382,  373,  374,
      533,  375,  376,  377,  361,  362,  379,  365,  363,  364,
      367,  366,  380,  381,  368,  532,  383,  369,  384,  370,
      385,  371,  386,  372,  373,  382,  374,  375,  376,  377,
      387,  531,  389,  390,  391,  379,  392,  393,  394,  396,
      381,  380,  383,  397,  384,  398,  400,  385,  386,  401,
      402,  403,  405,  408,  406,  407,  409,  387,  389,  390,
      391,  410,  392,  393,  394,  411,  396,  414,  413,  416,
      417,  418,  397,  400,  398,  420,  402,  403,  401,  408,
      405,  406,  409,  407,  421,  423,  530,  529,  450,  431,

      410,  411,  413,  414,  451,  432,  416,  417,  418,  528,
      424,  425,  527,  526,  420,  433,  525,  426,  524,  523,
      522,  427,  423,  421,  428,  521,  429,  481,  520,  430,
      519,  482,  483,  511,  518,  512,  517,  513,  514,   14,
       14,   14,   14,   53,   53,   53,   53,   57,   57,   57,
       57,  101,  101,  102,  516,  102,  102,  104,  515,  104,
      104,  105,  510,  105,  105,  150,  150,  150,  150,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  480,  477,  476,  475,  474,  473,  472,

      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  455,  454,  453,  452,
      449,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  436,  422,  419,  415,  412,  404,  399,  395,  388,
      378,  349,  340,  316,  278,  245,  243,  213,  207,  151,
      167,  151,  106,  103,  103,  125,  106,  103,  103,  552,
       17,   13,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,

      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552
    } ;

static const flex_int16_t yy_chk[1140] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,  556,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    5,    5,    5,
        5,    5,   34,    5,    5,    5,    5,    5,    7,    7,

        7,    7,    8,    8,    8,    8,    8,    5,    5,    5,
        5,    5,    9,    9,    9,    9,   11,   11,   11,   35,
        7,   34,  469,  469,    8,   10,   10,   10,   10,   10,
       12,   12,   12,   17,   12,   17,   44,    5,    5,    5,
       37,  108,  548,  108,  108,   35,   17,   17,   17,   17,
       17,   17,   17,   25,   25,   25,   25,   25,   25,   25,
       44,    5,    5,    6,    6,    6,    6,    6,    6,   37,
        6,    6,    6,    6,    6,   31,   33,   38,   31,   50,
       33,   33,   33,   39,    6,    6,    6,    6,    6,   41,
       33,   36,   36,   46,   66,   38,   41,  472,   69,  472,

      547,   31,  546,   33,   31,   50,   33,   33,   33,   40,
       39,   67,  544,   79,    6,    6,    6,   41,   36,   36,
       66,   38,   46,   41,   40,   40,   45,   69,   42,   60,
       42,   60,   70,  542,  540,   45,   45,   67,    6,    6,
       42,   79,   60,   60,   60,   60,   60,   60,   60,   71,
       40,   40,  427,   68,   45,   72,   70,   42,   74,   42,
       68,   45,   45,   77,  425,  539,  427,   42,   43,  538,
       83,  425,   43,   75,   93,   71,   43,   61,   43,   61,
       68,   72,   92,   82,   74,   43,   68,   43,   43,   77,
       61,   61,   61,   61,   61,   61,   61,   43,   73,   83,

       75,   43,   84,   93,   43,   43,   62,  537,   62,   82,
       92,   43,  535,   43,   43,   63,   73,   63,   63,   62,
       62,   62,   62,   62,   62,   62,   84,   73,   63,   63,
       63,   63,   63,   63,   63,   64,   64,   64,   64,   64,
       64,   64,   73,   76,   85,  534,   80,   86,   76,   80,
       87,   87,   88,   90,   87,   89,   91,   95,   94,  112,
       96,   97,   98,   99,  114,  100,  110,  533,  532,  116,
       76,   85,   80,   86,   76,  111,  113,   87,   88,   90,
       87,  531,   89,   91,   94,  112,   95,   96,   97,  115,
      114,   98,   99,  100,  107,  110,  107,  107,  116,  117,

      118,  120,  111,  113,  119,  121,  124,  107,  107,  107,
      107,  107,  107,  107,  122,  123,  115,  126,  132,  127,
      128,  126,  530,  133,  129,  117,  130,  118,  120,  131,
      119,  134,  121,  124,  135,  136,  137,  138,  145,  139,
      122,  123,  132,  140,  126,  141,  142,  126,  127,  128,
      129,  133,  130,  143,  144,  131,  146,  147,  134,  148,
      135,  149,  137,  154,  136,  139,  138,  145,  152,  155,
      140,  156,  141,  142,  157,  158,  159,  160,  168,  143,
      144,  161,  162,  146,  147,  148,  163,  149,  164,  154,
      165,  166,  152,  169,  170,  155,  171,  156,  174,  172,

      175,  158,  159,  157,  160,  168,  176,  161,  162,  177,
      178,  179,  163,  180,  164,  181,  182,  186,  187,  165,
      166,  185,  169,  170,  171,  172,  174,  175,  183,  189,
      190,  183,  196,  177,  192,  176,  195,  198,  179,  178,
      191,  180,  187,  199,  181,  182,  186,  191,  185,  201,
      191,  200,  529,  203,  205,  183,  189,  190,  183,  206,
      192,  196,  208,  198,  195,  210,  211,  212,  191,  213,
      214,  199,  218,  215,  191,  201,  191,  217,  200,  203,
      219,  205,  222,  220,  221,  223,  206,  224,  208,  230,
      217,  225,  211,  226,  210,  213,  212,  227,  218,  214,

      215,  228,  229,  231,  217,  232,  234,  233,  222,  219,
      220,  221,  235,  224,  223,  225,  230,  236,  237,  226,
      238,  239,  247,  227,  244,  249,  229,  228,  242,  231,
      242,  245,  246,  234,  232,  233,  248,  250,  235,  251,
      252,  236,  253,  255,  254,  237,  256,  257,  247,  238,
      239,  259,  244,  249,  242,  260,  242,  266,  245,  246,
      267,  261,  528,  248,  263,  251,  250,  252,  264,  253,
      254,  258,  255,  257,  261,  256,  258,  259,  265,  268,
      269,  260,  270,  258,  266,  271,  258,  272,  261,  267,
      263,  265,  273,  275,  264,  276,  277,  284,  279,  280,

      258,  281,  282,  287,  258,  265,  285,  269,  268,  270,
      258,  271,  258,  286,  272,  288,  292,  293,  289,  275,
      273,  294,  277,  284,  276,  279,  280,  295,  281,  287,
      282,  289,  296,  285,  307,  297,  299,  300,  301,  303,
      286,  304,  288,  292,  305,  289,  293,  308,  294,  309,
      310,  311,  313,  295,  315,  314,  324,  317,  319,  320,
      307,  296,  297,  299,  300,  321,  303,  301,  304,  322,
      325,  305,  323,  328,  310,  309,  308,  326,  327,  313,
      311,  314,  324,  315,  317,  319,  320,  329,  330,  331,
      332,  333,  527,  335,  321,  334,  325,  336,  322,  328,

      323,  337,  338,  340,  326,  327,  341,  355,  343,  344,
      526,  346,  347,  348,  329,  330,  351,  333,  331,  332,
      335,  334,  352,  354,  336,  522,  357,  337,  358,  338,
      359,  340,  361,  341,  343,  355,  344,  346,  347,  348,
      362,  521,  364,  365,  366,  351,  367,  369,  370,  372,
      354,  352,  357,  374,  358,  376,  381,  359,  361,  382,
      384,  385,  388,  392,  389,  390,  394,  362,  364,  365,
      366,  396,  367,  369,  370,  398,  372,  403,  400,  406,
      407,  410,  374,  381,  376,  416,  384,  385,  382,  392,
      388,  389,  394,  390,  417,  420,  520,  518,  439,  424,

      396,  398,  400,  403,  439,  424,  406,  407,  410,  517,
      422,  422,  516,  515,  416,  424,  513,  422,  512,  511,
      509,  422,  420,  417,  422,  508,  422,  471,  507,  422,
      506,  471,  471,  501,  505,  501,  504,  501,  501,  553,
      553,  553,  553,  554,  554,  554,  554,  555,  555,  555,
      555,  557,  557,  558,  503,  558,  558,  559,  502,  559,
      559,  560,  500,  560,  560,  561,  561,  561,  561,  499,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  486,
      485,  484,  483,  482,  481,  480,  479,  478,  477,  476,
      475,  474,  473,  470,  468,  467,  466,  465,  464,  463,

      462,  461,  460,  459,  458,  457,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  441,  440,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  426,  419,  412,  405,  399,  386,  378,  371,  363,
      349,  316,  306,  278,  243,  209,  207,  173,  167,  150,
      125,  109,  105,  104,  102,   78,   56,   55,   54,   13,
        4,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,

      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552,  552,
      552,  552,  552,  552,  552,  552,  552,  552,  552
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexxer.l"
#line 15 "lexxer.l"
/*
 * Copyright (c) 1995, 1994, 1993, 1992, 1991, 1990  
 * Open Software Foundation, Inc. 
 *  
 * Permission to use, copy, modify, and distribute this software and 
 * its documentation for any purpose and without fee is hereby granted, 
 * provided that the above copyright notice appears in all copies and 
 * that both the copyright notice and this permission notice appear in 
 * supporting documentation, and that the name of ("OSF") or Open Software 
 * Foundation not be used in advertising or publicity pertaining to 
 * distribution of the software without specific, written prior permission. 
 *  
 * OSF DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE 
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
 * FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL OSF BE LIABLE FOR ANY 
 * SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES 
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN 
 * ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, ARISING 
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE 
 */
/*
 * OSF Research Institute MK6.1 (unencumbered) 1/31/1995
 */
/* 
 * Mach Operating System
 * Copyright (c) 1991,1990 Carnegie Mellon University
 * All Rights Reserved.
 * 
 * Permission to use, copy, modify and distribute this software and its
 * documentation is hereby granted, provided that both the copyright
 * notice and this permission notice appear in all copies of the
 * software, derivative works or modified versions, and any portions
 * thereof, and that both notices appear in supporting documentation.
 * 
 * CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
 * CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
 * ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
 * 
 * Carnegie Mellon requests users of this software to return to
 * 
 *  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
 *  School of Computer Science
 *  Carnegie Mellon University
 *  Pittsburgh PA 15213-3890
 * 
 * any improvements or extensions that they make and grant Carnegie Mellon
 * the rights to redistribute these changes.
 */
/*
 * 92/03/03  16:25:00  jeffreyh
 * 	Changes from TRUNK
 * 	[92/02/26  12:31:19  jeffreyh]
 * 
 * 92/01/23  15:21:24  rpd
 * 	Fixed macros for STDC.
 * 	[92/01/16            rpd]
 * 
 * 92/01/03  20:29:25  dbg
 * 	Add 'CountInOut' flag.
 * 	[91/11/11            dbg]
 * 
 * 91/08/28  11:17:01  jsb
 * 	Added syServerDemux.
 * 	[91/08/13            rpd]
 * 
 * 	Removed syMsgKind, syCamelot, syCamelotRoutine, syTrapRoutine,
 * 	syTrapSimpleRoutine.  Added syMsgSeqno.
 * 	[91/08/11            rpd]
 * 
 * 91/07/31  18:09:31  dbg
 * 	Add 'serverCopy' keyword.
 * 	[91/06/05            dbg]
 * 
 * 	Add 'c_string' keyword.
 * 	[91/04/03            dbg]
 * 
 * 91/02/05  17:54:51  mrt
 * 	Changed to new Mach copyright
 * 	[91/02/01  17:54:35  mrt]
 * 
 * 90/06/02  15:04:54  rpd
 * 	Created for new IPC.
 * 	[90/03/26  21:11:34  rpd]
 * 
 * 07-Apr-89  Richard Draves (rpd) at Carnegie-Mellon University
 *	Extensive revamping.  Added polymorphic arguments.
 *	Allow multiple variable-sized inline arguments in messages.
 *
 * 27-May-87  Richard Draves (rpd) at Carnegie-Mellon University
 *	Created.
 */

#include "strdefs.h"
#include "type.h"
#include <mach/message.h>
#include "statement.h"
#include "global.h"
#include "parser.h"
#include "lexxer.h"
#include <execinfo.h>
#include <signal.h>

static void SafeEcho(const char *buf, size_t len)
{
    size_t i;
    for (i = 0; i < len; ++i) {
        unsigned char b = (unsigned char)buf[i];
        if ((b < 32 && b != 9 && b != 10 && b != 13) || b > 126) {
            fprintf(stderr, "[lexxer-SafeEcho] non-ASCII byte 0x%02x at offset %zu\n", b, i);
            void *bt[32];
            int n = backtrace(bt, 32);
            backtrace_symbols_fd(bt, n, fileno(stderr));
            raise(SIGTRAP);
        }
    }
    /* If no non-ASCII found, write out as before */
    fwrite(buf, (size_t) len, 1, yyout);
}

#undef ECHO
#define ECHO do { SafeEcho(yytext, yyleng); } while (0)

#ifdef	__STDC__
#define stringize(x)	#x
#else	/* __STDC__ */
#define	stringize(x)	"x"
#endif	/* __STDC__ */

#ifdef	LDEBUG
#define RETURN(sym)							\
{									\
    printf("yylex: returning '%s' (%d)\n", stringize(sym), (sym));	\
    return (sym);							\
}
#else	/* LDEBUG */
#define RETURN(sym)	return (sym)
#endif	/* LDEBUG */

#define	TPRETURN(intype, outtype, tsize)				\
{									\
    yylval.symtype.innumber = (intype);					\
    yylval.symtype.instr = stringize(intype);				\
    yylval.symtype.outnumber = (outtype);				\
    yylval.symtype.outstr = stringize(outtype);				\
    yylval.symtype.size = (tsize);					\
    RETURN(sySymbolicType);						\
}

#define	TRETURN(type, tsize)	TPRETURN(type,type,tsize)

#define SAVE(s)		do {oldYYBegin = s; BEGIN s; } while (0)

#define RESTORE		BEGIN oldYYBegin

#define	FRETURN(val)							\
{									\
    yylval.flag = (val);						\
    RETURN(syIPCFlag);							\
}

static int	oldYYBegin = 0;

int lineno = 0;			/* Replaces lex yylineno */

static void doSharp(); /* process body of # directives */
extern void yyerror(char *);
#line 1044 "lex.yy.c"

#line 1046 "lex.yy.c"

#define INITIAL 0
#define Normal 1
#define String 2
#define FileName 3
#define QString 4
#define SkipToEOL 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 185 "lexxer.l"


#line 1274 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 553 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1062 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 187 "lexxer.l"
RETURN(syRoutine);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 188 "lexxer.l"
RETURN(sySimpleRoutine);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 189 "lexxer.l"
RETURN(sySubsystem);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 190 "lexxer.l"
RETURN(syMsgOption);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 191 "lexxer.l"
RETURN(syMsgSeqno);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 192 "lexxer.l"
RETURN(syWaitTime);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 193 "lexxer.l"
RETURN(syNoWaitTime);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 194 "lexxer.l"
RETURN(syIn);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 195 "lexxer.l"
RETURN(syOut);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 196 "lexxer.l"
RETURN(syUserImpl);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 197 "lexxer.l"
RETURN(syServerImpl);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 198 "lexxer.l"
RETURN(syServerSecToken);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 199 "lexxer.l"
RETURN(syUserSecToken);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 200 "lexxer.l"
RETURN(syInOut);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 201 "lexxer.l"
RETURN(syRequestPort);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 202 "lexxer.l"
RETURN(syRequestPort);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 203 "lexxer.l"
RETURN(syReplyPort);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 204 "lexxer.l"
RETURN(syReplyPort);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 205 "lexxer.l"
RETURN(syUReplyPort);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 206 "lexxer.l"
RETURN(syUReplyPort);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 207 "lexxer.l"
RETURN(sySReplyPort);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 208 "lexxer.l"
RETURN(sySReplyPort);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 209 "lexxer.l"
RETURN(syArray);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 210 "lexxer.l"
RETURN(syOf);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 211 "lexxer.l"
RETURN(syErrorProc);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 212 "lexxer.l"
RETURN(syServerPrefix);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 213 "lexxer.l"
RETURN(syUserPrefix);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 214 "lexxer.l"
RETURN(syServerDemux);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 215 "lexxer.l"
RETURN(syRCSId);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 216 "lexxer.l"
RETURN(syImport);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 217 "lexxer.l"
RETURN(syUImport);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 218 "lexxer.l"
RETURN(sySImport);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 219 "lexxer.l"
RETURN(syType);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 220 "lexxer.l"
RETURN(syKernelServer);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 221 "lexxer.l"
RETURN(syKernelUser);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 222 "lexxer.l"
RETURN(sySkip);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 223 "lexxer.l"
RETURN(syStruct);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 224 "lexxer.l"
RETURN(syInTran);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 225 "lexxer.l"
RETURN(syOutTran);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 226 "lexxer.l"
RETURN(syDestructor);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 227 "lexxer.l"
RETURN(syCType);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 228 "lexxer.l"
RETURN(syCUserType);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 229 "lexxer.l"
RETURN(syCServerType);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 230 "lexxer.l"
RETURN(syCString);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 232 "lexxer.l"
FRETURN(flSameCount);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 233 "lexxer.l"
FRETURN(flRetCode);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 234 "lexxer.l"
FRETURN(flPhysicalCopy);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 235 "lexxer.l"
FRETURN(flOverwrite);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 236 "lexxer.l"
FRETURN(flDealloc);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 237 "lexxer.l"
FRETURN(flNotDealloc);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 238 "lexxer.l"
FRETURN(flCountInOut);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 239 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC, MACH_MSG_TYPE_POLYMORPHIC, 32);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 240 "lexxer.l"
FRETURN(flAuto);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 241 "lexxer.l"
FRETURN(flConst);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 244 "lexxer.l"
TRETURN(MACH_MSG_TYPE_UNSTRUCTURED,0);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 245 "lexxer.l"
TRETURN(MACH_MSG_TYPE_BIT,1);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 246 "lexxer.l"
TRETURN(MACH_MSG_TYPE_BOOLEAN,32);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 247 "lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_8,8);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 248 "lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_16,16);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 249 "lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_32,32);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 250 "lexxer.l"
TRETURN(MACH_MSG_TYPE_INTEGER_64,64);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 251 "lexxer.l"
TRETURN(MACH_MSG_TYPE_REAL_32,32);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 252 "lexxer.l"
TRETURN(MACH_MSG_TYPE_REAL_64,64);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 253 "lexxer.l"
TRETURN(MACH_MSG_TYPE_CHAR,8);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 254 "lexxer.l"
TRETURN(MACH_MSG_TYPE_BYTE,8);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 256 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_RECEIVE,MACH_MSG_TYPE_PORT_RECEIVE,32);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 257 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_COPY_SEND,MACH_MSG_TYPE_PORT_SEND,32);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 258 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_MAKE_SEND,MACH_MSG_TYPE_PORT_SEND,32);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 259 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_SEND,MACH_MSG_TYPE_PORT_SEND,32);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 260 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_MAKE_SEND_ONCE,MACH_MSG_TYPE_PORT_SEND_ONCE,32);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 261 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_MOVE_SEND_ONCE,MACH_MSG_TYPE_PORT_SEND_ONCE,32);
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 263 "lexxer.l"
TRETURN(MACH_MSG_TYPE_PORT_NAME,32);
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 264 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_RECEIVE,32);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 265 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_SEND,32);
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 266 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC,MACH_MSG_TYPE_PORT_SEND_ONCE,32);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 267 "lexxer.l"
TPRETURN(MACH_MSG_TYPE_POLYMORPHIC, MACH_MSG_TYPE_POLYMORPHIC, 32);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 269 "lexxer.l"
RETURN(syColon);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 270 "lexxer.l"
RETURN(sySemi);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 271 "lexxer.l"
RETURN(syComma);
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 272 "lexxer.l"
RETURN(syPlus);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 273 "lexxer.l"
RETURN(syMinus);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 274 "lexxer.l"
RETURN(syStar);
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 275 "lexxer.l"
RETURN(syDiv);
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 276 "lexxer.l"
RETURN(syLParen);
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 277 "lexxer.l"
RETURN(syRParen);
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 278 "lexxer.l"
RETURN(syEqual);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 279 "lexxer.l"
RETURN(syCaret);
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 280 "lexxer.l"
RETURN(syTilde);
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 281 "lexxer.l"
RETURN(syLAngle);
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 282 "lexxer.l"
RETURN(syRAngle);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 283 "lexxer.l"
RETURN(syLBrack);
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 284 "lexxer.l"
RETURN(syRBrack);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 285 "lexxer.l"
RETURN(syBar);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 287 "lexxer.l"
{ yylval.identifier = strmake(yytext);
			  RETURN(syIdentifier); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 289 "lexxer.l"
{ yylval.number = atoi(yytext); RETURN(syNumber); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 291 "lexxer.l"
{ yylval.string = strmake(yytext);
			  SAVE(Normal); RETURN(syString); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 293 "lexxer.l"
{ yylval.string = strmake(yytext);
			  SAVE(Normal); RETURN(syFileName); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 295 "lexxer.l"
{ yylval.string = strmake(yytext);
			  SAVE(Normal); RETURN(syQString); }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 298 "lexxer.l"
{ doSharp(yytext+1);
					  BEGIN SkipToEOL; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 300 "lexxer.l"
{ doSharp(yytext+1);
					  BEGIN SkipToEOL; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 302 "lexxer.l"
{ yyerror("illegal # directive");
					  BEGIN SkipToEOL; }
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 305 "lexxer.l"
{ RESTORE; lineno++; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 306 "lexxer.l"
;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 308 "lexxer.l"
;
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 309 "lexxer.l"
lineno++;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 310 "lexxer.l"
{ SAVE(Normal); RETURN(syError); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 312 "lexxer.l"
ECHO;
	YY_BREAK
#line 1877 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Normal):
case YY_STATE_EOF(String):
case YY_STATE_EOF(FileName):
case YY_STATE_EOF(QString):
case YY_STATE_EOF(SkipToEOL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 553 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 553 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 552);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 312 "lexxer.l"


extern void
LookNormal()
{
    SAVE(Normal);
}

extern void
LookString()
{
    SAVE(String);
}

extern void
LookQString()
{
    SAVE(QString);
}

extern void
LookFileName()
{
    SAVE(FileName);
}

static void
doSharp(char *body)
{
    register char *startName, *endName;

    lineno = atoi(body);
    startName = strchr(body, '"');
    if (startName != NULL)
    {
	endName = strrchr(body, '"');
	*endName = '\0';
	strfree(yyinname);
	yyinname = strmake(startName+1);
    }
}


