# Turn a binary file into a C array, in CMake script mode.
#
#   cmake -DIN=<file> -DOUT=<file.c> -DSYM=<name> -P bin2c.cmake
#
# ⚠️ Here rather than `xxd -i' because xxd is not a build dependency anywhere
# else in this tree, and a rule that works on the machine it was written on is
# how a build stops being reproducible.  file(READ ... HEX) is CMake's own.

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _len)
math(EXPR _bytes "${_len} / 2")

set(_body "")
set(_i 0)
set(_col 0)
while(_i LESS _len)
  string(SUBSTRING "${_hex}" ${_i} 2 _b)
  string(APPEND _body "0x${_b},")
  math(EXPR _col "${_col} + 1")
  if(_col EQUAL 12)
    string(APPEND _body "\n\t")
    set(_col 0)
  endif()
  math(EXPR _i "${_i} + 2")
endwhile()

file(WRITE "${OUT}"
"/* Generated by cmake/bin2c.cmake from ${IN} -- do not edit. */\n"
"#include <stddef.h>\n"
"const unsigned char ${SYM}[] = {\n\t${_body}\n};\n"
"const unsigned int ${SYM}_size = ${_bytes};\n")
