/*
 * System call switch table.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from/home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

#include <ktrace.h>
#include <compat_43.h>
#include <sys/param.h>
#include <sys/systm.h>

int	nosys();

#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
int	rexit();
int	fork();
int	open();
int	close();
int	wait4();
int	link();
int	unlink();
int	chdir();
int	fchdir();
int	mknod();
int	getfsstat();
int	lseek();
int	getpid();
int	mount();
int	unmount();
int	setuid();
int	getuid();
int	geteuid();
int	recvmsg();
int	sendmsg();
int	accept();
int	getpeername();
int	getsockname();
int	saccess();
int	sync();
int	kill();
int	stat();
int	getppid();
int	dup();
int	pipe();
int	getegid();
int	sigaction();
int	getgid();
int	sigprocmask();
int	getlogin();
int	setlogin();
int	sysacct();
#if MAP_UAREA
int	sigpending();
#else
int	sigpending();
#endif
#ifdef notyet
#else
#endif
int	ioctl();
int	reboot();
int	revoke();
int	symlink();
int	readlink();
#if NMAP_UAREA
int	umask();
#else
int	umask();
#endif
int	chroot();
int	msync();
int	vfork();
int	munmap();
int	mprotect();
int	madvise();
int	mincore();
int	getgroups();
int	setgroups();
int	getpgrp();
int	setpgid();
int	setitimer();
int	swapon();
int	getitimer();
int	getdtablesize();
int	dup2();
int	fcntl();
int	select();
int	fsync();
int	setpriority();
int	socket();
int	getpriority();
int	sigreturn();
int	listen();
#if MAP_UAREA
#else
#endif
int	sigsuspend();
int	gettimeofday();
int	getrusage();
int	rename();
int	flock();
int	mkfifo();
int	shutdown();
int	socketpair();
int	mkdir();
int	rmdir();
#if MAP_UAREA
int	getrlimit();
#else
int	getrlimit();
#endif
int	setsid();
int	quotactl();
#if NFS
int	nfssvc();
#else
#endif
int	getdirentries();
int	statfs();
int	fstatfs();
#if NFS
int	getfh();
#else
#endif
#if SYSVSHM
int	shmsys();
#else
#endif
int	setgid();
int	setegid();
int	seteuid();
int	table();
int	sysctrace();

#if COMPAT_43
#define compat(n, name) n, __CONCAT(o,name)

#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
#if MAP_UAREA
#else
#endif
#ifdef notyet
#else
#endif
#if NMAP_UAREA
#else
#endif
#if MAP_UAREA
int	osigblock();
int	osigsetmask();
#else
int	osigblock();
int	osigsetmask();
#endif
int	osigstack();
int	osetreuid();
int	osetregid();
#if MAP_UAREA
#else
#endif
int	okillpg();
#if NFS
#else
#endif
#if NFS
#else
#endif
#if SYSVSHM
#else
#endif

#else /* COMPAT_43 */
#define compat(n, name) 0, nosys
#endif /* COMPAT_43 */

struct sysent sysent[] = {
#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
	0, nosys,			/* 0 = indir or out-of-range */
	0, rexit,			/* 1 = exit */
	0, fork,			/* 2 = fork */
	0, nosys,			/* 3 = emulated read */
	0, nosys,			/* 4 = emulated write */
	0, open,			/* 5 = open */
	0, close,			/* 6 = close */
	0, wait4,			/* 7 = wait4 */
	0, nosys,			/* 8 = emulated creat */
	0, link,			/* 9 = link */
	0, unlink,			/* 10 = unlink */
	0, nosys,			/* 11 = obsolete execv execv */
	0, chdir,			/* 12 = chdir */
	0, fchdir,			/* 13 = fchdir */
	0, mknod,			/* 14 = mknod */
	0, nosys,			/* 15 = emulated chmod */
	0, nosys,			/* 16 = emulated chown */
	0, nosys,			/* 17 = emulated brk */
	0, getfsstat,			/* 18 = getfsstat */
	0, lseek,			/* 19 = lseek */
	0, getpid,			/* 20 = getpid */
	0, mount,			/* 21 = mount */
	0, unmount,			/* 22 = unmount */
	0, setuid,			/* 23 = setuid */
	0, getuid,			/* 24 = getuid */
	0, geteuid,			/* 25 = geteuid */
	0, nosys,			/* 26 = emulated ptrace */
	0, recvmsg,			/* 27 = recvmsg */
	0, sendmsg,			/* 28 = sendmsg */
	0, nosys,			/* 29 = emulated recvfrom */
	0, accept,			/* 30 = accept */
	0, getpeername,			/* 31 = getpeername */
	0, getsockname,			/* 32 = getsockname */
	0, saccess,			/* 33 = access */
	0, nosys,			/* 34 = emulated chflags */
	0, nosys,			/* 35 = emulated fchflags */
	0, sync,			/* 36 = sync */
	0, kill,			/* 37 = kill */
	0, stat,			/* 38 = stat */
	0, getppid,			/* 39 = getppid */
	0, nosys,			/* 40 = emulated lstat */
	0, dup,			/* 41 = dup */
	0, pipe,			/* 42 = pipe */
	0, getegid,			/* 43 = getegid */
	0, nosys,			/* 44 = obsolete profil profil junk X void *bufbase, size_t bufsize, unsigned pcoffset, unsigned pcscale */
	0, nosys,			/* 45 = ktrace ktrace */
	0, sigaction,			/* 46 = sigaction */
	0, getgid,			/* 47 = getgid */
	0, sigprocmask,			/* 48 = sigprocmask */
	0, getlogin,			/* 49 = getlogin */
	0, setlogin,			/* 50 = setlogin */
	0, sysacct,			/* 51 = acct */
#if MAP_UAREA
	0, sigpending,			/* 52 = sigpending */
#else
	0, sigpending,			/* 52 = sigpending */
#endif
#ifdef notyet
#else
	0, nosys,			/* 53 = sigaltstack sigaltstack */
#endif
	0, ioctl,			/* 54 = ioctl */
	0, reboot,			/* 55 = reboot */
	0, revoke,			/* 56 = revoke */
	0, symlink,			/* 57 = symlink */
	0, readlink,			/* 58 = readlink */
	0, nosys,			/* 59 = emulated execve */
#if NMAP_UAREA
	0, umask,			/* 60 = umask */
#else
	0, umask,			/* 60 = umask */
#endif
	0, chroot,			/* 61 = chroot */
	0, nosys,			/* 62 = emulated fstat */
	0, nosys,			/* 63 = obsolete getkerninfo getkerninfo int ? int op, char *where, int *size, int arg */
	0, nosys,			/* 64 = emulated getpagesize */
	0, msync,			/* 65 = msync */
	0, vfork,			/* 66 = vfork */
	0, nosys,			/* 67 = obsolete vread vread */
	0, nosys,			/* 68 = obsolete vwrite vwrite */
	0, nosys,			/* 69 = emulated sbrk */
	0, nosys,			/* 70 = obsolete sstk sstk */
	0, nosys,			/* 71 = emulated mmap */
	0, nosys,			/* 72 = obsolete ovadvise vadvise */
	0, munmap,			/* 73 = munmap */
	0, mprotect,			/* 74 = mprotect */
	0, madvise,			/* 75 = madvise */
	0, nosys,			/* 76 = obsolete vhangup vhangup */
	0, nosys,			/* 77 = obsolete vlimit vlimit */
	0, mincore,			/* 78 = mincore */
	0, getgroups,			/* 79 = getgroups */
	0, setgroups,			/* 80 = setgroups */
	0, getpgrp,			/* 81 = getpgrp */
	0, setpgid,			/* 82 = setpgid */
	0, setitimer,			/* 83 = setitimer */
	0, nosys,			/* 84 = emulated wait */
	0, swapon,			/* 85 = swapon */
	0, getitimer,			/* 86 = getitimer */
	0, nosys,			/* 87 = emulated gethostname */
	0, nosys,			/* 88 = emulated sethostname */
	0, getdtablesize,			/* 89 = getdtablesize */
	0, dup2,			/* 90 = dup2 */
	0, nosys,			/* 91 = getdopt getdopt */
	0, fcntl,			/* 92 = fcntl */
	0, select,			/* 93 = select */
	0, nosys,			/* 94 = setdopt setdopt */
	0, fsync,			/* 95 = fsync */
	0, setpriority,			/* 96 = setpriority */
	0, socket,			/* 97 = socket */
	0, nosys,			/* 98 = emulated connect */
	0, nosys,			/* 99 = obsolete accept accept int fd int s, struct sockaddr *addr, int *addrlen */
	0, getpriority,			/* 100 = getpriority */
	0, nosys,			/* 101 = emulated send */
	0, nosys,			/* 102 = emulated recv */
	0, sigreturn,			/* 103 = sigreturn */
	0, nosys,			/* 104 = emulated bind */
	0, nosys,			/* 105 = emulated setsockopt */
	0, listen,			/* 106 = listen */
	0, nosys,			/* 107 = obsolete vtimes vtimes */
	0, nosys,			/* 108 = emulated sigvec */
#if MAP_UAREA
	compat(1,sigblock),		/* 109 = old sigblock */
	compat(1,sigsetmask),		/* 110 = old sigsetmask */
#else
	compat(1,sigblock),		/* 109 = old sigblock */
	compat(1,sigsetmask),		/* 110 = old sigsetmask */
#endif
	0, sigsuspend,			/* 111 = sigsuspend */
	compat(2,sigstack),		/* 112 = old sigstack */
	0, nosys,			/* 113 = obsolete recvmsg recvmsg int nreceived int fd, struct msghdr *msg, int flags */
	0, nosys,			/* 114 = obsolete sendmsg sendmsg int nset int s, const struct msghdr *msg, int flags */
	0, nosys,			/* 115 = obsolete vtrace vtrace */
	0, gettimeofday,			/* 116 = gettimeofday */
	0, getrusage,			/* 117 = getrusage */
	0, nosys,			/* 118 = emulated getsockopt */
	0, nosys,			/* 119 = nosys nosys */
	0, nosys,			/* 120 = emulated readv */
	0, nosys,			/* 121 = emulated writev */
	0, nosys,			/* 122 = emulated settimeofday */
	0, nosys,			/* 123 = emulated fchown */
	0, nosys,			/* 124 = emulated fchmod */
	0, nosys,			/* 125 = obsolete recvfrom recvfrom int nreceived int s, void *buf, int len, int flags, struct sockaddr *from, int *fromlen */
	compat(2,setreuid),		/* 126 = old setreuid */
	compat(2,setregid),		/* 127 = old setregid */
	0, rename,			/* 128 = rename */
	0, nosys,			/* 129 = emulated truncate */
	0, nosys,			/* 130 = emulated ftruncate */
	0, flock,			/* 131 = flock */
	0, mkfifo,			/* 132 = mkfifo */
	0, nosys,			/* 133 = emulated sendto */
	0, shutdown,			/* 134 = shutdown */
	0, socketpair,			/* 135 = socketpair */
	0, mkdir,			/* 136 = mkdir */
	0, rmdir,			/* 137 = rmdir */
	0, nosys,			/* 138 = emulated utimes */
	0, nosys,			/* 139 = obsolete 4.2 sigreturn sigreturn */
	0, nosys,			/* 140 = emulated adjtime */
	0, nosys,			/* 141 = obsolete getpeername getpeername junk X int s, struct sockaddr *name, int *namelen */
	0, nosys,			/* 142 = emulated gethostid */
	0, nosys,			/* 143 = emulated sethostid */
#if MAP_UAREA
	0, getrlimit,			/* 144 = getrlimit */
#else
	0, getrlimit,			/* 144 = getrlimit */
#endif
	0, nosys,			/* 145 = emulated setrlimit */
	compat(2,killpg),		/* 146 = old killpg */
	0, setsid,			/* 147 = setsid */
	0, quotactl,			/* 148 = quotactl */
	0, nosys,			/* 149 = emulated quota */
	0, nosys,			/* 150 = obsolete getsockname getsockname junk X int s, struct sockaddr *name, int *namelen */
	0, nosys,			/* 151 = nosys nosys */
	0, nosys,			/* 152 = nosys nosys */
	0, nosys,			/* 153 = nosys nosys */
	0, nosys,			/* 154 = nosys nosys */
#if NFS
	0, nfssvc,			/* 155 = nfssvc */
#else
	0, nosys,			/* 155 = nosys nosys */
#endif
	0, getdirentries,			/* 156 = getdirentries */
	0, statfs,			/* 157 = statfs */
	0, fstatfs,			/* 158 = fstatfs */
	0, nosys,			/* 159 = nosys nosys */
	0, nosys,			/* 160 = nosys nosys */
#if NFS
	0, getfh,			/* 161 = getfh */
#else
	0, nosys,			/* 161 = nosys nosys */
#endif
	0, nosys,			/* 162 = emulated getdomainname */
	0, nosys,			/* 163 = emulated setdomainname */
	0, nosys,			/* 164 = emulated uname */
	0, nosys,			/* 165 = nosys nosys */
	0, nosys,			/* 166 = nosys nosys */
	0, nosys,			/* 167 = nosys nosys */
	0, nosys,			/* 168 = nosys nosys */
	0, nosys,			/* 169 = nosys nosys */
	0, nosys,			/* 170 = nosys nosys */
#if SYSVSHM
	0, shmsys,			/* 171 = shmsys */
#else
	0, nosys,			/* 171 = nosys nosys */
#endif
	0, nosys,			/* 172 = nosys nosys */
	0, nosys,			/* 173 = nosys nosys */
	0, nosys,			/* 174 = nosys nosys */
	0, nosys,			/* 175 = nosys nosys */
	0, nosys,			/* 176 = nosys nosys */
	0, nosys,			/* 177 = nosys nosys */
	0, nosys,			/* 178 = nosys nosys */
	0, nosys,			/* 179 = nosys nosys */
	0, nosys,			/* 180 = nosys nosys */
	0, setgid,			/* 181 = setgid */
	0, setegid,			/* 182 = setegid */
	0, seteuid,			/* 183 = seteuid */
	0, nosys,			/* 184 = nosys nosys */
	0, nosys,			/* 185 = nosys nosys */
	0, nosys,			/* 186 = nosys nosys */
	0, nosys,			/* 187 = nosys nosys */
	0, nosys,			/* 188 = nosys nosys */
	0, nosys,			/* 189 = nosys nosys */
	0, nosys,			/* 190 = nosys nosys */
	0, nosys,			/* 191 = nosys nosys */
	0, nosys,			/* 192 = nosys nosys */
	0, nosys,			/* 193 = nosys nosys */
	0, nosys,			/* 194 = nosys nosys */
	0, nosys,			/* 195 = nosys nosys */
	0, nosys,			/* 196 = nosys nosys */
	0, nosys,			/* 197 = nosys nosys */
	0, nosys,			/* 198 = nosys nosys */
	0, nosys,			/* 199 = nosys nosys */
	0, table,			/* 200 = table */
	0, sysctrace,			/* 201 = sysctrace */
	0, nosys,			/* 202 = emulated __sysctl */
};

int	nsysent = sizeof(sysent) / sizeof(sysent[0]);
