/*
 * System call names.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * created from/home/slex/Scaricati/xMach-main/lites/server/kern/syscalls.master
 */

char *syscallnames[] = {
#if KERNEL
#include <nfs.h>
#include <sysvshm.h>
#include <map_uarea.h>
#include <ktrace.h>
#include <trace.h>
#endif
	"#0",			/* 0 = indir or out-of-range */
	"exit",			/* 1 = exit */
	"fork",			/* 2 = fork */
	"read",			/* 3 = read */
	"write",			/* 4 = write */
	"open",			/* 5 = open */
	"close",			/* 6 = close */
	"wait4",			/* 7 = wait4 */
	"creat",			/* 8 = creat */
	"link",			/* 9 = link */
	"unlink",			/* 10 = unlink */
	"obs_execv",			/* 11 = obsolete execv execv */
	"chdir",			/* 12 = chdir */
	"fchdir",			/* 13 = fchdir */
	"mknod",			/* 14 = mknod */
	"chmod",			/* 15 = chmod */
	"chown",			/* 16 = chown */
	"brk",			/* 17 = brk */
	"getfsstat",			/* 18 = getfsstat */
	"lseek",			/* 19 = lseek */
	"getpid",			/* 20 = getpid */
	"mount",			/* 21 = mount */
	"unmount",			/* 22 = unmount */
	"setuid",			/* 23 = setuid */
	"getuid",			/* 24 = getuid */
	"geteuid",			/* 25 = geteuid */
	"ptrace",			/* 26 = ptrace */
	"recvmsg",			/* 27 = recvmsg */
	"sendmsg",			/* 28 = sendmsg */
	"recvfrom",			/* 29 = recvfrom */
	"accept",			/* 30 = accept */
	"getpeername",			/* 31 = getpeername */
	"getsockname",			/* 32 = getsockname */
	"access",			/* 33 = access */
	"chflags",			/* 34 = chflags */
	"fchflags",			/* 35 = fchflags */
	"sync",			/* 36 = sync */
	"kill",			/* 37 = kill */
	"stat",			/* 38 = stat */
	"getppid",			/* 39 = getppid */
	"lstat",			/* 40 = lstat */
	"dup",			/* 41 = dup */
	"pipe",			/* 42 = pipe */
	"getegid",			/* 43 = getegid */
	"obs_profil",			/* 44 = obsolete profil profil junk X void *bufbase, size_t bufsize, unsigned pcoffset, unsigned pcscale */
	"#45",			/* 45 = ktrace ktrace */
	"sigaction",			/* 46 = sigaction */
	"getgid",			/* 47 = getgid */
	"sigprocmask",			/* 48 = sigprocmask */
	"getlogin",			/* 49 = getlogin */
	"setlogin",			/* 50 = setlogin */
	"acct",			/* 51 = acct */
#if MAP_UAREA
	"sigpending",			/* 52 = sigpending */
#else
	"sigpending",			/* 52 = sigpending */
#endif
#ifdef notyet
#else
	"#53",			/* 53 = sigaltstack sigaltstack */
#endif
	"ioctl",			/* 54 = ioctl */
	"reboot",			/* 55 = reboot */
	"revoke",			/* 56 = revoke */
	"symlink",			/* 57 = symlink */
	"readlink",			/* 58 = readlink */
	"execve",			/* 59 = execve */
#if NMAP_UAREA
	"umask",			/* 60 = umask */
#else
	"umask",			/* 60 = umask */
#endif
	"chroot",			/* 61 = chroot */
	"fstat",			/* 62 = fstat */
	"obs_getkerninfo",			/* 63 = obsolete getkerninfo getkerninfo int ? int op, char *where, int *size, int arg */
	"getpagesize",			/* 64 = getpagesize */
	"msync",			/* 65 = msync */
	"vfork",			/* 66 = vfork */
	"obs_vread",			/* 67 = obsolete vread vread */
	"obs_vwrite",			/* 68 = obsolete vwrite vwrite */
	"sbrk",			/* 69 = sbrk */
	"obs_sstk",			/* 70 = obsolete sstk sstk */
	"mmap",			/* 71 = mmap */
	"obs_ovadvise",			/* 72 = obsolete ovadvise vadvise */
	"munmap",			/* 73 = munmap */
	"mprotect",			/* 74 = mprotect */
	"madvise",			/* 75 = madvise */
	"obs_vhangup",			/* 76 = obsolete vhangup vhangup */
	"obs_vlimit",			/* 77 = obsolete vlimit vlimit */
	"mincore",			/* 78 = mincore */
	"getgroups",			/* 79 = getgroups */
	"setgroups",			/* 80 = setgroups */
	"getpgrp",			/* 81 = getpgrp */
	"setpgid",			/* 82 = setpgid */
	"setitimer",			/* 83 = setitimer */
	"wait",			/* 84 = wait */
	"swapon",			/* 85 = swapon */
	"getitimer",			/* 86 = getitimer */
	"gethostname",			/* 87 = gethostname */
	"sethostname",			/* 88 = sethostname */
	"getdtablesize",			/* 89 = getdtablesize */
	"dup2",			/* 90 = dup2 */
	"#91",			/* 91 = getdopt getdopt */
	"fcntl",			/* 92 = fcntl */
	"select",			/* 93 = select */
	"#94",			/* 94 = setdopt setdopt */
	"fsync",			/* 95 = fsync */
	"setpriority",			/* 96 = setpriority */
	"socket",			/* 97 = socket */
	"connect",			/* 98 = connect */
	"obs_accept",			/* 99 = obsolete accept accept int fd int s, struct sockaddr *addr, int *addrlen */
	"getpriority",			/* 100 = getpriority */
	"send",			/* 101 = send */
	"recv",			/* 102 = recv */
	"sigreturn",			/* 103 = sigreturn */
	"bind",			/* 104 = bind */
	"setsockopt",			/* 105 = setsockopt */
	"listen",			/* 106 = listen */
	"obs_vtimes",			/* 107 = obsolete vtimes vtimes */
	"sigvec",			/* 108 = sigvec */
#if MAP_UAREA
	"old.sigblock",		/* 109 = old sigblock */
	"old.sigsetmask",		/* 110 = old sigsetmask */
#else
	"old.sigblock",		/* 109 = old sigblock */
	"old.sigsetmask",		/* 110 = old sigsetmask */
#endif
	"sigsuspend",			/* 111 = sigsuspend */
	"old.sigstack",		/* 112 = old sigstack */
	"obs_recvmsg",			/* 113 = obsolete recvmsg recvmsg int nreceived int fd, struct msghdr *msg, int flags */
	"obs_sendmsg",			/* 114 = obsolete sendmsg sendmsg int nset int s, const struct msghdr *msg, int flags */
	"obs_vtrace",			/* 115 = obsolete vtrace vtrace */
	"gettimeofday",			/* 116 = gettimeofday */
	"getrusage",			/* 117 = getrusage */
	"getsockopt",			/* 118 = getsockopt */
	"#119",			/* 119 = nosys nosys */
	"readv",			/* 120 = readv */
	"writev",			/* 121 = writev */
	"settimeofday",			/* 122 = settimeofday */
	"fchown",			/* 123 = fchown */
	"fchmod",			/* 124 = fchmod */
	"obs_recvfrom",			/* 125 = obsolete recvfrom recvfrom int nreceived int s, void *buf, int len, int flags, struct sockaddr *from, int *fromlen */
	"old.setreuid",		/* 126 = old setreuid */
	"old.setregid",		/* 127 = old setregid */
	"rename",			/* 128 = rename */
	"truncate",			/* 129 = truncate */
	"ftruncate",			/* 130 = ftruncate */
	"flock",			/* 131 = flock */
	"mkfifo",			/* 132 = mkfifo */
	"sendto",			/* 133 = sendto */
	"shutdown",			/* 134 = shutdown */
	"socketpair",			/* 135 = socketpair */
	"mkdir",			/* 136 = mkdir */
	"rmdir",			/* 137 = rmdir */
	"utimes",			/* 138 = utimes */
	"obs_4.2",			/* 139 = obsolete 4.2 sigreturn sigreturn */
	"adjtime",			/* 140 = adjtime */
	"obs_getpeername",			/* 141 = obsolete getpeername getpeername junk X int s, struct sockaddr *name, int *namelen */
	"gethostid",			/* 142 = gethostid */
	"sethostid",			/* 143 = sethostid */
#if MAP_UAREA
	"getrlimit",			/* 144 = getrlimit */
#else
	"getrlimit",			/* 144 = getrlimit */
#endif
	"setrlimit",			/* 145 = setrlimit */
	"old.killpg",		/* 146 = old killpg */
	"setsid",			/* 147 = setsid */
	"quotactl",			/* 148 = quotactl */
	"quota",			/* 149 = quota */
	"obs_getsockname",			/* 150 = obsolete getsockname getsockname junk X int s, struct sockaddr *name, int *namelen */
	"#151",			/* 151 = nosys nosys */
	"#152",			/* 152 = nosys nosys */
	"#153",			/* 153 = nosys nosys */
	"#154",			/* 154 = nosys nosys */
#if NFS
	"nfssvc",			/* 155 = nfssvc */
#else
	"#155",			/* 155 = nosys nosys */
#endif
	"getdirentries",			/* 156 = getdirentries */
	"statfs",			/* 157 = statfs */
	"fstatfs",			/* 158 = fstatfs */
	"#159",			/* 159 = nosys nosys */
	"#160",			/* 160 = nosys nosys */
#if NFS
	"getfh",			/* 161 = getfh */
#else
	"#161",			/* 161 = nosys nosys */
#endif
	"getdomainname",			/* 162 = getdomainname */
	"setdomainname",			/* 163 = setdomainname */
	"uname",			/* 164 = uname */
	"#165",			/* 165 = nosys nosys */
	"#166",			/* 166 = nosys nosys */
	"#167",			/* 167 = nosys nosys */
	"#168",			/* 168 = nosys nosys */
	"#169",			/* 169 = nosys nosys */
	"#170",			/* 170 = nosys nosys */
#if SYSVSHM
	"shmsys",			/* 171 = shmsys */
#else
	"#171",			/* 171 = nosys nosys */
#endif
	"#172",			/* 172 = nosys nosys */
	"#173",			/* 173 = nosys nosys */
	"#174",			/* 174 = nosys nosys */
	"#175",			/* 175 = nosys nosys */
	"#176",			/* 176 = nosys nosys */
	"#177",			/* 177 = nosys nosys */
	"#178",			/* 178 = nosys nosys */
	"#179",			/* 179 = nosys nosys */
	"#180",			/* 180 = nosys nosys */
	"setgid",			/* 181 = setgid */
	"setegid",			/* 182 = setegid */
	"seteuid",			/* 183 = seteuid */
	"#184",			/* 184 = nosys nosys */
	"#185",			/* 185 = nosys nosys */
	"#186",			/* 186 = nosys nosys */
	"#187",			/* 187 = nosys nosys */
	"#188",			/* 188 = nosys nosys */
	"#189",			/* 189 = nosys nosys */
	"#190",			/* 190 = nosys nosys */
	"#191",			/* 191 = nosys nosys */
	"#192",			/* 192 = nosys nosys */
	"#193",			/* 193 = nosys nosys */
	"#194",			/* 194 = nosys nosys */
	"#195",			/* 195 = nosys nosys */
	"#196",			/* 196 = nosys nosys */
	"#197",			/* 197 = nosys nosys */
	"#198",			/* 198 = nosys nosys */
	"#199",			/* 199 = nosys nosys */
	"table",			/* 200 = table */
	"sysctrace",			/* 201 = sysctrace */
	"__sysctl",			/* 202 = __sysctl */
};
