#!/usr/bin/env python3
# Copyright (c) 2026 Alessandro Sangiuliano (Slex) <alex22_7@hotmail.com>
# SPDX-License-Identifier: MIT
#
# gen-fbcons-font.py — regenerate the 8x16 console font used by the in-kernel
# emergency framebuffer console (i386/AT386/fbcons.c, #342).
#
# Reads a PC Screen Font (PSF1 or PSF2, 8x16) and emits the C glyph table
# i386/AT386/fbcons_font.h.  The default source is the public-domain CP850 VGA
# font shipped by the kbd package; its codepage-437/850 layout matches what the
# kernel prints for ASCII and for the box-drawing/banner glyphs.
#
# Usage:
#   scripts/gen-fbcons-font.py [PSF.gz] > uros/src/mach_kernel/i386/AT386/fbcons_font.h

import gzip, struct, sys, os

DEFAULT = "/usr/share/kbd/consolefonts/cp850-8x16.psfu.gz"


def load_glyphs(path):
    data = gzip.open(path, "rb").read() if path.endswith(".gz") else open(path, "rb").read()
    if data[:2] == b"\x36\x04":            # PSF1
        mode, charsize = data[2], data[3]
        nglyphs = 512 if (mode & 0x01) else 256
        return data[4:4 + nglyphs * charsize], 8, charsize
    if data[:4] == b"\x72\xb5\x4a\x86":    # PSF2
        (_v, hsize, _f, length, charsize, height, width) = struct.unpack("<IIIIIII", data[4:32])
        return data[hsize:hsize + length * charsize], width, height
    sys.exit("unknown PSF magic %r in %s" % (data[:4], path))


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    glyphs, width, height = load_glyphs(path)
    if (width, height) != (8, 16):
        sys.exit("expected an 8x16 font, got %dx%d" % (width, height))
    cs = 16
    out = [
        "/*",
        " * Copyright (c) 2026 Alessandro Sangiuliano (Slex) <alex22_7@hotmail.com>",
        " * SPDX-License-Identifier: MIT",
        " */",
        "",
        "#ifndef _I386_AT386_FBCONS_FONT_H_",
        "#define _I386_AT386_FBCONS_FONT_H_",
        "",
        "/* 8x16 console font, codepage-437/850 layout (public-domain PC VGA font,",
        " * regenerated by scripts/gen-fbcons-font.py from %s)." % os.path.basename(path),
        " * 256 glyphs, 16 bytes each, MSB=left. */",
        "static const unsigned char fbcons_font8x16[256][16] = {",
    ]
    for g in range(256):
        rows = glyphs[g * cs:(g + 1) * cs].ljust(cs, b"\x00")
        out.append("  { %s }, /* 0x%02x */" % (",".join("0x%02x" % b for b in rows), g))
    out += ["};", "", "#endif\t/* _I386_AT386_FBCONS_FONT_H_ */", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
