/*
 * Copyright 1991-1998 by Open Software Foundation, Inc. 
 *              All Rights Reserved 
 *  
 * Permission to use, copy, modify, and distribute this software and 
 * its documentation for any purpose and without fee is hereby granted, 
 * provided that the above copyright notice appears in all copies and 
 * that both the copyright notice and this permission notice appear in 
 * supporting documentation. 
 *  
 * OSF DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE 
 * INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
 * FOR A PARTICULAR PURPOSE. 
 *  
 * IN NO EVENT SHALL OSF BE LIABLE FOR ANY SPECIAL, INDIRECT, OR 
 * CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN ACTION OF CONTRACT, 
 * NEGLIGENCE, OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
 * WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. 
 */
/*
 * MkLinux
 */
/* CMU_HIST */
/*
 * Revision 2.3  92/08/03  17:16:40  jfriedl
 * 	Hacked boot_load_program and read_emulator_symbols to print
 * 	the location of unix and emulator symbols.  This is to make
 * 	sure startup loads the emulator text from the same place as
 * 	the emulator symbol table.
 * 	[92/08/02            cmaeda]
 * 
 * Revision 2.2  92/01/03  19:57:44  dbg
 *      Close startup file after loading it.
 * 	[91/09/25            dbg]
 * 
 * 	Move outside of kernel.
 * 	[91/09/04            dbg]
 * 
 * Revision 2.14  91/09/04  11:27:54  jsb
 * 	Fixed a printf in read_symtab_from_file (following failure of
 * 	get_symtab) by not printing unset variable ``result''.
 * 	[91/09/01  07:48:45  jsb]
 * 
 * Revision 2.13  91/08/28  11:09:49  jsb
 * 	Fixed to check vm_allocate return codes, esp in read_symtab_from_file.
 * 	[91/08/26            rpd]
 * 
 * Revision 2.12  91/07/31  17:25:29  dbg
 * 	Replace blkclr with bzero.
 * 	[91/07/26            dbg]
 * 
 * 	Moved read_symtab_from_file here and made independent of load
 * 	format.
 * 	[91/06/25            dbg]
 * 
 * 
 * Revision 2.11  91/05/14  15:23:41  mrt
 * 	Correcting copyright
 * 
 * Revision 2.10  91/03/16  14:41:37  rpd
 * 	Fixed read_emulator_symbols to not panic if there is no emulator.
 * 	[91/03/13            rpd]
 * 
 * Revision 2.9  91/02/05  17:01:45  mrt
 * 	Changed to new copyright
 * 	[91/01/28  14:55:09  mrt]
 * 
 * Revision 2.8  90/10/25  14:42:05  rwd
 * 	Modified boot_load_program and read_emulator_symbols
 * 	to allocate arrays from heap, not stack.
 * 	[90/10/23            rpd]
 * 
 * Revision 2.7  90/08/27  21:46:02  dbg
 * 	Reduce lint.
 * 	[90/08/13            dbg]
 * 
 * 	Use new error codes.  Use new file_io package.
 * 	[90/07/16            dbg]
 * 
 * Revision 2.6  90/06/02  14:45:31  rpd
 * 	Added read_emulator_symbols.
 * 	[90/05/11  17:08:19  rpd]
 * 
 * 	From jsb: to support debugging, read in the server's symbol table.
 * 	[90/04/23            rpd]
 * 	Converted to new IPC.
 * 	[90/03/26  21:31:33  rpd]
 * 
 * Revision 2.5  90/01/11  11:41:20  dbg
 * 	Use bootstrap-task print routines.
 * 	[89/12/20            dbg]
 * 
 * Revision 2.4  89/11/14  10:28:13  dbg
 * 	Restore read-only protection for text segment.
 * 	[89/11/01            dbg]
 * 
 * Revision 2.3  89/09/08  11:22:13  dbg
 * 	Use new open_file routine.  Change 'struct inode' to
 * 	'struct file' for new stand-alone IO package.
 * 	[89/08/31            dbg]
 * 
 * 26-May-89  Randall Dean (rwd) at Carnegie-Mellon University
 *	Fixed separate text/data case.  Added copyright to version
 *	generated by dbg
 *
 */
/* CMU_ENDHIST */
/* 
 * Mach Operating System
 * Copyright (c) 1991,1990,1989,1988 Carnegie Mellon University
 * All Rights Reserved.
 * 
 * Permission to use, copy, modify and distribute this software and its
 * documentation is hereby granted, provided that both the copyright
 * notice and this permission notice appear in all copies of the
 * software, derivative works or modified versions, and any portions
 * thereof, and that both notices appear in supporting documentation.
 * 
 * CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
 * CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
 * ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
 * 
 * Carnegie Mellon requests users of this software to return to
 * 
 *  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
 *  School of Computer Science
 *  Carnegie Mellon University
 *  Pittsburgh PA 15213-3890
 * 
 * any improvements or extensions that they make and grant Carnegie Mellon
 * the rights to redistribute these changes.
 */

#include "bootstrap.h"
#include "elf.h"
#include <stdarg.h>
#include <ddb/nlist.h>

/*
 * Apply R_386_RELATIVE relocations to a position-independent (ET_DYN)
 * executable image sitting in a local buffer, before it's written to
 * the user task.
 *
 *   area_start  — local buffer holding the segment data
 *   alloc_start — VA that area_start represents (= seg_lo, post-bias)
 *   alloc_size  — size of the buffer
 *   load_bias   — bias added to every PT_LOAD vaddr by elf_load()
 *   dyn_vaddr   — runtime VA (post-bias) of the .dynamic array
 *   dyn_size    — size of .dynamic in bytes
 *
 * Returns KERN_SUCCESS or an error code.  Fails loudly on any
 * relocation type other than R_386_RELATIVE; static-PIE executables
 * linked with -pie -Bsymbolic -Wl,--no-dynamic-linker should only
 * emit RELATIVE relocations.
 */
static int
apply_pie_relocations(vm_offset_t area_start,
		      vm_offset_t alloc_start,
		      vm_size_t   alloc_size,
		      vm_offset_t load_bias,
		      vm_offset_t dyn_vaddr,
		      vm_size_t   dyn_size)
{
	const Elf32_Dyn *dyn;
	vm_offset_t rel_vaddr = 0;
	unsigned long rel_size = 0;
	unsigned long rel_ent  = sizeof(Elf32_Rel);
	unsigned long i, n;
	const Elf32_Rel *rel;

	if (dyn_vaddr < alloc_start
	    || dyn_vaddr + dyn_size > alloc_start + alloc_size) {
		BOOTSTRAP_IO_LOCK();
		printf("PIE: PT_DYNAMIC outside mapped range\n");
		BOOTSTRAP_IO_UNLOCK();
		return EX_NOT_EXECUTABLE;
	}

	dyn = (const Elf32_Dyn *)(area_start + (dyn_vaddr - alloc_start));
	for (i = 0; i < dyn_size / sizeof(Elf32_Dyn); i++) {
		if (dyn[i].d_tag == DT_NULL)
			break;
		switch (dyn[i].d_tag) {
		case DT_REL:
			rel_vaddr = (vm_offset_t)dyn[i].d_un.d_ptr + load_bias;
			break;
		case DT_RELSZ:
			rel_size = (unsigned long)dyn[i].d_un.d_val;
			break;
		case DT_RELENT:
			rel_ent = (unsigned long)dyn[i].d_un.d_val;
			break;
		case DT_RELA:
		case DT_RELASZ:
			BOOTSTRAP_IO_LOCK();
			printf("PIE: DT_RELA not supported on i386\n");
			BOOTSTRAP_IO_UNLOCK();
			return EX_NOT_EXECUTABLE;
		default:
			break;
		}
	}

	if (rel_size == 0)
		return KERN_SUCCESS;	/* no relocations — nothing to do */

	if (rel_vaddr < alloc_start
	    || rel_vaddr + rel_size > alloc_start + alloc_size) {
		BOOTSTRAP_IO_LOCK();
		printf("PIE: DT_REL table outside mapped range\n");
		BOOTSTRAP_IO_UNLOCK();
		return EX_NOT_EXECUTABLE;
	}
	if (rel_ent != sizeof(Elf32_Rel)) {
		BOOTSTRAP_IO_LOCK();
		printf("PIE: unexpected DT_RELENT %lu\n", rel_ent);
		BOOTSTRAP_IO_UNLOCK();
		return EX_NOT_EXECUTABLE;
	}

	rel = (const Elf32_Rel *)(area_start + (rel_vaddr - alloc_start));
	n = rel_size / rel_ent;
	for (i = 0; i < n; i++) {
		unsigned char type = ELF32_R_TYPE(rel[i].r_info);
		vm_offset_t target_vaddr;
		unsigned long *slot;

		if (type == R_386_NONE)
			continue;
		if (type != R_386_RELATIVE) {
			BOOTSTRAP_IO_LOCK();
			printf("PIE: unsupported reloc type %u at 0x%lx\n",
			       (unsigned)type,
			       (unsigned long)rel[i].r_offset);
			BOOTSTRAP_IO_UNLOCK();
			return EX_NOT_EXECUTABLE;
		}

		target_vaddr = (vm_offset_t)rel[i].r_offset + load_bias;
		if (target_vaddr < alloc_start
		    || target_vaddr + sizeof(unsigned long)
		       > alloc_start + alloc_size) {
			BOOTSTRAP_IO_LOCK();
			printf("PIE: reloc target 0x%lx outside mapped range\n",
			       (unsigned long)target_vaddr);
			BOOTSTRAP_IO_UNLOCK();
			return EX_NOT_EXECUTABLE;
		}

		slot = (unsigned long *)(area_start
					 + (target_vaddr - alloc_start));
		*slot += load_bias;
	}

	return KERN_SUCCESS;
}

int load_program_file(struct file *, task_port_t, thread_port_t, objfmt_t);
void read_symtab_from_file(struct file *, mach_port_t, task_port_t,
			   const char *, objfmt_t);

/*
 * Loads the file into the user space of the specified task,
 * and sets up the starting thread's registers.
 */

boolean_t	load_protect_text = TRUE;

int
load_program_file(struct file	*fp,
		  task_port_t		user_task,
		  thread_port_t		user_thread,
		  objfmt_t		ofmt)
{
	struct loader_info	*lp = &ofmt->info;
	kern_return_t		result;
	vm_offset_t		text_page_start,
				text_page_end,
				data_page_start,
				data_page_end,
				area_start,
	                        zero_page_start;

	/*
         * Map page 0 so that the program doesn't get it as
	 * the result of a vm_allocate() or whatever.
	 */
	zero_page_start = 0;
	(void) vm_map(user_task, &zero_page_start, vm_page_size,
			0, FALSE, MEMORY_OBJECT_NULL, 0, TRUE,
			VM_PROT_NONE, VM_PROT_NONE, VM_INHERIT_COPY);

	/*
	 * Multi-segment ELF loading path.
	 * Handles modern linker output with separate R / R+X / R+W
	 * LOAD segments (e.g. -z separate-code).
	 */
	if (lp->num_segments > 0) {
	    vm_offset_t seg_lo = ~(vm_offset_t)0;
	    vm_offset_t seg_hi = 0;
	    vm_offset_t alloc_start, alloc_end;
	    int s;

	    /* Compute the VA extent covering all segments */
	    for (s = 0; s < lp->num_segments; s++) {
		struct load_segment *seg = &lp->segments[s];
		vm_offset_t lo = trunc_page(seg->seg_vaddr);
		vm_offset_t hi = round_page(seg->seg_vaddr + seg->seg_memsz);
		if (lo < seg_lo) seg_lo = lo;
		if (hi > seg_hi) seg_hi = hi;
	    }
	    alloc_start = seg_lo;
	    alloc_end   = seg_hi;

	    /* Allocate a local buffer covering the entire range */
	    result = vm_allocate(mach_task_self(), &area_start,
				 (vm_size_t)(alloc_end - alloc_start), TRUE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate segment buffer failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    /* Read each segment from file into the local buffer */
	    for (s = 0; s < lp->num_segments; s++) {
		struct load_segment *seg = &lp->segments[s];
		if (seg->seg_filesz > 0) {
		    result = read_file(fp, seg->seg_offset,
				    area_start + (seg->seg_vaddr - alloc_start),
				    seg->seg_filesz);
		    if (result) {
			BOOTSTRAP_IO_LOCK();
			printf("read segment %d failed\n", s);
			BOOTSTRAP_IO_UNLOCK();
			return (result);
		    }
		}
		/* Zero the BSS portion (memsz > filesz) */
		if (seg->seg_memsz > seg->seg_filesz) {
		    memset((char *)(area_start
				  + (seg->seg_vaddr - alloc_start)
				  + seg->seg_filesz),
			   0,
			   seg->seg_memsz - seg->seg_filesz);
		}
	    }

	    /*
	     * ET_DYN: apply R_386_RELATIVE relocations in the local
	     * buffer before writing it to the user task.  For ET_EXEC
	     * load_bias is 0 and this is a no-op.
	     */
	    if (lp->load_bias != 0) {
		result = apply_pie_relocations(area_start,
					       alloc_start,
					       (vm_size_t)(alloc_end
							   - alloc_start),
					       lp->load_bias,
					       lp->dyn_vaddr,
					       lp->dyn_filesz);
		if (result) {
		    (void) vm_deallocate(mach_task_self(), area_start,
					 (vm_size_t)(alloc_end - alloc_start));
		    return (result);
		}
	    }

	    /* Allocate the range in the user task at the exact VA */
	    result = vm_allocate(user_task, &alloc_start,
				 (vm_size_t)(alloc_end - alloc_start), FALSE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate user segments (%x,%x) failed\n",
		       alloc_start, alloc_end);
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    /* Copy the data into the user task */
	    result = vm_write(user_task, alloc_start,
			      (pointer_t)area_start,
			      (vm_size_t)(alloc_end - alloc_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("write segments failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    /* Free the local buffer */
	    (void) vm_deallocate(mach_task_self(), area_start,
				 (vm_size_t)(alloc_end - alloc_start));

	    /* Apply per-segment protection */
	    if (load_protect_text) {
		for (s = 0; s < lp->num_segments; s++) {
		    struct load_segment *seg = &lp->segments[s];
		    vm_offset_t prot_start = trunc_page(seg->seg_vaddr);
		    vm_size_t   prot_size  = round_page(seg->seg_vaddr
							+ seg->seg_memsz)
					      - prot_start;
		    result = vm_protect(user_task, prot_start, prot_size,
				      FALSE, seg->seg_prot);
		    if (result) {
			BOOTSTRAP_IO_LOCK();
			printf("protect segment %d failed\n", s);
			BOOTSTRAP_IO_UNLOCK();
			return (result);
		    }
		}
	    }

	    return (KERN_SUCCESS);
	}

	/*
	 * Legacy 2-segment (text + data) loading path.
	 * Used by a.out, COFF, ROSE, and old-style ELF binaries.
	 */
	text_page_start = trunc_page(lp->text_start);
	text_page_end   = round_page(lp->text_start + lp->text_size);
	data_page_start = trunc_page(lp->data_start);
	data_page_end   = round_page(lp->data_start + lp->data_size)
		+ round_page(lp->bss_size);

	if (text_page_end >= data_page_start) {
	    /*
	     * One contiguous area for text and data.
	     */
	    result = vm_allocate(mach_task_self(),
				&area_start,
				(vm_size_t)(data_page_end - text_page_start),
				TRUE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate text+data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = read_file(fp,
				lp->text_offset,
				area_start + (lp->text_start - text_page_start),
				lp->text_size);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("read text into text+data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = read_file(fp,
				lp->data_offset,
				area_start + (lp->data_start - text_page_start),
				lp->data_size);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("read data into text+data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    memset((char *)(area_start + (lp->data_start + lp->data_size - text_page_start)),
		   0,
		   lp->bss_size);

	    result = vm_allocate(user_task,
				&text_page_start,
				(vm_size_t)(data_page_end - text_page_start),
				FALSE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate text+data (%x,%x) failed\n", text_page_start,
		       data_page_end);
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_write(user_task,
				text_page_start,
				(pointer_t)area_start,
				(vm_size_t)(data_page_end - text_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("write text+data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_deallocate(mach_task_self(),
				area_start,
				(vm_size_t)(data_page_end - text_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("deallocate text+data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	}
	else {
	    /*
	     * Separated text and data areas.
	     */
	    /*
	     * First read in the text
	     */
	    result = vm_allocate(mach_task_self(),
				&area_start,
				(vm_size_t)(text_page_end - text_page_start), TRUE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate text buffer failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = read_file(fp,
			       lp->text_offset,
			       area_start + (lp->text_start - text_page_start),
			       lp->text_size);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("read text failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_allocate(user_task,
				&text_page_start,
				(vm_size_t)(text_page_end - text_page_start),
				FALSE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate text (%x,%x) failed\n", text_page_start,
		       data_page_end);
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_write(user_task,
				text_page_start,
				(pointer_t)area_start,
				(vm_size_t)(text_page_end - text_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("write text failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_deallocate(mach_task_self(),
				area_start,
				(vm_size_t)(text_page_end - text_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("deallocate text failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    /*
	     * Then the data
	     */
	    result = vm_allocate(mach_task_self(),
				&area_start,
				(vm_size_t)(data_page_end - data_page_start),
				TRUE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate data buffer failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = read_file(fp,
			       lp->data_offset,
			       area_start + (lp->data_start - data_page_start),
			       lp->data_size);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("read data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    memset((char *)(area_start + (lp->data_start + lp->data_size - data_page_start)),
		   0,
		   lp->bss_size);

	    result = vm_allocate(user_task,
				&data_page_start,
				(vm_size_t)(data_page_end - data_page_start),
				FALSE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("allocate data (%x,%x) failed\n", data_page_start,
		       data_page_end);
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_write(user_task,
				data_page_start,
				(pointer_t)area_start,
				(vm_size_t)(data_page_end - data_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("write data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	    result = vm_deallocate(mach_task_self(),
				area_start,
				(vm_size_t)(data_page_end - data_page_start));
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("deallocate data failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }

	}
	/*
	 * Protect the text.
	 */
	if (load_protect_text) {
	    result = vm_protect(user_task,
			    text_page_start,
			    (vm_size_t)(trunc_page(lp->text_start+lp->text_size) - text_page_start),
			    FALSE,
			    VM_PROT_READ|VM_PROT_EXECUTE);
	    if (result) {
		BOOTSTRAP_IO_LOCK();
		printf("protect text failed\n");
		BOOTSTRAP_IO_UNLOCK();
		return (result);
	    }
	}

	return (KERN_SUCCESS);
}

#define	isspace(c)	((c) == ' ' || (c) == '\t')

int
boot_load_program(mach_port_t master_host_port,
		  mach_port_t master_device_port,
		  task_port_t user_task,
		  thread_port_t user_thread,
		  unsigned int server_flags,
		  const char *symtab_name,
		  const char *file_name,
		  unsigned long mapend)
{
	int		arg_len;
	kern_return_t	result;
	struct file	file;
	struct objfmt	ofmt;

	/*
	 * Open the file
	 */

	memset((char *)&ofmt, 0, sizeof (ofmt));
	memset((char *)&file, 0, sizeof(file));
	/*
	 * Issue #185: route through boot_open_file() so stage-2 loads
	 * (after block_device_server is up) flow through BDS, while
	 * stage-1 loads still use the kernel master device port.
	 * master_device_port is preserved for set_regs/symload below.
	 */
	result = boot_open_file(file_name, &file);
	if (result != 0) {
	    BOOTSTRAP_IO_LOCK();
	    printf("openi %d\n", result);
	    BOOTSTRAP_IO_UNLOCK();
	    return (result);
	}
#ifdef DEBUG
	BOOTSTRAP_IO_LOCK();
	printf("bootstrap: opened <%s>\n", file_name);
	BOOTSTRAP_IO_UNLOCK();
#endif

	/*
	 * Read in the header and get the file pointers.
	 */
	result = ex_get_header(&file, &ofmt);
	if (result) {
	    BOOTSTRAP_IO_LOCK();
	    printf("boot_load_program: failed to read file header.\n");
	    BOOTSTRAP_IO_UNLOCK();
	    return (result);
        }

	/*
	 * Allocate space for:
	 *    dummy 0 argument count
	 *    dummy 0 pointer to arguments
	 *    dummy 0 pointer to environment variables
	 *    and align to integer boundary
	 */
	arg_len = sizeof(int) + 2 * sizeof(char *);
	arg_len = (arg_len + (sizeof(int) - 1)) & ~(sizeof(int)-1);

	/*
	 * Load the file
	 */
	result = load_program_file(&file, user_task, user_thread, &ofmt);
	if (result) {
	    BOOTSTRAP_IO_LOCK();
	    printf("load_program_file failed - %d\n", result);
	    BOOTSTRAP_IO_UNLOCK();
	    return (result);
	}

	set_regs(master_host_port, user_task,
	    user_thread, &ofmt.info, mapend, arg_len);

	/*
	 * Read symbols from file
	 */
	(*ofmt.fmt->symload)(&file, master_host_port, user_task,
			     symtab_name, &ofmt);
	/*
	 * Close the file.
	 */
	close_file(&file);
	return (0);
}

int
ex_get_header(struct file *fp, objfmt_t ofmt)
{
    int i;
    objfmt_switch_t fmt;
    char buf[HEADER_MAX], *bufptr = buf;
    int result;

    result = read_file(fp, 0, (vm_offset_t)buf, sizeof(buf));
    if (result)
	return (result);

    for (i = 0; formats[i] != 0; i++) {
	fmt = formats[i];
	if (!(*fmt->recog)(fp, ofmt, &bufptr))
	    continue;
	ofmt->fmt = fmt;
	result = (*fmt->load)(fp, ofmt, bufptr);
	if (bufptr != buf)
	    free(bufptr);
	return result;
    }
    return EX_NOT_EXECUTABLE;
}
